

// Generated by cosim_wrapper.pl to be used for cosim

module edu_cosim_wrapper(interface datain, interface dataout, input _RESET);

 edu edu_expanded (datain.e[0] , datain.e[10] , datain.e[1] , datain.e[2] , datain.e[3] , datain.e[4] 
 , datain.e[5] , datain.e[6] , datain.e[7] , datain.e[8] , datain.e[9] , dataout.d[0][0] 
 , dataout.d[0][10] , dataout.d[0][1] , dataout.d[0][2] , dataout.d[0][3] , dataout.d[0][4] , dataout.d[0][5] 
 , dataout.d[0][6] , dataout.d[0][7] , dataout.d[0][8] , dataout.d[0][9] , dataout.d[1][0] , dataout.d[1][10] 
 , dataout.d[1][1] , dataout.d[1][2] , dataout.d[1][3] , dataout.d[1][4] , dataout.d[1][5] , dataout.d[1][6] 
 , dataout.d[1][7] , dataout.d[1][8] , dataout.d[1][9] , datain.d[0][0] , datain.d[0][10] , datain.d[0][1] 
 , datain.d[0][2] , datain.d[0][3] , datain.d[0][4] , datain.d[0][5] , datain.d[0][6] , datain.d[0][7] 
 , datain.d[0][8] , datain.d[0][9] , datain.d[1][0] , datain.d[1][10] , datain.d[1][1] , datain.d[1][2] 
 , datain.d[1][3] , datain.d[1][4] , datain.d[1][5] , datain.d[1][6] , datain.d[1][7] , datain.d[1][8] 
 , datain.d[1][9] , dataout.e[0] , dataout.e[10] , dataout.e[1] , dataout.e[2] , dataout.e[3] 
 , dataout.e[4] , dataout.e[5] , dataout.e[6] , dataout.e[7] , dataout.e[8] , dataout.e[9] 
 , _RESET );

endmodule

// Generated by E-GRAPH (EGS) v0.01

module edu (\datain_e[0] , \datain_e[10] , \datain_e[1] , \datain_e[2] , \datain_e[3] , \datain_e[4] , \datain_e[5] , 
  \datain_e[6] , \datain_e[7] , \datain_e[8] , \datain_e[9] , \dataout_d[0][0] , \dataout_d[0][10] , \dataout_d[0][1] , 
  \dataout_d[0][2] , \dataout_d[0][3] , \dataout_d[0][4] , \dataout_d[0][5] , \dataout_d[0][6] , \dataout_d[0][7] , 
  \dataout_d[0][8] , \dataout_d[0][9] , \dataout_d[1][0] , \dataout_d[1][10] , \dataout_d[1][1] , \dataout_d[1][2] , 
  \dataout_d[1][3] , \dataout_d[1][4] , \dataout_d[1][5] , \dataout_d[1][6] , \dataout_d[1][7] , \dataout_d[1][8] , 
  \dataout_d[1][9] , \datain_d[0][0] , \datain_d[0][10] , \datain_d[0][1] , \datain_d[0][2] , \datain_d[0][3] , \datain_d[0][4] , 
  \datain_d[0][5] , \datain_d[0][6] , \datain_d[0][7] , \datain_d[0][8] , \datain_d[0][9] , \datain_d[1][0] , \datain_d[1][10] , 
  \datain_d[1][1] , \datain_d[1][2] , \datain_d[1][3] , \datain_d[1][4] , \datain_d[1][5] , \datain_d[1][6] , \datain_d[1][7] , 
  \datain_d[1][8] , \datain_d[1][9] , \dataout_e[0] , \dataout_e[10] , \dataout_e[1] , \dataout_e[2] , \dataout_e[3] , 
  \dataout_e[4] , \dataout_e[5] , \dataout_e[6] , \dataout_e[7] , \dataout_e[8] , \dataout_e[9] , _RESET );
  input  \datain_d[0][0] , \datain_d[0][10] , \datain_d[0][1] , \datain_d[0][2] , \datain_d[0][3] , \datain_d[0][4] ;
  input  \datain_d[0][5] , \datain_d[0][6] , \datain_d[0][7] , \datain_d[0][8] , \datain_d[0][9] , \datain_d[1][0] ;
  input  \datain_d[1][10] , \datain_d[1][1] , \datain_d[1][2] , \datain_d[1][3] , \datain_d[1][4] , \datain_d[1][5] ;
  input  \datain_d[1][6] , \datain_d[1][7] , \datain_d[1][8] , \datain_d[1][9] , \dataout_e[0] , \dataout_e[10] , \dataout_e[1] ;
  input  \dataout_e[2] , \dataout_e[3] , \dataout_e[4] , \dataout_e[5] , \dataout_e[6] , \dataout_e[7] , \dataout_e[8] ;
  input  \dataout_e[9] , _RESET ;

  output \datain_e[0] , \datain_e[10] , \datain_e[1] , \datain_e[2] , \datain_e[3] , \datain_e[4] , \datain_e[5] , \datain_e[6] ;
  output \datain_e[7] , \datain_e[8] , \datain_e[9] , \dataout_d[0][0] , \dataout_d[0][10] , \dataout_d[0][1] ;
  output \dataout_d[0][2] , \dataout_d[0][3] , \dataout_d[0][4] , \dataout_d[0][5] , \dataout_d[0][6] , \dataout_d[0][7] ;
  output \dataout_d[0][8] , \dataout_d[0][9] , \dataout_d[1][0] , \dataout_d[1][10] , \dataout_d[1][1] , \dataout_d[1][2] ;
  output \dataout_d[1][3] , \dataout_d[1][4] , \dataout_d[1][5] , \dataout_d[1][6] , \dataout_d[1][7] , \dataout_d[1][8] ;
  output \dataout_d[1][9] ;

  wire   \d[10].0 , \d[10].1 , \d[10]_64.e , \d[10]_66.e , \d[10]_70.e , \d[10]_SX0_iter2.0 , \d[10]_SX0_iter2.1 ;
  wire   \d[10]_SX0_iter2.e , \d[10]_SX0_iter2_0.0 , \d[10]_SX0_iter2_0.1 , \d[10]_SX0_iter2_0.e , \d[10]_SX0_iter2_1.0 ;
  wire   \d[10]_SX0_iter2_1.1 , \d[10]_SX1_iter2.0 , \d[10]_SX1_iter2.1 , \d[10]_SX1_iter2_0.0 , \d[10]_SX1_iter2_0.1 ;
  wire   \d[10]_SX1_iter2_0.e , \d[10]_SX2_iter2.0 , \d[10]_SX2_iter2.1 , \d[10]_SX2_iter2.e , \d[10]_SX3_iter2.0 ;
  wire   \d[10]_SX3_iter2.1 , \d[4].0 , \d[4].1 , \d[4]_71.e , \d[4]_73.e , \d[4]_SX0_iter2.0 , \d[4]_SX0_iter2.1 ;
  wire   \d[4]_SX0_iter2.e , \d[4]_SX0_iter2_0.0 , \d[4]_SX0_iter2_0.1 , \d[4]_SX0_iter2_0.e , \d[4]_SX1_iter2.0 ;
  wire   \d[4]_SX1_iter2.1 , \d[4]_SX1_iter2_0.0 , \d[4]_SX1_iter2_0.1 , \d[4]_SX1_iter2_0.e , \d[4]_SX2_iter2.0 ;
  wire   \d[4]_SX2_iter2.1 , \d[5].0 , \d[5].1 , \d[5]_76.e , \d[5]_79.e , \d[5]_SX0_iter2.0 , \d[5]_SX0_iter2.1 ;
  wire   \d[5]_SX0_iter2.e , \d[5]_SX0_iter2_0.0 , \d[5]_SX0_iter2_0.1 , \d[5]_SX0_iter2_0.e , \d[5]_SX1_iter2.0 ;
  wire   \d[5]_SX1_iter2.1 , \d[5]_SX1_iter2.e , \d[5]_SX1_iter2_0.0 , \d[5]_SX1_iter2_0.1 , \d[5]_SX2_iter2.0 ;
  wire   \d[5]_SX2_iter2.1 , \d[6].0 , \d[6].1 , \d[6]_81.e , \d[6]_84.e , \d[6]_SX0_iter2.0 , \d[6]_SX0_iter2.1 ;
  wire   \d[6]_SX0_iter2.e , \d[6]_SX0_iter2_0.0 , \d[6]_SX0_iter2_0.1 , \d[6]_SX0_iter2_0.e , \d[6]_SX1_iter2.0 ;
  wire   \d[6]_SX1_iter2.1 , \d[6]_SX1_iter2.e , \d[6]_SX1_iter2_0.0 , \d[6]_SX1_iter2_0.1 , \d[6]_SX1_iter2_0.e ;
  wire   \d[6]_SX2_iter2.0 , \d[6]_SX2_iter2.1 , \d[6]_SX2_iter2_0.0 , \d[6]_SX2_iter2_0.1 , \d[6]_SX2_iter2_0.e ;
  wire   \d[6]_SX3_iter2.0 , \d[6]_SX3_iter2.1 , \d[7].0 , \d[7].1 , \d[7]_88.e , \d[7]_90.e , \d[7]_SX0_iter2.0 ;
  wire   \d[7]_SX0_iter2.1 , \d[7]_SX0_iter2.e , \d[7]_SX0_iter2_0.0 , \d[7]_SX0_iter2_0.1 , \d[7]_SX0_iter2_0.e ;
  wire   \d[7]_SX1_iter2.0 , \d[7]_SX1_iter2.1 , \d[7]_SX1_iter2_0.0 , \d[7]_SX1_iter2_0.1 , \d[7]_SX1_iter2_0.e ;
  wire   \d[7]_SX2_iter2.0 , \d[7]_SX2_iter2.1 , \d[8].0 , \d[8].1 , \d[8]_93.e , \d[8]_95.e , \d[8]_SX0_iter2.0 ;
  wire   \d[8]_SX0_iter2.1 , \d[8]_SX0_iter2.e , \d[8]_SX0_iter2_0.0 , \d[8]_SX0_iter2_0.1 , \d[8]_SX0_iter2_0.e ;
  wire   \d[8]_SX1_iter2.0 , \d[8]_SX1_iter2.1 , \d[8]_SX1_iter2_0.0 , \d[8]_SX1_iter2_0.1 , \d[8]_SX1_iter2_0.e ;
  wire   \d[8]_SX2_iter2.0 , \d[8]_SX2_iter2.1 , \d[9].0 , \d[9].1 , \d[9]_100.e , \d[9]_98.e , \d[9]_SX0_iter2.0 ;
  wire   \d[9]_SX0_iter2.1 , \d[9]_SX0_iter2.e , \d[9]_SX0_iter2_0.0 , \d[9]_SX0_iter2_0.1 , \d[9]_SX0_iter2_0.e ;
  wire   \d[9]_SX1_iter2.0 , \d[9]_SX1_iter2.1 , \d[9]_SX1_iter2_0.0 , \d[9]_SX1_iter2_0.1 , \d[9]_SX1_iter2_0.e ;
  wire   \d[9]_SX2_iter2.0 , \d[9]_SX2_iter2.1 , \datain_e[0] , \datain_e[10] , \datain_e[1] , \datain_e[2] , \datain_e[3] ;
  wire   \datain_e[4] , \datain_e[5] , \datain_e[6] , \datain_e[7] , \datain_e[8] , \datain_e[9] , \dataout_d[0][0] ;
  wire   \dataout_d[0][10] , \dataout_d[0][1] , \dataout_d[0][2] , \dataout_d[0][3] , \dataout_d[0][4] , \dataout_d[0][5] ;
  wire   \dataout_d[0][6] , \dataout_d[0][7] , \dataout_d[0][8] , \dataout_d[0][9] , \dataout_d[1][0] , \dataout_d[1][10] ;
  wire   \dataout_d[1][1] , \dataout_d[1][2] , \dataout_d[1][3] , \dataout_d[1][4] , \dataout_d[1][5] , \dataout_d[1][6] ;
  wire   \dataout_d[1][7] , \dataout_d[1][8] , \dataout_d[1][9] , \edu_RTL_BODY.n_0.0 , \edu_RTL_BODY.n_0.1 ;
  wire   \edu_RTL_BODY.n_0_61.e , \edu_RTL_BODY.n_0_FX0.0 , \edu_RTL_BODY.n_0_FX0.1 , \edu_RTL_BODY.n_10.0 ;
  wire   \edu_RTL_BODY.n_10.1 , \edu_RTL_BODY.n_11.0 , \edu_RTL_BODY.n_11.1 , \edu_RTL_BODY.n_12.0 , \edu_RTL_BODY.n_12.1 ;
  wire   \edu_RTL_BODY.n_12.e , \edu_RTL_BODY.n_12_SX0_iter2.0 , \edu_RTL_BODY.n_12_SX0_iter2.1 , \edu_RTL_BODY.n_13.0 ;
  wire   \edu_RTL_BODY.n_13.1 , \edu_RTL_BODY.n_13_104.e , \edu_RTL_BODY.n_13_62.e , \edu_RTL_BODY.n_13_FX0.0 ;
  wire   \edu_RTL_BODY.n_13_FX0.1 , \edu_RTL_BODY.n_13_FX0_121.e , \edu_RTL_BODY.n_13_FX0_122.e ;
  wire   \edu_RTL_BODY.n_13_FX0_SX0_iter2.0 , \edu_RTL_BODY.n_13_FX0_SX0_iter2.1 , \edu_RTL_BODY.n_13_FX0_SX0_iter2_0.0 ;
  wire   \edu_RTL_BODY.n_13_FX0_SX0_iter2_0.1 , \edu_RTL_BODY.n_13_SX0_iter2.0 , \edu_RTL_BODY.n_13_SX0_iter2.1 ;
  wire   \edu_RTL_BODY.n_15.0 , \edu_RTL_BODY.n_15.1 , \edu_RTL_BODY.n_15_105.e , \edu_RTL_BODY.n_15_SX0_iter2.0 ;
  wire   \edu_RTL_BODY.n_15_SX0_iter2.1 , \edu_RTL_BODY.n_16.0 , \edu_RTL_BODY.n_16.1 , \edu_RTL_BODY.n_17.0 ;
  wire   \edu_RTL_BODY.n_17.1 , \edu_RTL_BODY.n_18.0 , \edu_RTL_BODY.n_18.1 , \edu_RTL_BODY.n_19.0 , \edu_RTL_BODY.n_19.1 ;
  wire   \edu_RTL_BODY.n_20.0 , \edu_RTL_BODY.n_20.1 , \edu_RTL_BODY.n_21.0 , \edu_RTL_BODY.n_21.1 , \edu_RTL_BODY.n_22.0 ;
  wire   \edu_RTL_BODY.n_22.1 , \edu_RTL_BODY.n_22_118.e , \edu_RTL_BODY.n_22_119.e , \edu_RTL_BODY.n_22_SX0_iter2.0 ;
  wire   \edu_RTL_BODY.n_22_SX0_iter2.1 , \edu_RTL_BODY.n_22_SX0_iter2_0.0 , \edu_RTL_BODY.n_22_SX0_iter2_0.1 ;
  wire   \edu_RTL_BODY.n_22_SX0_iter2_0.e , \edu_RTL_BODY.n_22_SX1_iter2.0 , \edu_RTL_BODY.n_22_SX1_iter2.1 ;
  wire   \edu_RTL_BODY.n_23.0 , \edu_RTL_BODY.n_23.1 , \edu_RTL_BODY.n_23_116.e , \edu_RTL_BODY.n_23_SX0_iter2.0 ;
  wire   \edu_RTL_BODY.n_23_SX0_iter2.1 , \edu_RTL_BODY.n_23_SX0_iter2.e , \edu_RTL_BODY.n_23_SX1_iter2.0 ;
  wire   \edu_RTL_BODY.n_23_SX1_iter2.1 , \edu_RTL_BODY.n_24.0 , \edu_RTL_BODY.n_24.1 , \edu_RTL_BODY.n_24_112.e ;
  wire   \edu_RTL_BODY.n_24_SX0_iter2.0 , \edu_RTL_BODY.n_24_SX0_iter2.1 , \edu_RTL_BODY.n_24_SX0_iter2.e ;
  wire   \edu_RTL_BODY.n_24_SX1_iter2.0 , \edu_RTL_BODY.n_24_SX1_iter2.1 , \edu_RTL_BODY.n_25.0 , \edu_RTL_BODY.n_25.1 ;
  wire   \edu_RTL_BODY.n_25_106.e , \edu_RTL_BODY.n_25_SX0_iter2.0 , \edu_RTL_BODY.n_25_SX0_iter2.1 , \edu_RTL_BODY.n_26.0 ;
  wire   \edu_RTL_BODY.n_26.1 , \edu_RTL_BODY.n_26_111.e , \edu_RTL_BODY.n_26_114.e , \edu_RTL_BODY.n_26_SX0_iter2.0 ;
  wire   \edu_RTL_BODY.n_26_SX0_iter2.1 , \edu_RTL_BODY.n_26_SX0_iter2_0.0 , \edu_RTL_BODY.n_26_SX0_iter2_0.1 ;
  wire   \edu_RTL_BODY.n_26_SX0_iter2_0.e , \edu_RTL_BODY.n_26_SX1_iter2.0 , \edu_RTL_BODY.n_26_SX1_iter2.1 ;
  wire   \edu_RTL_BODY.n_27.0 , \edu_RTL_BODY.n_27.1 , \edu_RTL_BODY.n_27_108.e , \edu_RTL_BODY.n_27_109.e ;
  wire   \edu_RTL_BODY.n_27_SX0_iter2.0 , \edu_RTL_BODY.n_27_SX0_iter2.1 , \edu_RTL_BODY.n_27_SX0_iter2_0.0 ;
  wire   \edu_RTL_BODY.n_27_SX0_iter2_0.1 , \edu_RTL_BODY.n_28.0 , \edu_RTL_BODY.n_28.1 , \edu_RTL_BODY.n_28_107.e ;
  wire   \edu_RTL_BODY.n_28_110.e , \edu_RTL_BODY.n_28_SX0_iter2.0 , \edu_RTL_BODY.n_28_SX0_iter2.1 ;
  wire   \edu_RTL_BODY.n_28_SX0_iter2_0.0 , \edu_RTL_BODY.n_28_SX0_iter2_0.1 , \edu_RTL_BODY.n_29.0 , \edu_RTL_BODY.n_29.1 ;
  wire   \edu_RTL_BODY.n_30.0 , \edu_RTL_BODY.n_30.1 , \edu_RTL_BODY.n_30.e , \edu_RTL_BODY.n_30_SX0_iter2.0 ;
  wire   \edu_RTL_BODY.n_30_SX0_iter2.1 , \edu_RTL_BODY.n_31.0 , \edu_RTL_BODY.n_31.1 , \n_30.0 , \n_30.1 , \n_30.e , \n_31.0 ;
  wire   \n_31.1 , \n_31.e , \n_32.0 , \n_32.1 , \n_32.e , \n_33.0 , \n_33.1 , \n_33.e , \n_35.0 , \n_35.1 , \n_35.e , \n_36.0 ;
  wire   \n_36.1 , \n_36.e , \n_37.0 , \n_37.1 , \n_37.e , \pchb_cloud_12_inst_go , \pchb_cloud_12_inst_valid_out_0 ;
  wire   \pchb_cloud_14_inst_go , \pchb_cloud_14_inst_valid_out_0 , \pchb_cloud_15_inst_go , \pchb_cloud_15_inst_valid_out_0 ;
  wire   \pchb_cloud_16_inst_go , \pchb_cloud_16_inst_valid_out_0 , \pchb_cloud_34_inst_go , \pchb_cloud_34_inst_valid_out_0 ;
  wire   \pchb_cloud_35_inst_go , \pchb_cloud_35_inst_valid_out_0 , \pchb_cloud_47_inst_go , \pchb_cloud_47_inst_valid_out_0 ;
  wire   \pchb_cloud_47_inst_valid_out_1 , \pchb_cloud_49_inst_go , \pchb_cloud_49_inst_valid_out_0 ;
  wire   \pchb_cloud_49_inst_valid_out_1 , \pchb_cloud_49_inst_valid_out_2 , \pchb_cloud_51_inst_go ;
  wire   \pchb_cloud_51_inst_valid_out_0 , \pchb_cloud_51_inst_valid_out_1 , \pchb_cloud_53_inst_go ;
  wire   \pchb_cloud_53_inst_valid_out_0 , \pchb_cloud_53_inst_valid_out_1 , \pchb_cloud_54_inst_go ;
  wire   \pchb_cloud_54_inst_valid_out_0 , \pchb_cloud_54_inst_valid_out_1 , \pchb_cloud_54_inst_valid_out_2 ;
  wire   \pchb_cloud_55_inst_go , \pchb_cloud_55_inst_valid_out_0 , \pchb_cloud_55_inst_valid_out_1 ;
  wire   \pchb_cloud_55_inst_valid_out_2 , \pchb_cloud_58_inst_go , \pchb_cloud_58_inst_valid_out_0 ;
  wire   \pchb_cloud_58_inst_valid_out_1 , \pchb_cloud_59_inst_go , \pchb_cloud_59_inst_valid_out_0 ;
  wire   \pchb_cloud_59_inst_valid_out_1 , \pchb_cloud_59_inst_valid_out_2 , \pchb_cloud_59_inst_valid_out_3 ;
  wire   \pchb_cloud_60_inst_go , \pchb_cloud_60_inst_valid_out_0 , \pchb_cloud_60_inst_valid_out_1 ;

  trireg \c12.e , \c14.e , \c15.e , \c16.e , \c34.e , \c35.e , \c47.e , \c49.e , \c51.e , \c53.e , \c54.e , \c55.e , \c58.e ;
  trireg \c59.e , \c60.e , \pchb_cfbuf_61_FX_inst_en0 , \pchb_cfbuf_62_FX_inst_en0 , \pchb_cloud_12_inst_en0 ;
  trireg \pchb_cloud_14_inst_en0 , \pchb_cloud_15_inst_en0 , \pchb_cloud_16_inst_en0 , \pchb_cloud_34_inst_en0 ;
  trireg \pchb_cloud_35_inst_en0 , \pchb_cloud_36_inst_en0 , \pchb_cloud_37_inst_en0 , \pchb_cloud_38_inst_en0 ;
  trireg \pchb_cloud_39_inst_en0 , \pchb_cloud_40_inst_en0 , \pchb_cloud_41_inst_en0 , \pchb_cloud_42_inst_en0 ;
  trireg \pchb_cloud_47_inst_en0 , \pchb_cloud_49_inst_en0 , \pchb_cloud_49_inst_en2 , \pchb_cloud_51_inst_en0 ;
  trireg \pchb_cloud_53_inst_en0 , \pchb_cloud_54_inst_en0 , \pchb_cloud_54_inst_en1 , \pchb_cloud_54_inst_en2 ;
  trireg \pchb_cloud_55_inst_en0 , \pchb_cloud_55_inst_en1 , \pchb_cloud_58_inst_en0 , \pchb_cloud_59_inst_en0 ;
  trireg \pchb_cloud_59_inst_en1 , \pchb_cloud_59_inst_en2 , \pchb_cloud_59_inst_en3 , \pchb_cloud_60_inst_en0 ;



  \synthesis.qdi.special.BUF.2 \pchb_cloud_0_inst_dataout_SEND.send.bits[10].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \dataout_e[10] ), 
    .\L.0 ( \n_30.0 ), 
    .\L.1 ( \n_30.1 ), 
    .\L.e ( \n_30.e ), 
    .\R.0 ( \dataout_d[0][10] ), 
    .\R.1 ( \dataout_d[1][10] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_1_inst_dataout_SEND.send.bits[4].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \dataout_e[4] ), 
    .\L.0 ( \n_37.0 ), 
    .\L.1 ( \n_37.1 ), 
    .\L.e ( \n_37.e ), 
    .\R.0 ( \dataout_d[0][4] ), 
    .\R.1 ( \dataout_d[1][4] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_2_inst_dataout_SEND.send.bits[5].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \dataout_e[5] ), 
    .\L.0 ( \n_36.0 ), 
    .\L.1 ( \n_36.1 ), 
    .\L.e ( \n_36.e ), 
    .\R.0 ( \dataout_d[0][5] ), 
    .\R.1 ( \dataout_d[1][5] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_3_inst_dataout_SEND.send.bits[6].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \dataout_e[6] ), 
    .\L.0 ( \n_35.0 ), 
    .\L.1 ( \n_35.1 ), 
    .\L.e ( \n_35.e ), 
    .\R.0 ( \dataout_d[0][6] ), 
    .\R.1 ( \dataout_d[1][6] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_4_inst_dataout_SEND.send.bits[7].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \dataout_e[7] ), 
    .\L.0 ( \n_33.0 ), 
    .\L.1 ( \n_33.1 ), 
    .\L.e ( \n_33.e ), 
    .\R.0 ( \dataout_d[0][7] ), 
    .\R.1 ( \dataout_d[1][7] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_5_inst_dataout_SEND.send.bits[8].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \dataout_e[8] ), 
    .\L.0 ( \n_32.0 ), 
    .\L.1 ( \n_32.1 ), 
    .\L.e ( \n_32.e ), 
    .\R.0 ( \dataout_d[0][8] ), 
    .\R.1 ( \dataout_d[1][8] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_6_inst_dataout_SEND.send.bits[9].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \dataout_e[9] ), 
    .\L.0 ( \n_31.0 ), 
    .\L.1 ( \n_31.1 ), 
    .\L.e ( \n_31.e ), 
    .\R.0 ( \dataout_d[0][9] ), 
    .\R.1 ( \dataout_d[1][9] ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \edu_RTL_BODY.g1349 ( 
    .V ( \pchb_cloud_12_inst_valid_out_0 ), 
    .en ( \pchb_cloud_12_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_25_SX0_iter2.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_25_SX0_iter2.1 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_25_SX0_iter2.1 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_25_SX0_iter2.0 ), 
    .\A[2].0 ( \d[5]_SX2_iter2.1 ), 
    .\A[2].1 ( \d[5]_SX2_iter2.0 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_0.1 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_0.0 ), 
    .\X.0 ( \n_36.0 ), 
    .\X.1 ( \n_36.1 ));
  \synthesis.qdi.special.CTREE2.2 \ctreeedu_RTL_BODY.g1349 ( 
    .x ( \pchb_cloud_12_inst_en0 ), 
    .\a[0] ( \pchb_cloud_12_inst_go ), 
    .\a[1] ( \n_36.e ));
  \synthesis.qdi.special.CTRL31.2 \pchb_cloud_12_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_12_inst_go ), 
    .Ae ( \c12.e ), 
    .\A[0].0 ( \edu_RTL_BODY.n_25_SX0_iter2.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_25_SX0_iter2.1 ), 
    .\A[1].0 ( \d[5]_SX2_iter2.0 ), 
    .\A[1].1 ( \d[5]_SX2_iter2.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_0.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_0.1 ), 
    .\V[0] ( \pchb_cloud_12_inst_valid_out_0 ));
  \synthesis.qdi.logic5.LOGIC5_00000777.2 \edu_RTL_BODY.g1352 ( 
    .V ( \pchb_cloud_14_inst_valid_out_0 ), 
    .en ( \pchb_cloud_14_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_28_SX0_iter2.1 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_28_SX0_iter2.0 ), 
    .\A[1].0 ( \d[4]_SX1_iter2.0 ), 
    .\A[1].1 ( \d[4]_SX1_iter2.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_27_SX0_iter2.1 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_27_SX0_iter2.0 ), 
    .\A[3].0 ( \d[9]_SX1_iter2.0 ), 
    .\A[3].1 ( \d[9]_SX1_iter2.1 ), 
    .\A[4].0 ( \edu_RTL_BODY.n_29.0 ), 
    .\A[4].1 ( \edu_RTL_BODY.n_29.1 ), 
    .\X.0 ( \edu_RTL_BODY.n_31.0 ), 
    .\X.1 ( \edu_RTL_BODY.n_31.1 ));
  \synthesis.qdi.special.CTREE2.2 \ctreeedu_RTL_BODY.g1352 ( 
    .x ( \pchb_cloud_14_inst_en0 ), 
    .\a[0] ( \pchb_cloud_14_inst_go ), 
    .\a[1] ( \c35.e ));
  \synthesis.qdi.special.CTRL51.2 \pchb_cloud_14_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_14_inst_go ), 
    .Ae ( \c14.e ), 
    .\A[0].0 ( \edu_RTL_BODY.n_28_SX0_iter2.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_28_SX0_iter2.1 ), 
    .\A[1].0 ( \d[4]_SX1_iter2.0 ), 
    .\A[1].1 ( \d[4]_SX1_iter2.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_27_SX0_iter2.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_27_SX0_iter2.1 ), 
    .\A[3].0 ( \d[9]_SX1_iter2.0 ), 
    .\A[3].1 ( \d[9]_SX1_iter2.1 ), 
    .\A[4].0 ( \edu_RTL_BODY.n_29.0 ), 
    .\A[4].1 ( \edu_RTL_BODY.n_29.1 ), 
    .\V[0] ( \pchb_cloud_14_inst_valid_out_0 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \edu_RTL_BODY.g1353 ( 
    .V ( \pchb_cloud_15_inst_valid_out_0 ), 
    .en ( \pchb_cloud_15_inst_en0 ), 
    .\A[0].0 ( \d[5]_SX1_iter2_0.1 ), 
    .\A[0].1 ( \d[5]_SX1_iter2_0.0 ), 
    .\A[1].0 ( \d[10]_SX1_iter2.1 ), 
    .\A[1].1 ( \d[10]_SX1_iter2.0 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_22_SX0_iter2.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_22_SX0_iter2.1 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_25.0 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_25.1 ), 
    .\X.0 ( \edu_RTL_BODY.n_30.1 ), 
    .\X.1 ( \edu_RTL_BODY.n_30.0 ));
  \synthesis.qdi.special.CTREE2.2 \ctreeedu_RTL_BODY.g1353 ( 
    .x ( \pchb_cloud_15_inst_en0 ), 
    .\a[0] ( \pchb_cloud_15_inst_go ), 
    .\a[1] ( \edu_RTL_BODY.n_30.e ));
  \synthesis.qdi.special.CTRL41.2 \pchb_cloud_15_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_15_inst_go ), 
    .Ae ( \c15.e ), 
    .\A[0].0 ( \d[5]_SX1_iter2_0.0 ), 
    .\A[0].1 ( \d[5]_SX1_iter2_0.1 ), 
    .\A[1].0 ( \d[10]_SX1_iter2.0 ), 
    .\A[1].1 ( \d[10]_SX1_iter2.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_22_SX0_iter2.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_22_SX0_iter2.1 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_25.0 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_25.1 ), 
    .\V[0] ( \pchb_cloud_15_inst_valid_out_0 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \edu_RTL_BODY.g1354 ( 
    .V ( \pchb_cloud_16_inst_valid_out_0 ), 
    .en ( \pchb_cloud_16_inst_en0 ), 
    .\A[0].0 ( \d[8]_SX1_iter2.1 ), 
    .\A[0].1 ( \d[8]_SX1_iter2.0 ), 
    .\A[1].0 ( \d[7]_SX1_iter2.1 ), 
    .\A[1].1 ( \d[7]_SX1_iter2.0 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_24.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_24.1 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_23.0 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_23.1 ), 
    .\X.0 ( \edu_RTL_BODY.n_29.0 ), 
    .\X.1 ( \edu_RTL_BODY.n_29.1 ));
  \synthesis.qdi.special.CTREE2.2 \ctreeedu_RTL_BODY.g1354 ( 
    .x ( \pchb_cloud_16_inst_en0 ), 
    .\a[0] ( \pchb_cloud_16_inst_go ), 
    .\a[1] ( \c14.e ));
  \synthesis.qdi.special.CTRL41.2 \pchb_cloud_16_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_16_inst_go ), 
    .Ae ( \c16.e ), 
    .\A[0].0 ( \d[8]_SX1_iter2.0 ), 
    .\A[0].1 ( \d[8]_SX1_iter2.1 ), 
    .\A[1].0 ( \d[7]_SX1_iter2.0 ), 
    .\A[1].1 ( \d[7]_SX1_iter2.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_24.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_24.1 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_23.0 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_23.1 ), 
    .\V[0] ( \pchb_cloud_16_inst_valid_out_0 ));
  \synthesis.qdi.logic2.LOGIC2_6.2 \edu_RTL_BODY.g1375 ( 
    .V ( \pchb_cloud_34_inst_valid_out_0 ), 
    .en ( \pchb_cloud_34_inst_en0 ), 
    .\A[0].0 ( \d[10].0 ), 
    .\A[0].1 ( \d[10].1 ), 
    .\A[1].0 ( \d[6].0 ), 
    .\A[1].1 ( \d[6].1 ), 
    .\X.0 ( \edu_RTL_BODY.n_10.0 ), 
    .\X.1 ( \edu_RTL_BODY.n_10.1 ));
  \synthesis.qdi.special.CTREE2.2 \ctreeedu_RTL_BODY.g1375 ( 
    .x ( \pchb_cloud_34_inst_en0 ), 
    .\a[0] ( \pchb_cloud_34_inst_go ), 
    .\a[1] ( \c49.e ));
  \synthesis.qdi.special.CTRL21.2 \pchb_cloud_34_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_34_inst_go ), 
    .Ae ( \c34.e ), 
    .\A[0].0 ( \d[10].0 ), 
    .\A[0].1 ( \d[10].1 ), 
    .\A[1].0 ( \d[6].0 ), 
    .\A[1].1 ( \d[6].1 ), 
    .\V[0] ( \pchb_cloud_34_inst_valid_out_0 ));
  \synthesis.qdi.logic4.LOGIC4_0007.4 \edu_RTL_BODY.g2 ( 
    .V ( \pchb_cloud_35_inst_valid_out_0 ), 
    .en ( \pchb_cloud_35_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_26_SX0_iter2.1 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_26_SX0_iter2.0 ), 
    .\A[1].0 ( \d[6]_SX2_iter2.0 ), 
    .\A[1].1 ( \d[6]_SX2_iter2.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_30_SX0_iter2.1 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_30_SX0_iter2.0 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_31.1 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_31.0 ), 
    .\X.0 ( \edu_RTL_BODY.n_0.0 ), 
    .\X.1 ( \edu_RTL_BODY.n_0.1 ));
  \synthesis.qdi.special.CTREE4.2 \ctreeedu_RTL_BODY.g2 ( 
    .x ( \pchb_cloud_35_inst_en0 ), 
    .\a[3] ( \pchb_cloud_35_inst_go ), 
    .\a[0] ( \c12.e ), 
    .\a[1] ( \c51.e ), 
    .\a[2] ( \edu_RTL_BODY.n_0_61.e ));
  \synthesis.qdi.special.CTRL41.2 \pchb_cloud_35_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_35_inst_go ), 
    .Ae ( \c35.e ), 
    .\A[0].0 ( \edu_RTL_BODY.n_26_SX0_iter2.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_26_SX0_iter2.1 ), 
    .\A[1].0 ( \d[6]_SX2_iter2.0 ), 
    .\A[1].1 ( \d[6]_SX2_iter2.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_30_SX0_iter2.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_30_SX0_iter2.1 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_31.0 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_31.1 ), 
    .\V[0] ( \pchb_cloud_35_inst_valid_out_0 ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_36_inst_datain_RECEIVE.recv.bits[10].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \datain_d[0][10] ), 
    .\L.1 ( \datain_d[1][10] ), 
    .\L.e ( \datain_e[10] ), 
    .\R.0 ( \d[10].0 ), 
    .\R.1 ( \d[10].1 ), 
    .\R.e ( \pchb_cloud_36_inst_en0 ));
  \synthesis.qdi.special.CTREE4.2 \pchb_cloud_36_inst_datain_RECEIVE.recv.bits[10].recv_companion0 ( 
    .x ( \pchb_cloud_36_inst_en0 ), 
    .\a[0] ( \d[10]_64.e ), 
    .\a[1] ( \c34.e ), 
    .\a[2] ( \d[10]_66.e ), 
    .\a[3] ( \d[10]_70.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_37_inst_datain_RECEIVE.recv.bits[4].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \datain_d[0][4] ), 
    .\L.1 ( \datain_d[1][4] ), 
    .\L.e ( \datain_e[4] ), 
    .\R.0 ( \d[4].0 ), 
    .\R.1 ( \d[4].1 ), 
    .\R.e ( \pchb_cloud_37_inst_en0 ));
  \synthesis.qdi.special.CTREE3.2 \pchb_cloud_37_inst_datain_RECEIVE.recv.bits[4].recv_companion0 ( 
    .x ( \pchb_cloud_37_inst_en0 ), 
    .\a[0] ( \d[4]_71.e ), 
    .\a[1] ( \c49.e ), 
    .\a[2] ( \d[4]_73.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_38_inst_datain_RECEIVE.recv.bits[5].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \datain_d[0][5] ), 
    .\L.1 ( \datain_d[1][5] ), 
    .\L.e ( \datain_e[5] ), 
    .\R.0 ( \d[5].0 ), 
    .\R.1 ( \d[5].1 ), 
    .\R.e ( \pchb_cloud_38_inst_en0 ));
  \synthesis.qdi.special.CTREE3.2 \pchb_cloud_38_inst_datain_RECEIVE.recv.bits[5].recv_companion0 ( 
    .x ( \pchb_cloud_38_inst_en0 ), 
    .\a[0] ( \d[5]_76.e ), 
    .\a[1] ( \d[5]_79.e ), 
    .\a[2] ( \c49.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_39_inst_datain_RECEIVE.recv.bits[6].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \datain_d[0][6] ), 
    .\L.1 ( \datain_d[1][6] ), 
    .\L.e ( \datain_e[6] ), 
    .\R.0 ( \d[6].0 ), 
    .\R.1 ( \d[6].1 ), 
    .\R.e ( \pchb_cloud_39_inst_en0 ));
  \synthesis.qdi.special.CTREE3.2 \pchb_cloud_39_inst_datain_RECEIVE.recv.bits[6].recv_companion0 ( 
    .x ( \pchb_cloud_39_inst_en0 ), 
    .\a[0] ( \c34.e ), 
    .\a[1] ( \d[6]_81.e ), 
    .\a[2] ( \d[6]_84.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_40_inst_datain_RECEIVE.recv.bits[7].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \datain_d[0][7] ), 
    .\L.1 ( \datain_d[1][7] ), 
    .\L.e ( \datain_e[7] ), 
    .\R.0 ( \d[7].0 ), 
    .\R.1 ( \d[7].1 ), 
    .\R.e ( \pchb_cloud_40_inst_en0 ));
  \synthesis.qdi.special.CTREE3.2 \pchb_cloud_40_inst_datain_RECEIVE.recv.bits[7].recv_companion0 ( 
    .x ( \pchb_cloud_40_inst_en0 ), 
    .\a[0] ( \d[7]_88.e ), 
    .\a[1] ( \d[7]_90.e ), 
    .\a[2] ( \c60.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_41_inst_datain_RECEIVE.recv.bits[8].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \datain_d[0][8] ), 
    .\L.1 ( \datain_d[1][8] ), 
    .\L.e ( \datain_e[8] ), 
    .\R.0 ( \d[8].0 ), 
    .\R.1 ( \d[8].1 ), 
    .\R.e ( \pchb_cloud_41_inst_en0 ));
  \synthesis.qdi.special.CTREE3.2 \pchb_cloud_41_inst_datain_RECEIVE.recv.bits[8].recv_companion0 ( 
    .x ( \pchb_cloud_41_inst_en0 ), 
    .\a[0] ( \d[8]_93.e ), 
    .\a[1] ( \c49.e ), 
    .\a[2] ( \d[8]_95.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_42_inst_datain_RECEIVE.recv.bits[9].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \datain_d[0][9] ), 
    .\L.1 ( \datain_d[1][9] ), 
    .\L.e ( \datain_e[9] ), 
    .\R.0 ( \d[9].0 ), 
    .\R.1 ( \d[9].1 ), 
    .\R.e ( \pchb_cloud_42_inst_en0 ));
  \synthesis.qdi.special.CTREE3.2 \pchb_cloud_42_inst_datain_RECEIVE.recv.bits[9].recv_companion0 ( 
    .x ( \pchb_cloud_42_inst_en0 ), 
    .\a[0] ( \d[9]_98.e ), 
    .\a[1] ( \c49.e ), 
    .\a[2] ( \d[9]_100.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_43_inst_CFMOD_datain_RECEIVE.recv.bits[0].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \datain_d[0][0] ), 
    .\R.0 ( \dataout_d[0][0] ), 
    .\L.1 ( \datain_d[1][0] ), 
    .\R.1 ( \dataout_d[1][0] ), 
    .\L.e ( \datain_e[0] ), 
    .\R.e ( \dataout_e[0] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_44_inst_CFMOD_datain_RECEIVE.recv.bits[1].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \datain_d[0][1] ), 
    .\R.0 ( \dataout_d[0][1] ), 
    .\L.1 ( \datain_d[1][1] ), 
    .\R.1 ( \dataout_d[1][1] ), 
    .\L.e ( \datain_e[1] ), 
    .\R.e ( \dataout_e[1] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_45_inst_CFMOD_datain_RECEIVE.recv.bits[2].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \datain_d[0][2] ), 
    .\R.0 ( \dataout_d[0][2] ), 
    .\L.1 ( \datain_d[1][2] ), 
    .\R.1 ( \dataout_d[1][2] ), 
    .\L.e ( \datain_e[2] ), 
    .\R.e ( \dataout_e[2] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_46_inst_CFMOD_datain_RECEIVE.recv.bits[3].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \datain_d[0][3] ), 
    .\R.0 ( \dataout_d[0][3] ), 
    .\L.1 ( \datain_d[1][3] ), 
    .\R.1 ( \dataout_d[1][3] ), 
    .\L.e ( \datain_e[3] ), 
    .\R.e ( \dataout_e[3] ));
  \synthesis.qdi.logic3.LOGIC3_69.4 \edu_RTL_BODY.g1365 ( 
    .V ( \pchb_cloud_47_inst_valid_out_0 ), 
    .en ( \pchb_cloud_47_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_11.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_11.1 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_12_SX0_iter2.0 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_12_SX0_iter2.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_16.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_16.1 ), 
    .\X.0 ( \edu_RTL_BODY.n_18.0 ), 
    .\X.1 ( \edu_RTL_BODY.n_18.1 ));
  \synthesis.qdi.logic3.LOGIC3_07.4 \edu_RTL_BODY.g1366 ( 
    .V ( \pchb_cloud_47_inst_valid_out_1 ), 
    .en ( \pchb_cloud_47_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_15_SX0_iter2.1 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_15_SX0_iter2.0 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_13_SX0_iter2.0 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_13_SX0_iter2.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_16.1 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_16.0 ), 
    .\X.0 ( \edu_RTL_BODY.n_17.1 ), 
    .\X.1 ( \edu_RTL_BODY.n_17.0 ));
  \synthesis.qdi.special.CTRL52.2 \pchb_cloud_47_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_47_inst_go ), 
    .Ae ( \c47.e ), 
    .\A[0].0 ( \edu_RTL_BODY.n_11.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_11.1 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_12_SX0_iter2.0 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_12_SX0_iter2.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_13_SX0_iter2.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_13_SX0_iter2.1 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_15_SX0_iter2.0 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_15_SX0_iter2.1 ), 
    .\A[4].0 ( \edu_RTL_BODY.n_16.0 ), 
    .\A[4].1 ( \edu_RTL_BODY.n_16.1 ), 
    .\V[0] ( \pchb_cloud_47_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_47_inst_valid_out_1 ));
  \synthesis.qdi.special.CTREE2.2 \ctreeedu_RTL_BODY.g1365 ( 
    .\a[0] ( \pchb_cloud_47_inst_go ), 
    .\a[1] ( \c59.e ), 
    .x ( \pchb_cloud_47_inst_en0 ));
  \synthesis.qdi.logic3.LOGIC3_69.2 \edu_RTL_BODY.g1368 ( 
    .V ( \pchb_cloud_49_inst_valid_out_1 ), 
    .en ( \pchb_cloud_49_inst_en0 ), 
    .\A[0].0 ( \d[5].0 ), 
    .\A[0].1 ( \d[5].1 ), 
    .\A[1].0 ( \d[9].0 ), 
    .\A[1].1 ( \d[9].1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_10.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_10.1 ), 
    .\X.0 ( \edu_RTL_BODY.n_15.0 ), 
    .\X.1 ( \edu_RTL_BODY.n_15.1 ));
  \synthesis.qdi.logic3.LOGIC3_69.4 \edu_RTL_BODY.g1372 ( 
    .V ( \pchb_cloud_49_inst_valid_out_2 ), 
    .en ( \pchb_cloud_49_inst_en2 ), 
    .\A[0].0 ( \d[4].1 ), 
    .\A[0].1 ( \d[4].0 ), 
    .\A[1].0 ( \d[8].0 ), 
    .\A[1].1 ( \d[8].1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_10.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_10.1 ), 
    .\X.0 ( \edu_RTL_BODY.n_13.0 ), 
    .\X.1 ( \edu_RTL_BODY.n_13.1 ));
  \synthesis.qdi.special.CTREE4.2 \ctreeedu_RTL_BODY.g1372 ( 
    .x ( \pchb_cloud_49_inst_en2 ), 
    .\a[3] ( \pchb_cloud_49_inst_go ), 
    .\a[0] ( \edu_RTL_BODY.n_13_104.e ), 
    .\a[1] ( \c60.e ), 
    .\a[2] ( \edu_RTL_BODY.n_13_62.e ));
  \synthesis.qdi.logic2.LOGIC2_6.2 \edu_RTL_BODY.g1373 ( 
    .V ( \pchb_cloud_49_inst_valid_out_0 ), 
    .en ( \pchb_cloud_49_inst_en0 ), 
    .\A[0].0 ( \d[8].1 ), 
    .\A[0].1 ( \d[8].0 ), 
    .\A[1].0 ( \d[9].0 ), 
    .\A[1].1 ( \d[9].1 ), 
    .\X.0 ( \edu_RTL_BODY.n_12.0 ), 
    .\X.1 ( \edu_RTL_BODY.n_12.1 ));
  \synthesis.qdi.special.CTRL53.2 \pchb_cloud_49_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_49_inst_go ), 
    .Ae ( \c49.e ), 
    .\A[0].0 ( \d[4].0 ), 
    .\A[0].1 ( \d[4].1 ), 
    .\A[1].0 ( \d[5].0 ), 
    .\A[1].1 ( \d[5].1 ), 
    .\A[2].0 ( \d[8].0 ), 
    .\A[2].1 ( \d[8].1 ), 
    .\A[3].0 ( \d[9].0 ), 
    .\A[3].1 ( \d[9].1 ), 
    .\A[4].0 ( \edu_RTL_BODY.n_10.0 ), 
    .\A[4].1 ( \edu_RTL_BODY.n_10.1 ), 
    .\V[0] ( \pchb_cloud_49_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_49_inst_valid_out_1 ), 
    .\V[2] ( \pchb_cloud_49_inst_valid_out_2 ));
  \synthesis.qdi.special.CTREE4.2 \ctreeedu_RTL_BODY.g1373 ( 
    .\a[0] ( \pchb_cloud_49_inst_go ), 
    .\a[1] ( \edu_RTL_BODY.n_12.e ), 
    .\a[2] ( \edu_RTL_BODY.n_15_105.e ), 
    .\a[3] ( \c60.e ), 
    .x ( \pchb_cloud_49_inst_en0 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \edu_RTL_BODY.g1345 ( 
    .V ( \pchb_cloud_51_inst_valid_out_0 ), 
    .en ( \pchb_cloud_51_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_27_SX0_iter2_0.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_27_SX0_iter2_0.1 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_27_SX0_iter2_0.1 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_27_SX0_iter2_0.0 ), 
    .\A[2].0 ( \d[9]_SX2_iter2.1 ), 
    .\A[2].1 ( \d[9]_SX2_iter2.0 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_0.1 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_0.0 ), 
    .\X.0 ( \n_31.0 ), 
    .\X.1 ( \n_31.1 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \edu_RTL_BODY.g1350 ( 
    .V ( \pchb_cloud_51_inst_valid_out_1 ), 
    .en ( \pchb_cloud_51_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_28_SX0_iter2_0.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_28_SX0_iter2_0.1 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_28_SX0_iter2_0.1 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_28_SX0_iter2_0.0 ), 
    .\A[2].0 ( \d[4]_SX2_iter2.1 ), 
    .\A[2].1 ( \d[4]_SX2_iter2.0 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_0.1 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_0.0 ), 
    .\X.0 ( \n_37.0 ), 
    .\X.1 ( \n_37.1 ));
  \synthesis.qdi.special.CTRL52.2 \pchb_cloud_51_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_51_inst_go ), 
    .Ae ( \c51.e ), 
    .\A[0].0 ( \d[4]_SX2_iter2.0 ), 
    .\A[0].1 ( \d[4]_SX2_iter2.1 ), 
    .\A[1].0 ( \d[9]_SX2_iter2.0 ), 
    .\A[1].1 ( \d[9]_SX2_iter2.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_0.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_0.1 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_27_SX0_iter2_0.0 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_27_SX0_iter2_0.1 ), 
    .\A[4].0 ( \edu_RTL_BODY.n_28_SX0_iter2_0.0 ), 
    .\A[4].1 ( \edu_RTL_BODY.n_28_SX0_iter2_0.1 ), 
    .\V[0] ( \pchb_cloud_51_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_51_inst_valid_out_1 ));
  \synthesis.qdi.special.CTREE3.2 \ctreeedu_RTL_BODY.g1345 ( 
    .\a[0] ( \pchb_cloud_51_inst_go ), 
    .\a[1] ( \n_31.e ), 
    .\a[2] ( \n_37.e ), 
    .x ( \pchb_cloud_51_inst_en0 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \edu_RTL_BODY.g1347 ( 
    .V ( \pchb_cloud_53_inst_valid_out_0 ), 
    .en ( \pchb_cloud_53_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_24_SX1_iter2.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_24_SX1_iter2.1 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_24_SX1_iter2.1 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_24_SX1_iter2.0 ), 
    .\A[2].0 ( \d[7]_SX2_iter2.1 ), 
    .\A[2].1 ( \d[7]_SX2_iter2.0 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_0_FX0.1 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_0_FX0.0 ), 
    .\X.0 ( \n_33.0 ), 
    .\X.1 ( \n_33.1 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \edu_RTL_BODY.g1348 ( 
    .V ( \pchb_cloud_53_inst_valid_out_1 ), 
    .en ( \pchb_cloud_53_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_26_SX1_iter2.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_26_SX1_iter2.1 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_26_SX1_iter2.1 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_26_SX1_iter2.0 ), 
    .\A[2].0 ( \d[6]_SX3_iter2.1 ), 
    .\A[2].1 ( \d[6]_SX3_iter2.0 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_0_FX0.1 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_0_FX0.0 ), 
    .\X.0 ( \n_35.0 ), 
    .\X.1 ( \n_35.1 ));
  \synthesis.qdi.special.CTRL52.2 \pchb_cloud_53_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_53_inst_go ), 
    .Ae ( \c53.e ), 
    .\A[0].0 ( \d[6]_SX3_iter2.0 ), 
    .\A[0].1 ( \d[6]_SX3_iter2.1 ), 
    .\A[1].0 ( \d[7]_SX2_iter2.0 ), 
    .\A[1].1 ( \d[7]_SX2_iter2.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_0_FX0.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_0_FX0.1 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_24_SX1_iter2.0 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_24_SX1_iter2.1 ), 
    .\A[4].0 ( \edu_RTL_BODY.n_26_SX1_iter2.0 ), 
    .\A[4].1 ( \edu_RTL_BODY.n_26_SX1_iter2.1 ), 
    .\V[0] ( \pchb_cloud_53_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_53_inst_valid_out_1 ));
  \synthesis.qdi.special.CTREE3.2 \ctreeedu_RTL_BODY.g1347 ( 
    .\a[0] ( \pchb_cloud_53_inst_go ), 
    .\a[1] ( \n_33.e ), 
    .\a[2] ( \n_35.e ), 
    .x ( \pchb_cloud_53_inst_en0 ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \edu_RTL_BODY.g1355 ( 
    .V ( \pchb_cloud_54_inst_valid_out_1 ), 
    .en ( \pchb_cloud_54_inst_en1 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2.1 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2.0 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_20.0 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_20.1 ), 
    .\X.0 ( \edu_RTL_BODY.n_28.1 ), 
    .\X.1 ( \edu_RTL_BODY.n_28.0 ));
  \synthesis.qdi.special.CTREE3.2 \ctreeedu_RTL_BODY.g1355 ( 
    .x ( \pchb_cloud_54_inst_en1 ), 
    .\a[2] ( \pchb_cloud_54_inst_go ), 
    .\a[0] ( \edu_RTL_BODY.n_28_107.e ), 
    .\a[1] ( \edu_RTL_BODY.n_28_110.e ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \edu_RTL_BODY.g1356 ( 
    .V ( \pchb_cloud_54_inst_valid_out_2 ), 
    .en ( \pchb_cloud_54_inst_en2 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_19.1 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_19.0 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2.0 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2.1 ), 
    .\X.0 ( \edu_RTL_BODY.n_27.1 ), 
    .\X.1 ( \edu_RTL_BODY.n_27.0 ));
  \synthesis.qdi.special.CTREE3.2 \ctreeedu_RTL_BODY.g1356 ( 
    .x ( \pchb_cloud_54_inst_en2 ), 
    .\a[2] ( \pchb_cloud_54_inst_go ), 
    .\a[0] ( \edu_RTL_BODY.n_27_108.e ), 
    .\a[1] ( \edu_RTL_BODY.n_27_109.e ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \edu_RTL_BODY.g1358 ( 
    .V ( \pchb_cloud_54_inst_valid_out_0 ), 
    .en ( \pchb_cloud_54_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_20.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_20.1 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2.0 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2.1 ), 
    .\X.0 ( \edu_RTL_BODY.n_25.1 ), 
    .\X.1 ( \edu_RTL_BODY.n_25.0 ));
  \synthesis.qdi.special.CTREE3.2 \ctreeedu_RTL_BODY.g1358 ( 
    .x ( \pchb_cloud_54_inst_en0 ), 
    .\a[2] ( \pchb_cloud_54_inst_go ), 
    .\a[0] ( \edu_RTL_BODY.n_25_106.e ), 
    .\a[1] ( \c15.e ));
  \synthesis.qdi.special.CTRL33.2 \pchb_cloud_54_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_54_inst_go ), 
    .Ae ( \c54.e ), 
    .\A[0].0 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2.1 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_19.0 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_19.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_20.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_20.1 ), 
    .\V[0] ( \pchb_cloud_54_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_54_inst_valid_out_1 ), 
    .\V[2] ( \pchb_cloud_54_inst_valid_out_2 ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \edu_RTL_BODY.g1357 ( 
    .V ( \pchb_cloud_55_inst_valid_out_1 ), 
    .en ( \pchb_cloud_55_inst_en1 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2_0.1 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2_0.0 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_21.0 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_21.1 ), 
    .\X.0 ( \edu_RTL_BODY.n_26.1 ), 
    .\X.1 ( \edu_RTL_BODY.n_26.0 ));
  \synthesis.qdi.special.CTREE3.2 \ctreeedu_RTL_BODY.g1357 ( 
    .x ( \pchb_cloud_55_inst_en1 ), 
    .\a[2] ( \pchb_cloud_55_inst_go ), 
    .\a[0] ( \edu_RTL_BODY.n_26_111.e ), 
    .\a[1] ( \edu_RTL_BODY.n_26_114.e ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \edu_RTL_BODY.g1359 ( 
    .V ( \pchb_cloud_55_inst_valid_out_2 ), 
    .en ( \pchb_cloud_55_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_21.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_21.1 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2_0.0 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2_0.1 ), 
    .\X.0 ( \edu_RTL_BODY.n_24.1 ), 
    .\X.1 ( \edu_RTL_BODY.n_24.0 ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \edu_RTL_BODY.g1360 ( 
    .V ( \pchb_cloud_55_inst_valid_out_0 ), 
    .en ( \pchb_cloud_55_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_19.1 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_19.0 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2_0.1 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2_0.0 ), 
    .\X.0 ( \edu_RTL_BODY.n_23.1 ), 
    .\X.1 ( \edu_RTL_BODY.n_23.0 ));
  \synthesis.qdi.special.CTRL33.2 \pchb_cloud_55_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_55_inst_go ), 
    .Ae ( \c55.e ), 
    .\A[0].0 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2_0.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2_0.1 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_19.0 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_19.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_21.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_21.1 ), 
    .\V[0] ( \pchb_cloud_55_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_55_inst_valid_out_1 ), 
    .\V[2] ( \pchb_cloud_55_inst_valid_out_2 ));
  \synthesis.qdi.special.CTREE4.2 \ctreeedu_RTL_BODY.g1360 ( 
    .\a[0] ( \pchb_cloud_55_inst_go ), 
    .\a[1] ( \edu_RTL_BODY.n_23_116.e ), 
    .\a[2] ( \c16.e ), 
    .\a[3] ( \edu_RTL_BODY.n_24_112.e ), 
    .x ( \pchb_cloud_55_inst_en0 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \edu_RTL_BODY.g1344 ( 
    .V ( \pchb_cloud_58_inst_valid_out_0 ), 
    .en ( \pchb_cloud_58_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_22_SX1_iter2.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_22_SX1_iter2.1 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_22_SX1_iter2.1 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_22_SX1_iter2.0 ), 
    .\A[2].0 ( \d[10]_SX3_iter2.1 ), 
    .\A[2].1 ( \d[10]_SX3_iter2.0 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_0_FX0.1 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_0_FX0.0 ), 
    .\X.0 ( \n_30.0 ), 
    .\X.1 ( \n_30.1 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \edu_RTL_BODY.g1346 ( 
    .V ( \pchb_cloud_58_inst_valid_out_1 ), 
    .en ( \pchb_cloud_58_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_23_SX1_iter2.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_23_SX1_iter2.1 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_23_SX1_iter2.1 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_23_SX1_iter2.0 ), 
    .\A[2].0 ( \d[8]_SX2_iter2.1 ), 
    .\A[2].1 ( \d[8]_SX2_iter2.0 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_0_FX0.1 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_0_FX0.0 ), 
    .\X.0 ( \n_32.0 ), 
    .\X.1 ( \n_32.1 ));
  \synthesis.qdi.special.CTRL52.2 \pchb_cloud_58_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_58_inst_go ), 
    .Ae ( \c58.e ), 
    .\A[0].0 ( \d[10]_SX3_iter2.0 ), 
    .\A[0].1 ( \d[10]_SX3_iter2.1 ), 
    .\A[1].0 ( \d[8]_SX2_iter2.0 ), 
    .\A[1].1 ( \d[8]_SX2_iter2.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_0_FX0.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_0_FX0.1 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_22_SX1_iter2.0 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_22_SX1_iter2.1 ), 
    .\A[4].0 ( \edu_RTL_BODY.n_23_SX1_iter2.0 ), 
    .\A[4].1 ( \edu_RTL_BODY.n_23_SX1_iter2.1 ), 
    .\V[0] ( \pchb_cloud_58_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_58_inst_valid_out_1 ));
  \synthesis.qdi.special.CTREE3.2 \ctreeedu_RTL_BODY.g1344 ( 
    .\a[0] ( \pchb_cloud_58_inst_go ), 
    .\a[1] ( \n_30.e ), 
    .\a[2] ( \n_32.e ), 
    .x ( \pchb_cloud_58_inst_en0 ));
  \synthesis.qdi.logic3.LOGIC3_01.2 \edu_RTL_BODY.g1361 ( 
    .V ( \pchb_cloud_59_inst_valid_out_0 ), 
    .en ( \pchb_cloud_59_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_13_FX0.1 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_13_FX0.0 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_17.1 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_17.0 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_18.1 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_18.0 ), 
    .\X.0 ( \edu_RTL_BODY.n_22.1 ), 
    .\X.1 ( \edu_RTL_BODY.n_22.0 ));
  \synthesis.qdi.special.CTREE3.2 \ctreeedu_RTL_BODY.g1361 ( 
    .x ( \pchb_cloud_59_inst_en0 ), 
    .\a[2] ( \pchb_cloud_59_inst_go ), 
    .\a[0] ( \edu_RTL_BODY.n_22_118.e ), 
    .\a[1] ( \edu_RTL_BODY.n_22_119.e ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \edu_RTL_BODY.g1362 ( 
    .V ( \pchb_cloud_59_inst_valid_out_2 ), 
    .en ( \pchb_cloud_59_inst_en2 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_17.1 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_17.0 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_18.0 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_18.1 ), 
    .\X.0 ( \edu_RTL_BODY.n_21.1 ), 
    .\X.1 ( \edu_RTL_BODY.n_21.0 ));
  \synthesis.qdi.special.CTREE2.2 \ctreeedu_RTL_BODY.g1362 ( 
    .x ( \pchb_cloud_59_inst_en2 ), 
    .\a[0] ( \pchb_cloud_59_inst_go ), 
    .\a[1] ( \c55.e ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \edu_RTL_BODY.g1363 ( 
    .V ( \pchb_cloud_59_inst_valid_out_1 ), 
    .en ( \pchb_cloud_59_inst_en1 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_18.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_18.1 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_17.0 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_17.1 ), 
    .\X.0 ( \edu_RTL_BODY.n_20.1 ), 
    .\X.1 ( \edu_RTL_BODY.n_20.0 ));
  \synthesis.qdi.special.CTREE2.2 \ctreeedu_RTL_BODY.g1363 ( 
    .x ( \pchb_cloud_59_inst_en1 ), 
    .\a[0] ( \pchb_cloud_59_inst_go ), 
    .\a[1] ( \c54.e ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \edu_RTL_BODY.g1364 ( 
    .V ( \pchb_cloud_59_inst_valid_out_3 ), 
    .en ( \pchb_cloud_59_inst_en3 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_18.1 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_18.0 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_17.0 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_17.1 ), 
    .\X.0 ( \edu_RTL_BODY.n_19.0 ), 
    .\X.1 ( \edu_RTL_BODY.n_19.1 ));
  \synthesis.qdi.special.CTREE3.2 \ctreeedu_RTL_BODY.g1364 ( 
    .x ( \pchb_cloud_59_inst_en3 ), 
    .\a[2] ( \pchb_cloud_59_inst_go ), 
    .\a[0] ( \c54.e ), 
    .\a[1] ( \c55.e ));
  \synthesis.qdi.special.CTRL34.2 \pchb_cloud_59_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_59_inst_go ), 
    .Ae ( \c59.e ), 
    .\A[0].0 ( \edu_RTL_BODY.n_13_FX0.0 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_13_FX0.1 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_17.0 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_17.1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_18.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_18.1 ), 
    .\V[0] ( \pchb_cloud_59_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_59_inst_valid_out_1 ), 
    .\V[2] ( \pchb_cloud_59_inst_valid_out_2 ), 
    .\V[3] ( \pchb_cloud_59_inst_valid_out_3 ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \edu_RTL_BODY.g1367 ( 
    .V ( \pchb_cloud_60_inst_valid_out_0 ), 
    .en ( \pchb_cloud_60_inst_en0 ), 
    .\A[0].0 ( \edu_RTL_BODY.n_15.1 ), 
    .\A[0].1 ( \edu_RTL_BODY.n_15.0 ), 
    .\A[1].0 ( \edu_RTL_BODY.n_13.0 ), 
    .\A[1].1 ( \edu_RTL_BODY.n_13.1 ), 
    .\X.0 ( \edu_RTL_BODY.n_16.1 ), 
    .\X.1 ( \edu_RTL_BODY.n_16.0 ));
  \synthesis.qdi.logic2.LOGIC2_6.2 \edu_RTL_BODY.g1374 ( 
    .V ( \pchb_cloud_60_inst_valid_out_1 ), 
    .en ( \pchb_cloud_60_inst_en0 ), 
    .\A[0].0 ( \d[10]_SX0_iter2_1.1 ), 
    .\A[0].1 ( \d[10]_SX0_iter2_1.0 ), 
    .\A[1].0 ( \d[7].0 ), 
    .\A[1].1 ( \d[7].1 ), 
    .\X.0 ( \edu_RTL_BODY.n_11.0 ), 
    .\X.1 ( \edu_RTL_BODY.n_11.1 ));
  \synthesis.qdi.special.CTRL42.2 \pchb_cloud_60_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_60_inst_go ), 
    .Ae ( \c60.e ), 
    .\A[0].0 ( \d[10]_SX0_iter2_1.0 ), 
    .\A[0].1 ( \d[10]_SX0_iter2_1.1 ), 
    .\A[1].0 ( \d[7].0 ), 
    .\A[1].1 ( \d[7].1 ), 
    .\A[2].0 ( \edu_RTL_BODY.n_13.0 ), 
    .\A[2].1 ( \edu_RTL_BODY.n_13.1 ), 
    .\A[3].0 ( \edu_RTL_BODY.n_15.0 ), 
    .\A[3].1 ( \edu_RTL_BODY.n_15.1 ), 
    .\V[0] ( \pchb_cloud_60_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_60_inst_valid_out_1 ));
  \synthesis.qdi.special.CTREE2.2 \ctreeedu_RTL_BODY.g1367 ( 
    .\a[0] ( \pchb_cloud_60_inst_go ), 
    .\a[1] ( \c47.e ), 
    .x ( \pchb_cloud_60_inst_en0 ));
  \synthesis.qdi.special.BUF.4 \pchb_cfbuf_61_FX_inst_edu_RTL_BODY.n_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_0.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_0.1 ), 
    .\L.e ( \edu_RTL_BODY.n_0_61.e ), 
    .\R.0 ( \edu_RTL_BODY.n_0_FX0.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_0_FX0.1 ), 
    .\R.e ( \pchb_cfbuf_61_FX_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cfbuf_61_FX_inst_edu_RTL_BODY.n_0_buf_companion0 ( 
    .x ( \pchb_cfbuf_61_FX_inst_en0 ), 
    .\a[0] ( \c58.e ), 
    .\a[1] ( \c53.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cfbuf_62_FX_inst_edu_RTL_BODY.n_13_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_13.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_13.1 ), 
    .\L.e ( \edu_RTL_BODY.n_13_62.e ), 
    .\R.0 ( \edu_RTL_BODY.n_13_FX0.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_13_FX0.1 ), 
    .\R.e ( \pchb_cfbuf_62_FX_inst_en0 ));
  \synthesis.qdi.special.CTREE3.2 \pchb_cfbuf_62_FX_inst_edu_RTL_BODY.n_13_buf_companion0 ( 
    .x ( \pchb_cfbuf_62_FX_inst_en0 ), 
    .\a[0] ( \edu_RTL_BODY.n_13_FX0_122.e ), 
    .\a[1] ( \edu_RTL_BODY.n_13_FX0_121.e ), 
    .\a[2] ( \c59.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_63_SX_inst_edu_RTL_BODY.n_30_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_30.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_30.1 ), 
    .\L.e ( \edu_RTL_BODY.n_30.e ), 
    .\R.0 ( \edu_RTL_BODY.n_30_SX0_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_30_SX0_iter2.1 ), 
    .\R.e ( \c35.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_64_SX_inst_d[10]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[10].0 ), 
    .\L.1 ( \d[10].1 ), 
    .\L.e ( \d[10]_64.e ), 
    .\R.0 ( \d[10]_SX0_iter2.0 ), 
    .\R.1 ( \d[10]_SX0_iter2.1 ), 
    .\R.e ( \d[10]_SX0_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_65_SX_inst_d[10]_SX0_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[10]_SX0_iter2.0 ), 
    .\L.1 ( \d[10]_SX0_iter2.1 ), 
    .\L.e ( \d[10]_SX0_iter2.e ), 
    .\R.0 ( \d[10]_SX1_iter2.0 ), 
    .\R.1 ( \d[10]_SX1_iter2.1 ), 
    .\R.e ( \c15.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_66_SX_inst_d[10]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[10].0 ), 
    .\L.1 ( \d[10].1 ), 
    .\L.e ( \d[10]_66.e ), 
    .\R.0 ( \d[10]_SX0_iter2_0.0 ), 
    .\R.1 ( \d[10]_SX0_iter2_0.1 ), 
    .\R.e ( \d[10]_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_67_SX_inst_d[10]_SX0_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[10]_SX0_iter2_0.0 ), 
    .\L.1 ( \d[10]_SX0_iter2_0.1 ), 
    .\L.e ( \d[10]_SX0_iter2_0.e ), 
    .\R.0 ( \d[10]_SX1_iter2_0.0 ), 
    .\R.1 ( \d[10]_SX1_iter2_0.1 ), 
    .\R.e ( \d[10]_SX1_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_68_SX_inst_d[10]_SX1_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[10]_SX1_iter2_0.0 ), 
    .\L.1 ( \d[10]_SX1_iter2_0.1 ), 
    .\L.e ( \d[10]_SX1_iter2_0.e ), 
    .\R.0 ( \d[10]_SX2_iter2.0 ), 
    .\R.1 ( \d[10]_SX2_iter2.1 ), 
    .\R.e ( \d[10]_SX2_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_69_SX_inst_d[10]_SX2_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[10]_SX2_iter2.0 ), 
    .\L.1 ( \d[10]_SX2_iter2.1 ), 
    .\L.e ( \d[10]_SX2_iter2.e ), 
    .\R.0 ( \d[10]_SX3_iter2.0 ), 
    .\R.1 ( \d[10]_SX3_iter2.1 ), 
    .\R.e ( \c58.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_70_SX_inst_d[10]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[10].0 ), 
    .\L.1 ( \d[10].1 ), 
    .\L.e ( \d[10]_70.e ), 
    .\R.0 ( \d[10]_SX0_iter2_1.0 ), 
    .\R.1 ( \d[10]_SX0_iter2_1.1 ), 
    .\R.e ( \c60.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_71_SX_inst_d[4]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[4].0 ), 
    .\L.1 ( \d[4].1 ), 
    .\L.e ( \d[4]_71.e ), 
    .\R.0 ( \d[4]_SX0_iter2.0 ), 
    .\R.1 ( \d[4]_SX0_iter2.1 ), 
    .\R.e ( \d[4]_SX0_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_72_SX_inst_d[4]_SX0_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[4]_SX0_iter2.0 ), 
    .\L.1 ( \d[4]_SX0_iter2.1 ), 
    .\L.e ( \d[4]_SX0_iter2.e ), 
    .\R.0 ( \d[4]_SX1_iter2.0 ), 
    .\R.1 ( \d[4]_SX1_iter2.1 ), 
    .\R.e ( \c14.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_73_SX_inst_d[4]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[4].0 ), 
    .\L.1 ( \d[4].1 ), 
    .\L.e ( \d[4]_73.e ), 
    .\R.0 ( \d[4]_SX0_iter2_0.0 ), 
    .\R.1 ( \d[4]_SX0_iter2_0.1 ), 
    .\R.e ( \d[4]_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_74_SX_inst_d[4]_SX0_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[4]_SX0_iter2_0.0 ), 
    .\L.1 ( \d[4]_SX0_iter2_0.1 ), 
    .\L.e ( \d[4]_SX0_iter2_0.e ), 
    .\R.0 ( \d[4]_SX1_iter2_0.0 ), 
    .\R.1 ( \d[4]_SX1_iter2_0.1 ), 
    .\R.e ( \d[4]_SX1_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_75_SX_inst_d[4]_SX1_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[4]_SX1_iter2_0.0 ), 
    .\L.1 ( \d[4]_SX1_iter2_0.1 ), 
    .\L.e ( \d[4]_SX1_iter2_0.e ), 
    .\R.0 ( \d[4]_SX2_iter2.0 ), 
    .\R.1 ( \d[4]_SX2_iter2.1 ), 
    .\R.e ( \c51.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_76_SX_inst_d[5]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[5].0 ), 
    .\L.1 ( \d[5].1 ), 
    .\L.e ( \d[5]_76.e ), 
    .\R.0 ( \d[5]_SX0_iter2.0 ), 
    .\R.1 ( \d[5]_SX0_iter2.1 ), 
    .\R.e ( \d[5]_SX0_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_77_SX_inst_d[5]_SX0_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[5]_SX0_iter2.0 ), 
    .\L.1 ( \d[5]_SX0_iter2.1 ), 
    .\L.e ( \d[5]_SX0_iter2.e ), 
    .\R.0 ( \d[5]_SX1_iter2.0 ), 
    .\R.1 ( \d[5]_SX1_iter2.1 ), 
    .\R.e ( \d[5]_SX1_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_78_SX_inst_d[5]_SX1_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[5]_SX1_iter2.0 ), 
    .\L.1 ( \d[5]_SX1_iter2.1 ), 
    .\L.e ( \d[5]_SX1_iter2.e ), 
    .\R.0 ( \d[5]_SX2_iter2.0 ), 
    .\R.1 ( \d[5]_SX2_iter2.1 ), 
    .\R.e ( \c12.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_79_SX_inst_d[5]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[5].0 ), 
    .\L.1 ( \d[5].1 ), 
    .\L.e ( \d[5]_79.e ), 
    .\R.0 ( \d[5]_SX0_iter2_0.0 ), 
    .\R.1 ( \d[5]_SX0_iter2_0.1 ), 
    .\R.e ( \d[5]_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_80_SX_inst_d[5]_SX0_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[5]_SX0_iter2_0.0 ), 
    .\L.1 ( \d[5]_SX0_iter2_0.1 ), 
    .\L.e ( \d[5]_SX0_iter2_0.e ), 
    .\R.0 ( \d[5]_SX1_iter2_0.0 ), 
    .\R.1 ( \d[5]_SX1_iter2_0.1 ), 
    .\R.e ( \c15.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_81_SX_inst_d[6]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[6].0 ), 
    .\L.1 ( \d[6].1 ), 
    .\L.e ( \d[6]_81.e ), 
    .\R.0 ( \d[6]_SX0_iter2.0 ), 
    .\R.1 ( \d[6]_SX0_iter2.1 ), 
    .\R.e ( \d[6]_SX0_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_82_SX_inst_d[6]_SX0_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[6]_SX0_iter2.0 ), 
    .\L.1 ( \d[6]_SX0_iter2.1 ), 
    .\L.e ( \d[6]_SX0_iter2.e ), 
    .\R.0 ( \d[6]_SX1_iter2.0 ), 
    .\R.1 ( \d[6]_SX1_iter2.1 ), 
    .\R.e ( \d[6]_SX1_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_83_SX_inst_d[6]_SX1_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[6]_SX1_iter2.0 ), 
    .\L.1 ( \d[6]_SX1_iter2.1 ), 
    .\L.e ( \d[6]_SX1_iter2.e ), 
    .\R.0 ( \d[6]_SX2_iter2.0 ), 
    .\R.1 ( \d[6]_SX2_iter2.1 ), 
    .\R.e ( \c35.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_84_SX_inst_d[6]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[6].0 ), 
    .\L.1 ( \d[6].1 ), 
    .\L.e ( \d[6]_84.e ), 
    .\R.0 ( \d[6]_SX0_iter2_0.0 ), 
    .\R.1 ( \d[6]_SX0_iter2_0.1 ), 
    .\R.e ( \d[6]_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_85_SX_inst_d[6]_SX0_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[6]_SX0_iter2_0.0 ), 
    .\L.1 ( \d[6]_SX0_iter2_0.1 ), 
    .\L.e ( \d[6]_SX0_iter2_0.e ), 
    .\R.0 ( \d[6]_SX1_iter2_0.0 ), 
    .\R.1 ( \d[6]_SX1_iter2_0.1 ), 
    .\R.e ( \d[6]_SX1_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_86_SX_inst_d[6]_SX1_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[6]_SX1_iter2_0.0 ), 
    .\L.1 ( \d[6]_SX1_iter2_0.1 ), 
    .\L.e ( \d[6]_SX1_iter2_0.e ), 
    .\R.0 ( \d[6]_SX2_iter2_0.0 ), 
    .\R.1 ( \d[6]_SX2_iter2_0.1 ), 
    .\R.e ( \d[6]_SX2_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_87_SX_inst_d[6]_SX2_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[6]_SX2_iter2_0.0 ), 
    .\L.1 ( \d[6]_SX2_iter2_0.1 ), 
    .\L.e ( \d[6]_SX2_iter2_0.e ), 
    .\R.0 ( \d[6]_SX3_iter2.0 ), 
    .\R.1 ( \d[6]_SX3_iter2.1 ), 
    .\R.e ( \c53.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_88_SX_inst_d[7]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[7].0 ), 
    .\L.1 ( \d[7].1 ), 
    .\L.e ( \d[7]_88.e ), 
    .\R.0 ( \d[7]_SX0_iter2.0 ), 
    .\R.1 ( \d[7]_SX0_iter2.1 ), 
    .\R.e ( \d[7]_SX0_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_89_SX_inst_d[7]_SX0_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[7]_SX0_iter2.0 ), 
    .\L.1 ( \d[7]_SX0_iter2.1 ), 
    .\L.e ( \d[7]_SX0_iter2.e ), 
    .\R.0 ( \d[7]_SX1_iter2.0 ), 
    .\R.1 ( \d[7]_SX1_iter2.1 ), 
    .\R.e ( \c16.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_90_SX_inst_d[7]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[7].0 ), 
    .\L.1 ( \d[7].1 ), 
    .\L.e ( \d[7]_90.e ), 
    .\R.0 ( \d[7]_SX0_iter2_0.0 ), 
    .\R.1 ( \d[7]_SX0_iter2_0.1 ), 
    .\R.e ( \d[7]_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_91_SX_inst_d[7]_SX0_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[7]_SX0_iter2_0.0 ), 
    .\L.1 ( \d[7]_SX0_iter2_0.1 ), 
    .\L.e ( \d[7]_SX0_iter2_0.e ), 
    .\R.0 ( \d[7]_SX1_iter2_0.0 ), 
    .\R.1 ( \d[7]_SX1_iter2_0.1 ), 
    .\R.e ( \d[7]_SX1_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_92_SX_inst_d[7]_SX1_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[7]_SX1_iter2_0.0 ), 
    .\L.1 ( \d[7]_SX1_iter2_0.1 ), 
    .\L.e ( \d[7]_SX1_iter2_0.e ), 
    .\R.0 ( \d[7]_SX2_iter2.0 ), 
    .\R.1 ( \d[7]_SX2_iter2.1 ), 
    .\R.e ( \c53.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_93_SX_inst_d[8]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[8].0 ), 
    .\L.1 ( \d[8].1 ), 
    .\L.e ( \d[8]_93.e ), 
    .\R.0 ( \d[8]_SX0_iter2.0 ), 
    .\R.1 ( \d[8]_SX0_iter2.1 ), 
    .\R.e ( \d[8]_SX0_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_94_SX_inst_d[8]_SX0_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[8]_SX0_iter2.0 ), 
    .\L.1 ( \d[8]_SX0_iter2.1 ), 
    .\L.e ( \d[8]_SX0_iter2.e ), 
    .\R.0 ( \d[8]_SX1_iter2.0 ), 
    .\R.1 ( \d[8]_SX1_iter2.1 ), 
    .\R.e ( \c16.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_95_SX_inst_d[8]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[8].0 ), 
    .\L.1 ( \d[8].1 ), 
    .\L.e ( \d[8]_95.e ), 
    .\R.0 ( \d[8]_SX0_iter2_0.0 ), 
    .\R.1 ( \d[8]_SX0_iter2_0.1 ), 
    .\R.e ( \d[8]_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_96_SX_inst_d[8]_SX0_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[8]_SX0_iter2_0.0 ), 
    .\L.1 ( \d[8]_SX0_iter2_0.1 ), 
    .\L.e ( \d[8]_SX0_iter2_0.e ), 
    .\R.0 ( \d[8]_SX1_iter2_0.0 ), 
    .\R.1 ( \d[8]_SX1_iter2_0.1 ), 
    .\R.e ( \d[8]_SX1_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_97_SX_inst_d[8]_SX1_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[8]_SX1_iter2_0.0 ), 
    .\L.1 ( \d[8]_SX1_iter2_0.1 ), 
    .\L.e ( \d[8]_SX1_iter2_0.e ), 
    .\R.0 ( \d[8]_SX2_iter2.0 ), 
    .\R.1 ( \d[8]_SX2_iter2.1 ), 
    .\R.e ( \c58.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_98_SX_inst_d[9]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[9].0 ), 
    .\L.1 ( \d[9].1 ), 
    .\L.e ( \d[9]_98.e ), 
    .\R.0 ( \d[9]_SX0_iter2.0 ), 
    .\R.1 ( \d[9]_SX0_iter2.1 ), 
    .\R.e ( \d[9]_SX0_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_99_SX_inst_d[9]_SX0_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[9]_SX0_iter2.0 ), 
    .\L.1 ( \d[9]_SX0_iter2.1 ), 
    .\L.e ( \d[9]_SX0_iter2.e ), 
    .\R.0 ( \d[9]_SX1_iter2.0 ), 
    .\R.1 ( \d[9]_SX1_iter2.1 ), 
    .\R.e ( \c14.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_100_SX_inst_d[9]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[9].0 ), 
    .\L.1 ( \d[9].1 ), 
    .\L.e ( \d[9]_100.e ), 
    .\R.0 ( \d[9]_SX0_iter2_0.0 ), 
    .\R.1 ( \d[9]_SX0_iter2_0.1 ), 
    .\R.e ( \d[9]_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_101_SX_inst_d[9]_SX0_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[9]_SX0_iter2_0.0 ), 
    .\L.1 ( \d[9]_SX0_iter2_0.1 ), 
    .\L.e ( \d[9]_SX0_iter2_0.e ), 
    .\R.0 ( \d[9]_SX1_iter2_0.0 ), 
    .\R.1 ( \d[9]_SX1_iter2_0.1 ), 
    .\R.e ( \d[9]_SX1_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_102_SX_inst_d[9]_SX1_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[9]_SX1_iter2_0.0 ), 
    .\L.1 ( \d[9]_SX1_iter2_0.1 ), 
    .\L.e ( \d[9]_SX1_iter2_0.e ), 
    .\R.0 ( \d[9]_SX2_iter2.0 ), 
    .\R.1 ( \d[9]_SX2_iter2.1 ), 
    .\R.e ( \c51.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_103_SX_inst_edu_RTL_BODY.n_12_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_12.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_12.1 ), 
    .\L.e ( \edu_RTL_BODY.n_12.e ), 
    .\R.0 ( \edu_RTL_BODY.n_12_SX0_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_12_SX0_iter2.1 ), 
    .\R.e ( \c47.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_104_SX_inst_edu_RTL_BODY.n_13_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_13.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_13.1 ), 
    .\L.e ( \edu_RTL_BODY.n_13_104.e ), 
    .\R.0 ( \edu_RTL_BODY.n_13_SX0_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_13_SX0_iter2.1 ), 
    .\R.e ( \c47.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_105_SX_inst_edu_RTL_BODY.n_15_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_15.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_15.1 ), 
    .\L.e ( \edu_RTL_BODY.n_15_105.e ), 
    .\R.0 ( \edu_RTL_BODY.n_15_SX0_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_15_SX0_iter2.1 ), 
    .\R.e ( \c47.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_106_SX_inst_edu_RTL_BODY.n_25_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_25.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_25.1 ), 
    .\L.e ( \edu_RTL_BODY.n_25_106.e ), 
    .\R.0 ( \edu_RTL_BODY.n_25_SX0_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_25_SX0_iter2.1 ), 
    .\R.e ( \c12.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_107_SX_inst_edu_RTL_BODY.n_28_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_28.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_28.1 ), 
    .\L.e ( \edu_RTL_BODY.n_28_107.e ), 
    .\R.0 ( \edu_RTL_BODY.n_28_SX0_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_28_SX0_iter2.1 ), 
    .\R.e ( \c14.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_108_SX_inst_edu_RTL_BODY.n_27_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_27.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_27.1 ), 
    .\L.e ( \edu_RTL_BODY.n_27_108.e ), 
    .\R.0 ( \edu_RTL_BODY.n_27_SX0_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_27_SX0_iter2.1 ), 
    .\R.e ( \c14.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_109_SX_inst_edu_RTL_BODY.n_27_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_27.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_27.1 ), 
    .\L.e ( \edu_RTL_BODY.n_27_109.e ), 
    .\R.0 ( \edu_RTL_BODY.n_27_SX0_iter2_0.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_27_SX0_iter2_0.1 ), 
    .\R.e ( \c51.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_110_SX_inst_edu_RTL_BODY.n_28_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_28.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_28.1 ), 
    .\L.e ( \edu_RTL_BODY.n_28_110.e ), 
    .\R.0 ( \edu_RTL_BODY.n_28_SX0_iter2_0.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_28_SX0_iter2_0.1 ), 
    .\R.e ( \c51.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_111_SX_inst_edu_RTL_BODY.n_26_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_26.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_26.1 ), 
    .\L.e ( \edu_RTL_BODY.n_26_111.e ), 
    .\R.0 ( \edu_RTL_BODY.n_26_SX0_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_26_SX0_iter2.1 ), 
    .\R.e ( \c35.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_112_SX_inst_edu_RTL_BODY.n_24_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_24.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_24.1 ), 
    .\L.e ( \edu_RTL_BODY.n_24_112.e ), 
    .\R.0 ( \edu_RTL_BODY.n_24_SX0_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_24_SX0_iter2.1 ), 
    .\R.e ( \edu_RTL_BODY.n_24_SX0_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_113_SX_inst_edu_RTL_BODY.n_24_SX0_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_24_SX0_iter2.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_24_SX0_iter2.1 ), 
    .\L.e ( \edu_RTL_BODY.n_24_SX0_iter2.e ), 
    .\R.0 ( \edu_RTL_BODY.n_24_SX1_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_24_SX1_iter2.1 ), 
    .\R.e ( \c53.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_114_SX_inst_edu_RTL_BODY.n_26_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_26.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_26.1 ), 
    .\L.e ( \edu_RTL_BODY.n_26_114.e ), 
    .\R.0 ( \edu_RTL_BODY.n_26_SX0_iter2_0.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_26_SX0_iter2_0.1 ), 
    .\R.e ( \edu_RTL_BODY.n_26_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_115_SX_inst_edu_RTL_BODY.n_26_SX0_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_26_SX0_iter2_0.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_26_SX0_iter2_0.1 ), 
    .\L.e ( \edu_RTL_BODY.n_26_SX0_iter2_0.e ), 
    .\R.0 ( \edu_RTL_BODY.n_26_SX1_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_26_SX1_iter2.1 ), 
    .\R.e ( \c53.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_116_SX_inst_edu_RTL_BODY.n_23_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_23.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_23.1 ), 
    .\L.e ( \edu_RTL_BODY.n_23_116.e ), 
    .\R.0 ( \edu_RTL_BODY.n_23_SX0_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_23_SX0_iter2.1 ), 
    .\R.e ( \edu_RTL_BODY.n_23_SX0_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_117_SX_inst_edu_RTL_BODY.n_23_SX0_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_23_SX0_iter2.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_23_SX0_iter2.1 ), 
    .\L.e ( \edu_RTL_BODY.n_23_SX0_iter2.e ), 
    .\R.0 ( \edu_RTL_BODY.n_23_SX1_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_23_SX1_iter2.1 ), 
    .\R.e ( \c58.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_118_SX_inst_edu_RTL_BODY.n_22_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_22.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_22.1 ), 
    .\L.e ( \edu_RTL_BODY.n_22_118.e ), 
    .\R.0 ( \edu_RTL_BODY.n_22_SX0_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_22_SX0_iter2.1 ), 
    .\R.e ( \c15.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_119_SX_inst_edu_RTL_BODY.n_22_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_22.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_22.1 ), 
    .\L.e ( \edu_RTL_BODY.n_22_119.e ), 
    .\R.0 ( \edu_RTL_BODY.n_22_SX0_iter2_0.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_22_SX0_iter2_0.1 ), 
    .\R.e ( \edu_RTL_BODY.n_22_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_120_SX_inst_edu_RTL_BODY.n_22_SX0_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_22_SX0_iter2_0.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_22_SX0_iter2_0.1 ), 
    .\L.e ( \edu_RTL_BODY.n_22_SX0_iter2_0.e ), 
    .\R.0 ( \edu_RTL_BODY.n_22_SX1_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_22_SX1_iter2.1 ), 
    .\R.e ( \c58.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_121_SX_inst_edu_RTL_BODY.n_13_FX0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_13_FX0.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_13_FX0.1 ), 
    .\L.e ( \edu_RTL_BODY.n_13_FX0_121.e ), 
    .\R.0 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2.1 ), 
    .\R.e ( \c54.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_122_SX_inst_edu_RTL_BODY.n_13_FX0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \edu_RTL_BODY.n_13_FX0.0 ), 
    .\L.1 ( \edu_RTL_BODY.n_13_FX0.1 ), 
    .\L.e ( \edu_RTL_BODY.n_13_FX0_122.e ), 
    .\R.0 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2_0.0 ), 
    .\R.1 ( \edu_RTL_BODY.n_13_FX0_SX0_iter2_0.1 ), 
    .\R.e ( \c55.e ));

endmodule
