

// Generated by cosim_wrapper.pl to be used for cosim

module core_db_cosim_wrapper(interface db8b, interface datain11b, input _RESET);

 core_db core_db_expanded (datain11b.d[0][0] , datain11b.d[0][10] , datain11b.d[0][1] , datain11b.d[0][2] , datain11b.d[0][3] , datain11b.d[0][4] 
 , datain11b.d[0][5] , datain11b.d[0][6] , datain11b.d[0][7] , datain11b.d[0][8] , datain11b.d[0][9] , datain11b.d[1][0] 
 , datain11b.d[1][10] , datain11b.d[1][1] , datain11b.d[1][2] , datain11b.d[1][3] , datain11b.d[1][4] , datain11b.d[1][5] 
 , datain11b.d[1][6] , datain11b.d[1][7] , datain11b.d[1][8] , datain11b.d[1][9] , db8b.e[0] , db8b.e[10] 
 , db8b.e[1] , db8b.e[2] , db8b.e[3] , db8b.e[4] , db8b.e[5] , db8b.e[6] 
 , db8b.e[7] , db8b.e[8] , db8b.e[9] , datain11b.e[0] , datain11b.e[10] , datain11b.e[1] 
 , datain11b.e[2] , datain11b.e[3] , datain11b.e[4] , datain11b.e[5] , datain11b.e[6] , datain11b.e[7] 
 , datain11b.e[8] , datain11b.e[9] , db8b.d[0][0] , db8b.d[0][10] , db8b.d[0][1] , db8b.d[0][2] 
 , db8b.d[0][3] , db8b.d[0][4] , db8b.d[0][5] , db8b.d[0][6] , db8b.d[0][7] , db8b.d[0][8] 
 , db8b.d[0][9] , db8b.d[1][0] , db8b.d[1][10] , db8b.d[1][1] , db8b.d[1][2] , db8b.d[1][3] 
 , db8b.d[1][4] , db8b.d[1][5] , db8b.d[1][6] , db8b.d[1][7] , db8b.d[1][8] , db8b.d[1][9] 
 , _RESET );

endmodule

// Generated by E-GRAPH (EGS) v0.01

module core_db (\datain11b_d[0][0] , \datain11b_d[0][10] , \datain11b_d[0][1] , \datain11b_d[0][2] , \datain11b_d[0][3] , 
  \datain11b_d[0][4] , \datain11b_d[0][5] , \datain11b_d[0][6] , \datain11b_d[0][7] , \datain11b_d[0][8] , \datain11b_d[0][9] , 
  \datain11b_d[1][0] , \datain11b_d[1][10] , \datain11b_d[1][1] , \datain11b_d[1][2] , \datain11b_d[1][3] , \datain11b_d[1][4] , 
  \datain11b_d[1][5] , \datain11b_d[1][6] , \datain11b_d[1][7] , \datain11b_d[1][8] , \datain11b_d[1][9] , \db8b_e[0] , 
  \db8b_e[10] , \db8b_e[1] , \db8b_e[2] , \db8b_e[3] , \db8b_e[4] , \db8b_e[5] , \db8b_e[6] , \db8b_e[7] , \db8b_e[8] , 
  \db8b_e[9] , \datain11b_e[0] , \datain11b_e[10] , \datain11b_e[1] , \datain11b_e[2] , \datain11b_e[3] , \datain11b_e[4] , 
  \datain11b_e[5] , \datain11b_e[6] , \datain11b_e[7] , \datain11b_e[8] , \datain11b_e[9] , \db8b_d[0][0] , \db8b_d[0][10] , 
  \db8b_d[0][1] , \db8b_d[0][2] , \db8b_d[0][3] , \db8b_d[0][4] , \db8b_d[0][5] , \db8b_d[0][6] , \db8b_d[0][7] , \db8b_d[0][8] , 
  \db8b_d[0][9] , \db8b_d[1][0] , \db8b_d[1][10] , \db8b_d[1][1] , \db8b_d[1][2] , \db8b_d[1][3] , \db8b_d[1][4] , 
  \db8b_d[1][5] , \db8b_d[1][6] , \db8b_d[1][7] , \db8b_d[1][8] , \db8b_d[1][9] , _RESET );
  input  \datain11b_e[0] , \datain11b_e[10] , \datain11b_e[1] , \datain11b_e[2] , \datain11b_e[3] , \datain11b_e[4] ;
  input  \datain11b_e[5] , \datain11b_e[6] , \datain11b_e[7] , \datain11b_e[8] , \datain11b_e[9] , \db8b_d[0][0] ;
  input  \db8b_d[0][10] , \db8b_d[0][1] , \db8b_d[0][2] , \db8b_d[0][3] , \db8b_d[0][4] , \db8b_d[0][5] , \db8b_d[0][6] ;
  input  \db8b_d[0][7] , \db8b_d[0][8] , \db8b_d[0][9] , \db8b_d[1][0] , \db8b_d[1][10] , \db8b_d[1][1] , \db8b_d[1][2] ;
  input  \db8b_d[1][3] , \db8b_d[1][4] , \db8b_d[1][5] , \db8b_d[1][6] , \db8b_d[1][7] , \db8b_d[1][8] , \db8b_d[1][9] , _RESET ;

  output \datain11b_d[0][0] , \datain11b_d[0][10] , \datain11b_d[0][1] , \datain11b_d[0][2] , \datain11b_d[0][3] ;
  output \datain11b_d[0][4] , \datain11b_d[0][5] , \datain11b_d[0][6] , \datain11b_d[0][7] , \datain11b_d[0][8] ;
  output \datain11b_d[0][9] , \datain11b_d[1][0] , \datain11b_d[1][10] , \datain11b_d[1][1] , \datain11b_d[1][2] ;
  output \datain11b_d[1][3] , \datain11b_d[1][4] , \datain11b_d[1][5] , \datain11b_d[1][6] , \datain11b_d[1][7] ;
  output \datain11b_d[1][8] , \datain11b_d[1][9] , \db8b_e[0] , \db8b_e[10] , \db8b_e[1] , \db8b_e[2] , \db8b_e[3] , \db8b_e[4] ;
  output \db8b_e[5] , \db8b_e[6] , \db8b_e[7] , \db8b_e[8] , \db8b_e[9] ;

  wire   \core_db_RTL_BODY.n_0.0 , \core_db_RTL_BODY.n_0.1 , \core_db_RTL_BODY.n_0_63.e , \core_db_RTL_BODY.n_0_FX0.0 ;
  wire   \core_db_RTL_BODY.n_0_FX0.1 , \core_db_RTL_BODY.n_12.0 , \core_db_RTL_BODY.n_12.1 , \core_db_RTL_BODY.n_12_111.e ;
  wire   \core_db_RTL_BODY.n_12_SX0_iter2.0 , \core_db_RTL_BODY.n_12_SX0_iter2.1 , \core_db_RTL_BODY.n_13.0 ;
  wire   \core_db_RTL_BODY.n_13.1 , \core_db_RTL_BODY.n_14.0 , \core_db_RTL_BODY.n_14.1 , \core_db_RTL_BODY.n_14_89.e ;
  wire   \core_db_RTL_BODY.n_14_SX0_iter2.0 , \core_db_RTL_BODY.n_14_SX0_iter2.1 , \core_db_RTL_BODY.n_15.0 ;
  wire   \core_db_RTL_BODY.n_15.1 , \core_db_RTL_BODY.n_15_110.e , \core_db_RTL_BODY.n_15_SX0_iter2.0 ;
  wire   \core_db_RTL_BODY.n_15_SX0_iter2.1 , \core_db_RTL_BODY.n_16.0 , \core_db_RTL_BODY.n_16.1 , \core_db_RTL_BODY.n_16_90.e ;
  wire   \core_db_RTL_BODY.n_16_91.e , \core_db_RTL_BODY.n_16_FX0.0 , \core_db_RTL_BODY.n_16_FX0.1 ;
  wire   \core_db_RTL_BODY.n_16_FX0_112.e , \core_db_RTL_BODY.n_16_FX0_SX0_iter2.0 , \core_db_RTL_BODY.n_16_FX0_SX0_iter2.1 ;
  wire   \core_db_RTL_BODY.n_16_SX0_iter2.0 , \core_db_RTL_BODY.n_16_SX0_iter2.1 , \core_db_RTL_BODY.n_16_SX0_iter2_0.0 ;
  wire   \core_db_RTL_BODY.n_16_SX0_iter2_0.1 , \core_db_RTL_BODY.n_16_SX0_iter2_0.e , \core_db_RTL_BODY.n_18.0 ;
  wire   \core_db_RTL_BODY.n_18.1 , \core_db_RTL_BODY.n_19.0 , \core_db_RTL_BODY.n_19.1 , \core_db_RTL_BODY.n_19_81.e ;
  wire   \core_db_RTL_BODY.n_19_83.e , \core_db_RTL_BODY.n_19_SX0_iter2.0 , \core_db_RTL_BODY.n_19_SX0_iter2.1 ;
  wire   \core_db_RTL_BODY.n_19_SX0_iter2_0.0 , \core_db_RTL_BODY.n_19_SX0_iter2_0.1 , \core_db_RTL_BODY.n_20.0 ;
  wire   \core_db_RTL_BODY.n_20.1 , \core_db_RTL_BODY.n_20_82.e , \core_db_RTL_BODY.n_20_84.e ;
  wire   \core_db_RTL_BODY.n_20_SX0_iter2.0 , \core_db_RTL_BODY.n_20_SX0_iter2.1 , \core_db_RTL_BODY.n_20_SX0_iter2_0.0 ;
  wire   \core_db_RTL_BODY.n_20_SX0_iter2_0.1 , \core_db_RTL_BODY.n_21.0 , \core_db_RTL_BODY.n_21.1 , \core_db_RTL_BODY.n_21.e ;
  wire   \core_db_RTL_BODY.n_21_SX0_iter2.0 , \core_db_RTL_BODY.n_21_SX0_iter2.1 , \core_db_RTL_BODY.n_22.0 ;
  wire   \core_db_RTL_BODY.n_22.1 , \core_db_RTL_BODY.n_22_105.e , \core_db_RTL_BODY.n_22_107.e ;
  wire   \core_db_RTL_BODY.n_22_SX0_iter2.0 , \core_db_RTL_BODY.n_22_SX0_iter2.1 , \core_db_RTL_BODY.n_22_SX0_iter2_0.0 ;
  wire   \core_db_RTL_BODY.n_22_SX0_iter2_0.1 , \core_db_RTL_BODY.n_24.0 , \core_db_RTL_BODY.n_24.1 ;
  wire   \core_db_RTL_BODY.n_24_106.e , \core_db_RTL_BODY.n_24_108.e , \core_db_RTL_BODY.n_24_SX0_iter2.0 ;
  wire   \core_db_RTL_BODY.n_24_SX0_iter2.1 , \core_db_RTL_BODY.n_24_SX0_iter2_0.0 , \core_db_RTL_BODY.n_24_SX0_iter2_0.1 ;
  wire   \core_db_RTL_BODY.n_25.0 , \core_db_RTL_BODY.n_25.1 , \core_db_RTL_BODY.n_25.e , \core_db_RTL_BODY.n_25_SX0_iter2.0 ;
  wire   \core_db_RTL_BODY.n_25_SX0_iter2.1 , \core_db_RTL_BODY.n_27.0 , \core_db_RTL_BODY.n_27.1 , \core_db_RTL_BODY.n_27_96.e ;
  wire   \core_db_RTL_BODY.n_27_SX0_iter2.0 , \core_db_RTL_BODY.n_27_SX0_iter2.1 , \core_db_RTL_BODY.n_28.0 ;
  wire   \core_db_RTL_BODY.n_28.1 , \core_db_RTL_BODY.n_28.e , \core_db_RTL_BODY.n_28_SX0_iter2.0 ;
  wire   \core_db_RTL_BODY.n_28_SX0_iter2.1 , \core_db_RTL_BODY.n_29.0 , \core_db_RTL_BODY.n_29.1 , \core_db_RTL_BODY.n_29.e ;
  wire   \core_db_RTL_BODY.n_29_SX0_iter2.0 , \core_db_RTL_BODY.n_29_SX0_iter2.1 , \core_db_RTL_BODY.n_30.0 ;
  wire   \core_db_RTL_BODY.n_30.1 , \core_db_RTL_BODY.n_30.e , \core_db_RTL_BODY.n_30_SX0_iter2.0 ;
  wire   \core_db_RTL_BODY.n_30_SX0_iter2.1 , \core_db_RTL_BODY.n_31.0 , \core_db_RTL_BODY.n_31.1 , \core_db_RTL_BODY.n_31.e ;
  wire   \core_db_RTL_BODY.n_31_SX0_iter2.0 , \core_db_RTL_BODY.n_31_SX0_iter2.1 , \core_db_RTL_BODY.n_32.0 ;
  wire   \core_db_RTL_BODY.n_32.1 , \core_db_RTL_BODY.n_32.e , \core_db_RTL_BODY.n_32_SX0_iter2.0 ;
  wire   \core_db_RTL_BODY.n_32_SX0_iter2.1 , \core_db_RTL_BODY.n_33.0 , \core_db_RTL_BODY.n_33.1 , \core_db_RTL_BODY.n_35.0 ;
  wire   \core_db_RTL_BODY.n_35.1 , \core_db_RTL_BODY.n_53.0 , \core_db_RTL_BODY.n_53.1 , \d[0].0 , \d[0].1 , \d[0]_65.e ;
  wire   \d[0]_68.e , \d[0]_SX0_iter2.0 , \d[0]_SX0_iter2.1 , \d[0]_SX0_iter2.e , \d[0]_SX0_iter2_0.0 , \d[0]_SX0_iter2_0.1 ;
  wire   \d[0]_SX0_iter2_0.e , \d[0]_SX1_iter2.0 , \d[0]_SX1_iter2.1 , \d[0]_SX1_iter2.e , \d[0]_SX1_iter2_0.0 ;
  wire   \d[0]_SX1_iter2_0.1 , \d[0]_SX2_iter2.0 , \d[0]_SX2_iter2.1 , \d[1].0 , \d[1].1 , \d[1]_70.e , \d[1]_72.e ;
  wire   \d[1]_SX0_iter2.0 , \d[1]_SX0_iter2.1 , \d[1]_SX0_iter2.e , \d[1]_SX0_iter2_0.0 , \d[1]_SX0_iter2_0.1 ;
  wire   \d[1]_SX0_iter2_0.e , \d[1]_SX1_iter2.0 , \d[1]_SX1_iter2.1 , \d[1]_SX1_iter2_0.0 , \d[1]_SX1_iter2_0.1 ;
  wire   \d[1]_SX1_iter2_0.e , \d[1]_SX2_iter2.0 , \d[1]_SX2_iter2.1 , \d[2].0 , \d[2].1 , \d[2]_75.e , \d[2]_78.e , \d[2]_79.e ;
  wire   \d[2]_SX0_iter2.0 , \d[2]_SX0_iter2.1 , \d[2]_SX0_iter2.e , \d[2]_SX0_iter2_0.0 , \d[2]_SX0_iter2_0.1 ;
  wire   \d[2]_SX0_iter2_1.0 , \d[2]_SX0_iter2_1.1 , \d[2]_SX0_iter2_1.e , \d[2]_SX1_iter2.0 , \d[2]_SX1_iter2.1 ;
  wire   \d[2]_SX1_iter2.e , \d[2]_SX1_iter2_0.0 , \d[2]_SX1_iter2_0.1 , \d[2]_SX2_iter2.0 , \d[2]_SX2_iter2.1 , \d[3].0 ;
  wire   \d[3].1 , \d[3]_85.e , \d[3]_86.e , \d[3]_SX0_iter2.0 , \d[3]_SX0_iter2.1 , \d[3]_SX0_iter2_0.0 , \d[3]_SX0_iter2_0.1 ;
  wire   \d[3]_SX0_iter2_0.e , \d[3]_SX1_iter2.0 , \d[3]_SX1_iter2.1 , \d[3]_SX1_iter2.e , \d[3]_SX2_iter2.0 ;
  wire   \d[3]_SX2_iter2.1 , \d[4].0 , \d[4].1 , \d[4]_101.e , \d[4]_98.e , \d[4]_SX0_iter2.0 , \d[4]_SX0_iter2.1 ;
  wire   \d[4]_SX0_iter2.e , \d[4]_SX0_iter2_0.0 , \d[4]_SX0_iter2_0.1 , \d[4]_SX0_iter2_0.e , \d[4]_SX1_iter2.0 ;
  wire   \d[4]_SX1_iter2.1 , \d[4]_SX1_iter2.e , \d[4]_SX1_iter2_0.0 , \d[4]_SX1_iter2_0.1 , \d[4]_SX1_iter2_0.e ;
  wire   \d[4]_SX2_iter2.0 , \d[4]_SX2_iter2.1 , \d[4]_SX2_iter2_0.0 , \d[4]_SX2_iter2_0.1 , \d[5].0 , \d[5].1 , \d[5]_113.e ;
  wire   \d[5]_115.e , \d[5]_118.e , \d[5]_SX0_iter2.0 , \d[5]_SX0_iter2.1 , \d[5]_SX0_iter2.e , \d[5]_SX0_iter2_0.0 ;
  wire   \d[5]_SX0_iter2_0.1 , \d[5]_SX0_iter2_0.e , \d[5]_SX0_iter2_1.0 , \d[5]_SX0_iter2_1.1 , \d[5]_SX1_iter2.0 ;
  wire   \d[5]_SX1_iter2.1 , \d[5]_SX1_iter2_0.0 , \d[5]_SX1_iter2_0.1 , \d[5]_SX1_iter2_0.e , \d[5]_SX2_iter2.0 ;
  wire   \d[5]_SX2_iter2.1 , \d[6].0 , \d[6].1 , \d[6]_119.e , \d[6]_122.e , \d[6]_124.e , \d[6]_SX0_iter2.0 ;
  wire   \d[6]_SX0_iter2.1 , \d[6]_SX0_iter2.e , \d[6]_SX0_iter2_0.0 , \d[6]_SX0_iter2_0.1 , \d[6]_SX0_iter2_0.e ;
  wire   \d[6]_SX0_iter2_1.0 , \d[6]_SX0_iter2_1.1 , \d[6]_SX1_iter2.0 , \d[6]_SX1_iter2.1 , \d[6]_SX1_iter2.e ;
  wire   \d[6]_SX1_iter2_0.0 , \d[6]_SX1_iter2_0.1 , \d[6]_SX2_iter2.0 , \d[6]_SX2_iter2.1 , \datain11b_d[0][0] ;
  wire   \datain11b_d[0][1] , \datain11b_d[0][2] , \datain11b_d[0][3] , \datain11b_d[0][4] , \datain11b_d[0][5] ;
  wire   \datain11b_d[0][6] , \datain11b_d[0][7] , \datain11b_d[1][0] , \datain11b_d[1][1] , \datain11b_d[1][2] ;
  wire   \datain11b_d[1][3] , \datain11b_d[1][4] , \datain11b_d[1][5] , \datain11b_d[1][6] , \datain11b_d[1][7] , \db8b_e[0] ;
  wire   \db8b_e[10] , \db8b_e[1] , \db8b_e[2] , \db8b_e[3] , \db8b_e[4] , \db8b_e[5] , \db8b_e[6] , \db8b_e[7] , \db8b_e[8] ;
  wire   \db8b_e[9] , \n_30.0 , \n_30.1 , \n_30.e , \n_32.0 , \n_32.1 , \n_32.e , \n_33.0 , \n_33.1 , \n_33.e , \n_34.0 ;
  wire   \n_34.1 , \n_34_42.e , \n_34_44.e , \n_35.0 , \n_35.1 , \n_35.e , \n_36.0 , \n_36.1 , \n_36.e , \n_37.0 , \n_37.1 ;
  wire   \n_37.e , \pchb_cloud_11_inst_go , \pchb_cloud_11_inst_valid_out_0 , \pchb_cloud_18_inst_go ;
  wire   \pchb_cloud_18_inst_valid_out_0 , \pchb_cloud_38_inst_go , \pchb_cloud_38_inst_valid_out_0 , \pchb_cloud_39_inst_go ;
  wire   \pchb_cloud_39_inst_valid_out_0 , \pchb_cloud_48_inst_go , \pchb_cloud_48_inst_valid_out_0 ;
  wire   \pchb_cloud_48_inst_valid_out_1 , \pchb_cloud_50_inst_go , \pchb_cloud_50_inst_valid_out_0 ;
  wire   \pchb_cloud_50_inst_valid_out_1 , \pchb_cloud_52_inst_go , \pchb_cloud_52_inst_valid_out_0 ;
  wire   \pchb_cloud_52_inst_valid_out_1 , \pchb_cloud_54_inst_go , \pchb_cloud_54_inst_valid_out_0 ;
  wire   \pchb_cloud_54_inst_valid_out_1 , \pchb_cloud_56_inst_go , \pchb_cloud_56_inst_valid_out_0 ;
  wire   \pchb_cloud_56_inst_valid_out_1 , \pchb_cloud_57_inst_go , \pchb_cloud_57_inst_valid_out_0 ;
  wire   \pchb_cloud_57_inst_valid_out_1 , \pchb_cloud_57_inst_valid_out_2 , \pchb_cloud_57_inst_valid_out_3 ;
  wire   \pchb_cloud_58_inst_go , \pchb_cloud_58_inst_valid_out_0 , \pchb_cloud_58_inst_valid_out_1 ;
  wire   \pchb_cloud_58_inst_valid_out_2 , \pchb_cloud_60_inst_go , \pchb_cloud_60_inst_valid_out_0 ;
  wire   \pchb_cloud_60_inst_valid_out_1 , \pchb_cloud_60_inst_valid_out_2 , \pchb_cloud_60_inst_valid_out_3 ;
  wire   \pchb_cloud_61_inst_go , \pchb_cloud_61_inst_valid_out_0 , \pchb_cloud_61_inst_valid_out_1 , \pchb_cloud_62_inst_go ;
  wire   \pchb_cloud_62_inst_valid_out_0 , \pchb_cloud_62_inst_valid_out_1 ;

  trireg \c11.e , \c18.e , \c38.e , \c39.e , \c48.e , \c50.e , \c52.e , \c54.e , \c56.e , \c57.e , \c58.e , \c60.e , \c61.e ;
  trireg \c62.e , \pchb_cfbuf_63_FX_inst_en0 , \pchb_cfbuf_64_FX_inst_en0 , \pchb_cloud_0_inst_en0 , \pchb_cloud_11_inst_en0 ;
  trireg \pchb_cloud_18_inst_en0 , \pchb_cloud_2_inst_en0 , \pchb_cloud_38_inst_en0 , \pchb_cloud_39_inst_en0 ;
  trireg \pchb_cloud_3_inst_en0 , \pchb_cloud_48_inst_en0 , \pchb_cloud_48_inst_en1 , \pchb_cloud_4_inst_en0 ;
  trireg \pchb_cloud_50_inst_en0 , \pchb_cloud_52_inst_en0 , \pchb_cloud_54_inst_en0 , \pchb_cloud_56_inst_en0 ;
  trireg \pchb_cloud_56_inst_en1 , \pchb_cloud_57_inst_en0 , \pchb_cloud_57_inst_en3 , \pchb_cloud_58_inst_en0 ;
  trireg \pchb_cloud_5_inst_en0 , \pchb_cloud_60_inst_en0 , \pchb_cloud_60_inst_en2 , \pchb_cloud_60_inst_en3 ;
  trireg \pchb_cloud_61_inst_en0 , \pchb_cloud_62_inst_en0 , \pchb_cloud_6_inst_en0 , \pchb_cloud_7_inst_en0 ;


  assign \datain11b_d[1][10] = 1'b0 ;
  assign \datain11b_d[1][8] = 1'b0 ;
  assign \datain11b_d[1][9] = 1'b0 ;

  \synthesis.qdi.special.BUF.4 \pchb_cloud_0_inst_db8b_RECEIVE.recv.bits[0].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db8b_d[0][0] ), 
    .\L.1 ( \db8b_d[1][0] ), 
    .\L.e ( \db8b_e[0] ), 
    .\R.0 ( \d[0].0 ), 
    .\R.1 ( \d[0].1 ), 
    .\R.e ( \pchb_cloud_0_inst_en0 ));
  \synthesis.qdi.special.CTREE3.2 \pchb_cloud_0_inst_db8b_RECEIVE.recv.bits[0].recv_companion0 ( 
    .x ( \pchb_cloud_0_inst_en0 ), 
    .\a[0] ( \d[0]_65.e ), 
    .\a[1] ( \c56.e ), 
    .\a[2] ( \d[0]_68.e ));
  \synthesis.qdi.special.BB.2 \pchb_cloud_1_inst_db8b_RECEIVE.recv.bits[10].recv ( 
    .\L.0 ( \db8b_d[0][10] ), 
    .\L.1 ( \db8b_d[1][10] ), 
    .\L.e ( \db8b_e[10] ), 
    ._RESET ( _RESET ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_2_inst_db8b_RECEIVE.recv.bits[1].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db8b_d[0][1] ), 
    .\L.1 ( \db8b_d[1][1] ), 
    .\L.e ( \db8b_e[1] ), 
    .\R.0 ( \d[1].0 ), 
    .\R.1 ( \d[1].1 ), 
    .\R.e ( \pchb_cloud_2_inst_en0 ));
  \synthesis.qdi.special.CTREE3.2 \pchb_cloud_2_inst_db8b_RECEIVE.recv.bits[1].recv_companion0 ( 
    .x ( \pchb_cloud_2_inst_en0 ), 
    .\a[0] ( \d[1]_70.e ), 
    .\a[1] ( \d[1]_72.e ), 
    .\a[2] ( \c62.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_3_inst_db8b_RECEIVE.recv.bits[2].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db8b_d[0][2] ), 
    .\L.1 ( \db8b_d[1][2] ), 
    .\L.e ( \db8b_e[2] ), 
    .\R.0 ( \d[2].0 ), 
    .\R.1 ( \d[2].1 ), 
    .\R.e ( \pchb_cloud_3_inst_en0 ));
  \synthesis.qdi.special.CTREE4.2 \pchb_cloud_3_inst_db8b_RECEIVE.recv.bits[2].recv_companion0 ( 
    .x ( \pchb_cloud_3_inst_en0 ), 
    .\a[0] ( \d[2]_75.e ), 
    .\a[1] ( \d[2]_78.e ), 
    .\a[2] ( \d[2]_79.e ), 
    .\a[3] ( \c62.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_4_inst_db8b_RECEIVE.recv.bits[3].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db8b_d[0][3] ), 
    .\L.1 ( \db8b_d[1][3] ), 
    .\L.e ( \db8b_e[3] ), 
    .\R.0 ( \d[3].0 ), 
    .\R.1 ( \d[3].1 ), 
    .\R.e ( \pchb_cloud_4_inst_en0 ));
  \synthesis.qdi.special.CTREE3.2 \pchb_cloud_4_inst_db8b_RECEIVE.recv.bits[3].recv_companion0 ( 
    .x ( \pchb_cloud_4_inst_en0 ), 
    .\a[0] ( \d[3]_85.e ), 
    .\a[1] ( \d[3]_86.e ), 
    .\a[2] ( \c61.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_5_inst_db8b_RECEIVE.recv.bits[4].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db8b_d[0][4] ), 
    .\L.1 ( \db8b_d[1][4] ), 
    .\L.e ( \db8b_e[4] ), 
    .\R.0 ( \d[4].0 ), 
    .\R.1 ( \d[4].1 ), 
    .\R.e ( \pchb_cloud_5_inst_en0 ));
  \synthesis.qdi.special.CTREE3.2 \pchb_cloud_5_inst_db8b_RECEIVE.recv.bits[4].recv_companion0 ( 
    .x ( \pchb_cloud_5_inst_en0 ), 
    .\a[0] ( \d[4]_98.e ), 
    .\a[1] ( \d[4]_101.e ), 
    .\a[2] ( \c62.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_6_inst_db8b_RECEIVE.recv.bits[5].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db8b_d[0][5] ), 
    .\L.1 ( \db8b_d[1][5] ), 
    .\L.e ( \db8b_e[5] ), 
    .\R.0 ( \d[5].0 ), 
    .\R.1 ( \d[5].1 ), 
    .\R.e ( \pchb_cloud_6_inst_en0 ));
  \synthesis.qdi.special.CTREE4.2 \pchb_cloud_6_inst_db8b_RECEIVE.recv.bits[5].recv_companion0 ( 
    .x ( \pchb_cloud_6_inst_en0 ), 
    .\a[0] ( \d[5]_113.e ), 
    .\a[1] ( \d[5]_115.e ), 
    .\a[2] ( \c56.e ), 
    .\a[3] ( \d[5]_118.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_7_inst_db8b_RECEIVE.recv.bits[6].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db8b_d[0][6] ), 
    .\L.1 ( \db8b_d[1][6] ), 
    .\L.e ( \db8b_e[6] ), 
    .\R.0 ( \d[6].0 ), 
    .\R.1 ( \d[6].1 ), 
    .\R.e ( \pchb_cloud_7_inst_en0 ));
  \synthesis.qdi.special.CTREE4.2 \pchb_cloud_7_inst_db8b_RECEIVE.recv.bits[6].recv_companion0 ( 
    .x ( \pchb_cloud_7_inst_en0 ), 
    .\a[0] ( \d[6]_119.e ), 
    .\a[1] ( \d[6]_122.e ), 
    .\a[2] ( \d[6]_124.e ), 
    .\a[3] ( \c62.e ));
  \synthesis.qdi.special.BB.2 \pchb_cloud_8_inst_db8b_RECEIVE.recv.bits[7].recv ( 
    .\L.0 ( \db8b_d[0][7] ), 
    .\L.1 ( \db8b_d[1][7] ), 
    .\L.e ( \db8b_e[7] ), 
    ._RESET ( _RESET ));
  \synthesis.qdi.special.BB.2 \pchb_cloud_9_inst_db8b_RECEIVE.recv.bits[8].recv ( 
    .\L.0 ( \db8b_d[0][8] ), 
    .\L.1 ( \db8b_d[1][8] ), 
    .\L.e ( \db8b_e[8] ), 
    ._RESET ( _RESET ));
  \synthesis.qdi.special.BB.2 \pchb_cloud_10_inst_db8b_RECEIVE.recv.bits[9].recv ( 
    .\L.0 ( \db8b_d[0][9] ), 
    .\L.1 ( \db8b_d[1][9] ), 
    .\L.e ( \db8b_e[9] ), 
    ._RESET ( _RESET ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \core_db_RTL_BODY.g1595 ( 
    .V ( \pchb_cloud_11_inst_valid_out_0 ), 
    .en ( \pchb_cloud_11_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_21_SX0_iter2.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_21_SX0_iter2.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_21_SX0_iter2.1 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_21_SX0_iter2.0 ), 
    .\A[2].0 ( \d[6]_SX2_iter2.1 ), 
    .\A[2].1 ( \d[6]_SX2_iter2.0 ), 
    .\A[3].0 ( \core_db_RTL_BODY.n_0.1 ), 
    .\A[3].1 ( \core_db_RTL_BODY.n_0.0 ), 
    .\X.0 ( \n_30.0 ), 
    .\X.1 ( \n_30.1 ));
  \synthesis.qdi.special.CTREE2.2 \ctreecore_db_RTL_BODY.g1595 ( 
    .x ( \pchb_cloud_11_inst_en0 ), 
    .\a[0] ( \pchb_cloud_11_inst_go ), 
    .\a[1] ( \n_30.e ));
  \synthesis.qdi.special.CTRL31.2 \pchb_cloud_11_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_11_inst_go ), 
    .Ae ( \c11.e ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_21_SX0_iter2.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_21_SX0_iter2.1 ), 
    .\A[1].0 ( \d[6]_SX2_iter2.0 ), 
    .\A[1].1 ( \d[6]_SX2_iter2.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_0.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_0.1 ), 
    .\V[0] ( \pchb_cloud_11_inst_valid_out_0 ));
  \synthesis.qdi.logic5.LOGIC5_00035557.2 \core_db_RTL_BODY.g1603 ( 
    .V ( \pchb_cloud_18_inst_valid_out_0 ), 
    .en ( \pchb_cloud_18_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_16_FX0.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_16_FX0.1 ), 
    .\A[1].0 ( \d[6]_SX1_iter2_0.1 ), 
    .\A[1].1 ( \d[6]_SX1_iter2_0.0 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_19_SX0_iter2.1 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_19_SX0_iter2.0 ), 
    .\A[3].0 ( \core_db_RTL_BODY.n_20_SX0_iter2.1 ), 
    .\A[3].1 ( \core_db_RTL_BODY.n_20_SX0_iter2.0 ), 
    .\A[4].0 ( \core_db_RTL_BODY.n_53.0 ), 
    .\A[4].1 ( \core_db_RTL_BODY.n_53.1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_35.1 ), 
    .\X.1 ( \core_db_RTL_BODY.n_35.0 ));
  \synthesis.qdi.special.CTREE2.2 \ctreecore_db_RTL_BODY.g1603 ( 
    .x ( \pchb_cloud_18_inst_en0 ), 
    .\a[0] ( \pchb_cloud_18_inst_go ), 
    .\a[1] ( \c38.e ));
  \synthesis.qdi.special.CTRL51.2 \pchb_cloud_18_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_18_inst_go ), 
    .Ae ( \c18.e ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_16_FX0.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_16_FX0.1 ), 
    .\A[1].0 ( \d[6]_SX1_iter2_0.0 ), 
    .\A[1].1 ( \d[6]_SX1_iter2_0.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_19_SX0_iter2.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_19_SX0_iter2.1 ), 
    .\A[3].0 ( \core_db_RTL_BODY.n_20_SX0_iter2.0 ), 
    .\A[3].1 ( \core_db_RTL_BODY.n_20_SX0_iter2.1 ), 
    .\A[4].0 ( \core_db_RTL_BODY.n_53.0 ), 
    .\A[4].1 ( \core_db_RTL_BODY.n_53.1 ), 
    .\V[0] ( \pchb_cloud_18_inst_valid_out_0 ));
  \synthesis.qdi.logic5.LOGIC5_00000777.4 \core_db_RTL_BODY.g2 ( 
    .V ( \pchb_cloud_38_inst_valid_out_0 ), 
    .en ( \pchb_cloud_38_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_27.1 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_27.0 ), 
    .\A[1].0 ( \d[4]_SX2_iter2.0 ), 
    .\A[1].1 ( \d[4]_SX2_iter2.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_33.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_33.1 ), 
    .\A[3].0 ( \core_db_RTL_BODY.n_16_FX0_SX0_iter2.0 ), 
    .\A[3].1 ( \core_db_RTL_BODY.n_16_FX0_SX0_iter2.1 ), 
    .\A[4].0 ( \core_db_RTL_BODY.n_35.1 ), 
    .\A[4].1 ( \core_db_RTL_BODY.n_35.0 ), 
    .\X.0 ( \core_db_RTL_BODY.n_0.0 ), 
    .\X.1 ( \core_db_RTL_BODY.n_0.1 ));
  \synthesis.qdi.special.CTREE4.2 \ctreecore_db_RTL_BODY.g2 ( 
    .x ( \pchb_cloud_38_inst_en0 ), 
    .\a[3] ( \pchb_cloud_38_inst_go ), 
    .\a[0] ( \c11.e ), 
    .\a[1] ( \c50.e ), 
    .\a[2] ( \core_db_RTL_BODY.n_0_63.e ));
  \synthesis.qdi.special.CTRL51.2 \pchb_cloud_38_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_38_inst_go ), 
    .Ae ( \c38.e ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_27.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_27.1 ), 
    .\A[1].0 ( \d[4]_SX2_iter2.0 ), 
    .\A[1].1 ( \d[4]_SX2_iter2.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_33.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_33.1 ), 
    .\A[3].0 ( \core_db_RTL_BODY.n_16_FX0_SX0_iter2.0 ), 
    .\A[3].1 ( \core_db_RTL_BODY.n_16_FX0_SX0_iter2.1 ), 
    .\A[4].0 ( \core_db_RTL_BODY.n_35.0 ), 
    .\A[4].1 ( \core_db_RTL_BODY.n_35.1 ), 
    .\V[0] ( \pchb_cloud_38_inst_valid_out_0 ));
  \synthesis.qdi.logic6.LOGIC6_0000077707770777.2 \core_db_RTL_BODY.g1651 ( 
    .V ( \pchb_cloud_39_inst_valid_out_0 ), 
    .en ( \pchb_cloud_39_inst_en0 ), 
    .\A[0].0 ( \d[3]_SX0_iter2.0 ), 
    .\A[0].1 ( \d[3]_SX0_iter2.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_19_SX0_iter2_0.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_19_SX0_iter2_0.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_20_SX0_iter2_0.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_20_SX0_iter2_0.1 ), 
    .\A[3].0 ( \d[5]_SX1_iter2.0 ), 
    .\A[3].1 ( \d[5]_SX1_iter2.1 ), 
    .\A[4].0 ( \core_db_RTL_BODY.n_22.0 ), 
    .\A[4].1 ( \core_db_RTL_BODY.n_22.1 ), 
    .\A[5].0 ( \d[1]_SX1_iter2.0 ), 
    .\A[5].1 ( \d[1]_SX1_iter2.1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_53.0 ), 
    .\X.1 ( \core_db_RTL_BODY.n_53.1 ));
  \synthesis.qdi.special.CTREE2.2 \ctreecore_db_RTL_BODY.g1651 ( 
    .x ( \pchb_cloud_39_inst_en0 ), 
    .\a[0] ( \pchb_cloud_39_inst_go ), 
    .\a[1] ( \c18.e ));
  \synthesis.qdi.special.CTRL61.2 \pchb_cloud_39_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_39_inst_go ), 
    .Ae ( \c39.e ), 
    .\A[0].0 ( \d[3]_SX0_iter2.0 ), 
    .\A[0].1 ( \d[3]_SX0_iter2.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_19_SX0_iter2_0.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_19_SX0_iter2_0.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_20_SX0_iter2_0.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_20_SX0_iter2_0.1 ), 
    .\A[3].0 ( \d[5]_SX1_iter2.0 ), 
    .\A[3].1 ( \d[5]_SX1_iter2.1 ), 
    .\A[4].0 ( \core_db_RTL_BODY.n_22.0 ), 
    .\A[4].1 ( \core_db_RTL_BODY.n_22.1 ), 
    .\A[5].0 ( \d[1]_SX1_iter2.0 ), 
    .\A[5].1 ( \d[1]_SX1_iter2.1 ), 
    .\V[0] ( \pchb_cloud_39_inst_valid_out_0 ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_40_inst_datain11b_SEND.send.bits[0].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \datain11b_e[0] ), 
    .\L.0 ( \n_37.0 ), 
    .\L.1 ( \n_37.1 ), 
    .\L.e ( \n_37.e ), 
    .\R.0 ( \datain11b_d[0][0] ), 
    .\R.1 ( \datain11b_d[1][0] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_41_inst_datain11b_SEND.send.bits[1].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \datain11b_e[1] ), 
    .\L.0 ( \n_36.0 ), 
    .\L.1 ( \n_36.1 ), 
    .\L.e ( \n_36.e ), 
    .\R.0 ( \datain11b_d[0][1] ), 
    .\R.1 ( \datain11b_d[1][1] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_42_inst_datain11b_SEND.send.bits[2].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \datain11b_e[2] ), 
    .\L.0 ( \n_34.0 ), 
    .\L.1 ( \n_34.1 ), 
    .\L.e ( \n_34_42.e ), 
    .\R.0 ( \datain11b_d[0][2] ), 
    .\R.1 ( \datain11b_d[1][2] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_43_inst_datain11b_SEND.send.bits[3].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \datain11b_e[3] ), 
    .\L.0 ( \n_35.0 ), 
    .\L.1 ( \n_35.1 ), 
    .\L.e ( \n_35.e ), 
    .\R.0 ( \datain11b_d[0][3] ), 
    .\R.1 ( \datain11b_d[1][3] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_44_inst_datain11b_SEND.send.bits[4].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \datain11b_e[4] ), 
    .\L.0 ( \n_34.0 ), 
    .\L.1 ( \n_34.1 ), 
    .\L.e ( \n_34_44.e ), 
    .\R.0 ( \datain11b_d[0][4] ), 
    .\R.1 ( \datain11b_d[1][4] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_45_inst_datain11b_SEND.send.bits[5].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \datain11b_e[5] ), 
    .\L.0 ( \n_33.0 ), 
    .\L.1 ( \n_33.1 ), 
    .\L.e ( \n_33.e ), 
    .\R.0 ( \datain11b_d[0][5] ), 
    .\R.1 ( \datain11b_d[1][5] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_46_inst_datain11b_SEND.send.bits[6].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \datain11b_e[6] ), 
    .\L.0 ( \n_32.0 ), 
    .\L.1 ( \n_32.1 ), 
    .\L.e ( \n_32.e ), 
    .\R.0 ( \datain11b_d[0][6] ), 
    .\R.1 ( \datain11b_d[1][6] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_47_inst_datain11b_SEND.send.bits[7].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \datain11b_e[7] ), 
    .\L.0 ( \n_30.0 ), 
    .\L.1 ( \n_30.1 ), 
    .\L.e ( \n_30.e ), 
    .\R.0 ( \datain11b_d[0][7] ), 
    .\R.1 ( \datain11b_d[1][7] ));
  \synthesis.qdi.logic2.LOGIC2_6.6 \core_db_RTL_BODY.g1619 ( 
    .V ( \pchb_cloud_48_inst_valid_out_0 ), 
    .en ( \pchb_cloud_48_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_15.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_15.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_18.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_18.1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_20.0 ), 
    .\X.1 ( \core_db_RTL_BODY.n_20.1 ));
  \synthesis.qdi.special.CTREE4.2 \ctreecore_db_RTL_BODY.g1619 ( 
    .x ( \pchb_cloud_48_inst_en0 ), 
    .\a[3] ( \pchb_cloud_48_inst_go ), 
    .\a[0] ( \core_db_RTL_BODY.n_20_82.e ), 
    .\a[1] ( \core_db_RTL_BODY.n_20_84.e ), 
    .\a[2] ( \c60.e ));
  \synthesis.qdi.logic3.LOGIC3_07.6 \core_db_RTL_BODY.g1621 ( 
    .V ( \pchb_cloud_48_inst_valid_out_1 ), 
    .en ( \pchb_cloud_48_inst_en1 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_14_SX0_iter2.1 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_14_SX0_iter2.0 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_16_SX0_iter2.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_16_SX0_iter2.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_18.1 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_18.0 ), 
    .\X.0 ( \core_db_RTL_BODY.n_19.1 ), 
    .\X.1 ( \core_db_RTL_BODY.n_19.0 ));
  \synthesis.qdi.special.CTREE4.2 \ctreecore_db_RTL_BODY.g1621 ( 
    .x ( \pchb_cloud_48_inst_en1 ), 
    .\a[3] ( \pchb_cloud_48_inst_go ), 
    .\a[0] ( \core_db_RTL_BODY.n_19_81.e ), 
    .\a[1] ( \core_db_RTL_BODY.n_19_83.e ), 
    .\a[2] ( \c60.e ));
  \synthesis.qdi.special.CTRL42.2 \pchb_cloud_48_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_48_inst_go ), 
    .Ae ( \c48.e ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_14_SX0_iter2.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_14_SX0_iter2.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_15.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_15.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_16_SX0_iter2.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_16_SX0_iter2.1 ), 
    .\A[3].0 ( \core_db_RTL_BODY.n_18.0 ), 
    .\A[3].1 ( \core_db_RTL_BODY.n_18.1 ), 
    .\V[0] ( \pchb_cloud_48_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_48_inst_valid_out_1 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \core_db_RTL_BODY.g1596 ( 
    .V ( \pchb_cloud_50_inst_valid_out_0 ), 
    .en ( \pchb_cloud_50_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_32_SX0_iter2.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_32_SX0_iter2.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_32_SX0_iter2.1 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_32_SX0_iter2.0 ), 
    .\A[2].0 ( \d[5]_SX2_iter2.1 ), 
    .\A[2].1 ( \d[5]_SX2_iter2.0 ), 
    .\A[3].0 ( \core_db_RTL_BODY.n_0.1 ), 
    .\A[3].1 ( \core_db_RTL_BODY.n_0.0 ), 
    .\X.0 ( \n_32.0 ), 
    .\X.1 ( \n_32.1 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \core_db_RTL_BODY.g1597 ( 
    .V ( \pchb_cloud_50_inst_valid_out_1 ), 
    .en ( \pchb_cloud_50_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_27_SX0_iter2.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_27_SX0_iter2.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_27_SX0_iter2.1 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_27_SX0_iter2.0 ), 
    .\A[2].0 ( \d[4]_SX2_iter2_0.1 ), 
    .\A[2].1 ( \d[4]_SX2_iter2_0.0 ), 
    .\A[3].0 ( \core_db_RTL_BODY.n_0.1 ), 
    .\A[3].1 ( \core_db_RTL_BODY.n_0.0 ), 
    .\X.0 ( \n_33.0 ), 
    .\X.1 ( \n_33.1 ));
  \synthesis.qdi.special.CTRL52.2 \pchb_cloud_50_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_50_inst_go ), 
    .Ae ( \c50.e ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_0.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_0.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_27_SX0_iter2.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_27_SX0_iter2.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_32_SX0_iter2.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_32_SX0_iter2.1 ), 
    .\A[3].0 ( \d[4]_SX2_iter2_0.0 ), 
    .\A[3].1 ( \d[4]_SX2_iter2_0.1 ), 
    .\A[4].0 ( \d[5]_SX2_iter2.0 ), 
    .\A[4].1 ( \d[5]_SX2_iter2.1 ), 
    .\V[0] ( \pchb_cloud_50_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_50_inst_valid_out_1 ));
  \synthesis.qdi.special.CTREE3.2 \ctreecore_db_RTL_BODY.g1596 ( 
    .\a[0] ( \pchb_cloud_50_inst_go ), 
    .\a[1] ( \n_32.e ), 
    .\a[2] ( \n_33.e ), 
    .x ( \pchb_cloud_50_inst_en0 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \core_db_RTL_BODY.g1598 ( 
    .V ( \pchb_cloud_52_inst_valid_out_0 ), 
    .en ( \pchb_cloud_52_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_30_SX0_iter2.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_30_SX0_iter2.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_30_SX0_iter2.1 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_30_SX0_iter2.0 ), 
    .\A[2].0 ( \d[2]_SX2_iter2.1 ), 
    .\A[2].1 ( \d[2]_SX2_iter2.0 ), 
    .\A[3].0 ( \core_db_RTL_BODY.n_0_FX0.1 ), 
    .\A[3].1 ( \core_db_RTL_BODY.n_0_FX0.0 ), 
    .\X.0 ( \n_34.0 ), 
    .\X.1 ( \n_34.1 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \core_db_RTL_BODY.g1599 ( 
    .V ( \pchb_cloud_52_inst_valid_out_1 ), 
    .en ( \pchb_cloud_52_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_31_SX0_iter2.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_31_SX0_iter2.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_31_SX0_iter2.1 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_31_SX0_iter2.0 ), 
    .\A[2].0 ( \d[3]_SX2_iter2.1 ), 
    .\A[2].1 ( \d[3]_SX2_iter2.0 ), 
    .\A[3].0 ( \core_db_RTL_BODY.n_0_FX0.1 ), 
    .\A[3].1 ( \core_db_RTL_BODY.n_0_FX0.0 ), 
    .\X.0 ( \n_35.0 ), 
    .\X.1 ( \n_35.1 ));
  \synthesis.qdi.special.CTRL52.2 \pchb_cloud_52_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_52_inst_go ), 
    .Ae ( \c52.e ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_0_FX0.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_0_FX0.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_30_SX0_iter2.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_30_SX0_iter2.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_31_SX0_iter2.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_31_SX0_iter2.1 ), 
    .\A[3].0 ( \d[2]_SX2_iter2.0 ), 
    .\A[3].1 ( \d[2]_SX2_iter2.1 ), 
    .\A[4].0 ( \d[3]_SX2_iter2.0 ), 
    .\A[4].1 ( \d[3]_SX2_iter2.1 ), 
    .\V[0] ( \pchb_cloud_52_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_52_inst_valid_out_1 ));
  \synthesis.qdi.special.CTREE4.2 \ctreecore_db_RTL_BODY.g1598 ( 
    .\a[0] ( \pchb_cloud_52_inst_go ), 
    .\a[1] ( \n_34_42.e ), 
    .\a[2] ( \n_34_44.e ), 
    .\a[3] ( \n_35.e ), 
    .x ( \pchb_cloud_52_inst_en0 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \core_db_RTL_BODY.g1600 ( 
    .V ( \pchb_cloud_54_inst_valid_out_0 ), 
    .en ( \pchb_cloud_54_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_28_SX0_iter2.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_28_SX0_iter2.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_28_SX0_iter2.1 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_28_SX0_iter2.0 ), 
    .\A[2].0 ( \d[1]_SX2_iter2.1 ), 
    .\A[2].1 ( \d[1]_SX2_iter2.0 ), 
    .\A[3].0 ( \core_db_RTL_BODY.n_0_FX0.1 ), 
    .\A[3].1 ( \core_db_RTL_BODY.n_0_FX0.0 ), 
    .\X.0 ( \n_36.0 ), 
    .\X.1 ( \n_36.1 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \core_db_RTL_BODY.g1601 ( 
    .V ( \pchb_cloud_54_inst_valid_out_1 ), 
    .en ( \pchb_cloud_54_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_29_SX0_iter2.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_29_SX0_iter2.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_29_SX0_iter2.1 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_29_SX0_iter2.0 ), 
    .\A[2].0 ( \d[0]_SX2_iter2.1 ), 
    .\A[2].1 ( \d[0]_SX2_iter2.0 ), 
    .\A[3].0 ( \core_db_RTL_BODY.n_0_FX0.1 ), 
    .\A[3].1 ( \core_db_RTL_BODY.n_0_FX0.0 ), 
    .\X.0 ( \n_37.0 ), 
    .\X.1 ( \n_37.1 ));
  \synthesis.qdi.special.CTRL52.2 \pchb_cloud_54_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_54_inst_go ), 
    .Ae ( \c54.e ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_0_FX0.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_0_FX0.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_28_SX0_iter2.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_28_SX0_iter2.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_29_SX0_iter2.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_29_SX0_iter2.1 ), 
    .\A[3].0 ( \d[0]_SX2_iter2.0 ), 
    .\A[3].1 ( \d[0]_SX2_iter2.1 ), 
    .\A[4].0 ( \d[1]_SX2_iter2.0 ), 
    .\A[4].1 ( \d[1]_SX2_iter2.1 ), 
    .\V[0] ( \pchb_cloud_54_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_54_inst_valid_out_1 ));
  \synthesis.qdi.special.CTREE3.2 \ctreecore_db_RTL_BODY.g1600 ( 
    .\a[0] ( \pchb_cloud_54_inst_go ), 
    .\a[1] ( \n_36.e ), 
    .\a[2] ( \n_37.e ), 
    .x ( \pchb_cloud_54_inst_en0 ));
  \synthesis.qdi.logic3.LOGIC3_69.4 \core_db_RTL_BODY.g1627 ( 
    .V ( \pchb_cloud_56_inst_valid_out_0 ), 
    .en ( \pchb_cloud_56_inst_en0 ), 
    .\A[0].0 ( \d[0].0 ), 
    .\A[0].1 ( \d[0].1 ), 
    .\A[1].0 ( \d[2]_SX0_iter2_0.0 ), 
    .\A[1].1 ( \d[2]_SX0_iter2_0.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_12.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_12.1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_16.0 ), 
    .\X.1 ( \core_db_RTL_BODY.n_16.1 ));
  \synthesis.qdi.special.CTREE4.2 \ctreecore_db_RTL_BODY.g1627 ( 
    .x ( \pchb_cloud_56_inst_en0 ), 
    .\a[3] ( \pchb_cloud_56_inst_go ), 
    .\a[0] ( \core_db_RTL_BODY.n_16_90.e ), 
    .\a[1] ( \c61.e ), 
    .\a[2] ( \core_db_RTL_BODY.n_16_91.e ));
  \synthesis.qdi.logic3.LOGIC3_69.2 \core_db_RTL_BODY.g1629 ( 
    .V ( \pchb_cloud_56_inst_valid_out_1 ), 
    .en ( \pchb_cloud_56_inst_en1 ), 
    .\A[0].0 ( \d[5].0 ), 
    .\A[0].1 ( \d[5].1 ), 
    .\A[1].0 ( \d[6]_SX0_iter2_1.0 ), 
    .\A[1].1 ( \d[6]_SX0_iter2_1.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_13.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_13.1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_14.0 ), 
    .\X.1 ( \core_db_RTL_BODY.n_14.1 ));
  \synthesis.qdi.special.CTREE3.2 \ctreecore_db_RTL_BODY.g1629 ( 
    .x ( \pchb_cloud_56_inst_en1 ), 
    .\a[2] ( \pchb_cloud_56_inst_go ), 
    .\a[0] ( \core_db_RTL_BODY.n_14_89.e ), 
    .\a[1] ( \c61.e ));
  \synthesis.qdi.special.CTRL62.2 \pchb_cloud_56_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_56_inst_go ), 
    .Ae ( \c56.e ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_12.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_12.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_13.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_13.1 ), 
    .\A[2].0 ( \d[0].0 ), 
    .\A[2].1 ( \d[0].1 ), 
    .\A[3].0 ( \d[2]_SX0_iter2_0.0 ), 
    .\A[3].1 ( \d[2]_SX0_iter2_0.1 ), 
    .\A[4].0 ( \d[5].0 ), 
    .\A[4].1 ( \d[5].1 ), 
    .\A[5].0 ( \d[6]_SX0_iter2_1.0 ), 
    .\A[5].1 ( \d[6]_SX0_iter2_1.1 ), 
    .\V[0] ( \pchb_cloud_56_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_56_inst_valid_out_1 ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \core_db_RTL_BODY.g1607 ( 
    .V ( \pchb_cloud_57_inst_valid_out_0 ), 
    .en ( \pchb_cloud_57_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_24_SX0_iter2.1 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_24_SX0_iter2.0 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_16_FX0.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_16_FX0.1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_31.1 ), 
    .\X.1 ( \core_db_RTL_BODY.n_31.0 ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \core_db_RTL_BODY.g1608 ( 
    .V ( \pchb_cloud_57_inst_valid_out_1 ), 
    .en ( \pchb_cloud_57_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_24_SX0_iter2.1 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_24_SX0_iter2.0 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_16_FX0.1 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_16_FX0.0 ), 
    .\X.0 ( \core_db_RTL_BODY.n_30.1 ), 
    .\X.1 ( \core_db_RTL_BODY.n_30.0 ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \core_db_RTL_BODY.g1609 ( 
    .V ( \pchb_cloud_57_inst_valid_out_2 ), 
    .en ( \pchb_cloud_57_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_22_SX0_iter2.1 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_22_SX0_iter2.0 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_16_FX0.1 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_16_FX0.0 ), 
    .\X.0 ( \core_db_RTL_BODY.n_29.1 ), 
    .\X.1 ( \core_db_RTL_BODY.n_29.0 ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \core_db_RTL_BODY.g1610 ( 
    .V ( \pchb_cloud_57_inst_valid_out_3 ), 
    .en ( \pchb_cloud_57_inst_en3 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_22_SX0_iter2.1 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_22_SX0_iter2.0 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_16_FX0.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_16_FX0.1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_28.1 ), 
    .\X.1 ( \core_db_RTL_BODY.n_28.0 ));
  \synthesis.qdi.special.CTREE2.2 \ctreecore_db_RTL_BODY.g1610 ( 
    .x ( \pchb_cloud_57_inst_en3 ), 
    .\a[0] ( \pchb_cloud_57_inst_go ), 
    .\a[1] ( \core_db_RTL_BODY.n_28.e ));
  \synthesis.qdi.special.CTRL34.2 \pchb_cloud_57_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_57_inst_go ), 
    .Ae ( \c57.e ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_16_FX0.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_16_FX0.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_22_SX0_iter2.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_22_SX0_iter2.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_24_SX0_iter2.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_24_SX0_iter2.1 ), 
    .\V[0] ( \pchb_cloud_57_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_57_inst_valid_out_1 ), 
    .\V[2] ( \pchb_cloud_57_inst_valid_out_2 ), 
    .\V[3] ( \pchb_cloud_57_inst_valid_out_3 ));
  \synthesis.qdi.special.CTREE4.2 \ctreecore_db_RTL_BODY.g1607 ( 
    .\a[0] ( \pchb_cloud_57_inst_go ), 
    .\a[1] ( \core_db_RTL_BODY.n_29.e ), 
    .\a[2] ( \core_db_RTL_BODY.n_30.e ), 
    .\a[3] ( \core_db_RTL_BODY.n_31.e ), 
    .x ( \pchb_cloud_57_inst_en0 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \core_db_RTL_BODY.g1605 ( 
    .V ( \pchb_cloud_58_inst_valid_out_0 ), 
    .en ( \pchb_cloud_58_inst_en0 ), 
    .\A[0].0 ( \d[0]_SX1_iter2_0.1 ), 
    .\A[0].1 ( \d[0]_SX1_iter2_0.0 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_24_SX0_iter2_0.1 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_24_SX0_iter2_0.0 ), 
    .\A[2].0 ( \d[2]_SX1_iter2_0.1 ), 
    .\A[2].1 ( \d[2]_SX1_iter2_0.0 ), 
    .\A[3].0 ( \core_db_RTL_BODY.n_22_SX0_iter2_0.1 ), 
    .\A[3].1 ( \core_db_RTL_BODY.n_22_SX0_iter2_0.0 ), 
    .\X.0 ( \core_db_RTL_BODY.n_33.0 ), 
    .\X.1 ( \core_db_RTL_BODY.n_33.1 ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \core_db_RTL_BODY.g1606 ( 
    .V ( \pchb_cloud_58_inst_valid_out_1 ), 
    .en ( \pchb_cloud_58_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_25_SX0_iter2.1 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_25_SX0_iter2.0 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_16_FX0.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_16_FX0.1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_32.1 ), 
    .\X.1 ( \core_db_RTL_BODY.n_32.0 ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \core_db_RTL_BODY.g1611 ( 
    .V ( \pchb_cloud_58_inst_valid_out_2 ), 
    .en ( \pchb_cloud_58_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_25_SX0_iter2.1 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_25_SX0_iter2.0 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_16_FX0.1 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_16_FX0.0 ), 
    .\X.0 ( \core_db_RTL_BODY.n_27.1 ), 
    .\X.1 ( \core_db_RTL_BODY.n_27.0 ));
  \synthesis.qdi.special.CTRL63.2 \pchb_cloud_58_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_58_inst_go ), 
    .Ae ( \c58.e ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_16_FX0.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_16_FX0.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_22_SX0_iter2_0.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_22_SX0_iter2_0.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_24_SX0_iter2_0.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_24_SX0_iter2_0.1 ), 
    .\A[3].0 ( \core_db_RTL_BODY.n_25_SX0_iter2.0 ), 
    .\A[3].1 ( \core_db_RTL_BODY.n_25_SX0_iter2.1 ), 
    .\A[4].0 ( \d[0]_SX1_iter2_0.0 ), 
    .\A[4].1 ( \d[0]_SX1_iter2_0.1 ), 
    .\A[5].0 ( \d[2]_SX1_iter2_0.0 ), 
    .\A[5].1 ( \d[2]_SX1_iter2_0.1 ), 
    .\V[0] ( \pchb_cloud_58_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_58_inst_valid_out_1 ), 
    .\V[2] ( \pchb_cloud_58_inst_valid_out_2 ));
  \synthesis.qdi.special.CTREE4.2 \ctreecore_db_RTL_BODY.g1605 ( 
    .\a[0] ( \pchb_cloud_58_inst_go ), 
    .\a[1] ( \core_db_RTL_BODY.n_27_96.e ), 
    .\a[2] ( \core_db_RTL_BODY.n_32.e ), 
    .\a[3] ( \c38.e ), 
    .x ( \pchb_cloud_58_inst_en0 ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \core_db_RTL_BODY.g1613 ( 
    .V ( \pchb_cloud_60_inst_valid_out_1 ), 
    .en ( \pchb_cloud_60_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_20.1 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_20.0 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_19.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_19.1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_25.0 ), 
    .\X.1 ( \core_db_RTL_BODY.n_25.1 ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \core_db_RTL_BODY.g1614 ( 
    .V ( \pchb_cloud_60_inst_valid_out_2 ), 
    .en ( \pchb_cloud_60_inst_en2 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_19.1 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_19.0 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_20.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_20.1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_24.0 ), 
    .\X.1 ( \core_db_RTL_BODY.n_24.1 ));
  \synthesis.qdi.special.CTREE3.2 \ctreecore_db_RTL_BODY.g1614 ( 
    .x ( \pchb_cloud_60_inst_en2 ), 
    .\a[2] ( \pchb_cloud_60_inst_go ), 
    .\a[0] ( \core_db_RTL_BODY.n_24_106.e ), 
    .\a[1] ( \core_db_RTL_BODY.n_24_108.e ));
  \synthesis.qdi.logic2.LOGIC2_1.4 \core_db_RTL_BODY.g1616 ( 
    .V ( \pchb_cloud_60_inst_valid_out_3 ), 
    .en ( \pchb_cloud_60_inst_en3 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_20.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_20.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_19.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_19.1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_22.0 ), 
    .\X.1 ( \core_db_RTL_BODY.n_22.1 ));
  \synthesis.qdi.special.CTREE4.2 \ctreecore_db_RTL_BODY.g1616 ( 
    .x ( \pchb_cloud_60_inst_en3 ), 
    .\a[3] ( \pchb_cloud_60_inst_go ), 
    .\a[0] ( \c39.e ), 
    .\a[1] ( \core_db_RTL_BODY.n_22_105.e ), 
    .\a[2] ( \core_db_RTL_BODY.n_22_107.e ));
  \synthesis.qdi.logic3.LOGIC3_01.2 \core_db_RTL_BODY.g1617 ( 
    .V ( \pchb_cloud_60_inst_valid_out_0 ), 
    .en ( \pchb_cloud_60_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_19.1 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_19.0 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_20.1 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_20.0 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_15_SX0_iter2.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_15_SX0_iter2.1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_21.1 ), 
    .\X.1 ( \core_db_RTL_BODY.n_21.0 ));
  \synthesis.qdi.special.CTRL34.2 \pchb_cloud_60_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_60_inst_go ), 
    .Ae ( \c60.e ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_15_SX0_iter2.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_15_SX0_iter2.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_19.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_19.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_20.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_20.1 ), 
    .\V[0] ( \pchb_cloud_60_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_60_inst_valid_out_1 ), 
    .\V[2] ( \pchb_cloud_60_inst_valid_out_2 ), 
    .\V[3] ( \pchb_cloud_60_inst_valid_out_3 ));
  \synthesis.qdi.special.CTREE3.2 \ctreecore_db_RTL_BODY.g1617 ( 
    .\a[0] ( \pchb_cloud_60_inst_go ), 
    .\a[1] ( \core_db_RTL_BODY.n_21.e ), 
    .\a[2] ( \core_db_RTL_BODY.n_25.e ), 
    .x ( \pchb_cloud_60_inst_en0 ));
  \synthesis.qdi.logic2.LOGIC2_1.2 \core_db_RTL_BODY.g1622 ( 
    .V ( \pchb_cloud_61_inst_valid_out_0 ), 
    .en ( \pchb_cloud_61_inst_en0 ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_14.1 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_14.0 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_16.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_16.1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_18.1 ), 
    .\X.1 ( \core_db_RTL_BODY.n_18.0 ));
  \synthesis.qdi.logic3.LOGIC3_69.2 \core_db_RTL_BODY.g1628 ( 
    .V ( \pchb_cloud_61_inst_valid_out_1 ), 
    .en ( \pchb_cloud_61_inst_en0 ), 
    .\A[0].0 ( \d[3].1 ), 
    .\A[0].1 ( \d[3].0 ), 
    .\A[1].0 ( \d[5]_SX0_iter2_1.0 ), 
    .\A[1].1 ( \d[5]_SX0_iter2_1.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_12_SX0_iter2.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_12_SX0_iter2.1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_15.0 ), 
    .\X.1 ( \core_db_RTL_BODY.n_15.1 ));
  \synthesis.qdi.special.CTRL52.2 \pchb_cloud_61_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_61_inst_go ), 
    .Ae ( \c61.e ), 
    .\A[0].0 ( \core_db_RTL_BODY.n_12_SX0_iter2.0 ), 
    .\A[0].1 ( \core_db_RTL_BODY.n_12_SX0_iter2.1 ), 
    .\A[1].0 ( \core_db_RTL_BODY.n_14.0 ), 
    .\A[1].1 ( \core_db_RTL_BODY.n_14.1 ), 
    .\A[2].0 ( \core_db_RTL_BODY.n_16.0 ), 
    .\A[2].1 ( \core_db_RTL_BODY.n_16.1 ), 
    .\A[3].0 ( \d[3].0 ), 
    .\A[3].1 ( \d[3].1 ), 
    .\A[4].0 ( \d[5]_SX0_iter2_1.0 ), 
    .\A[4].1 ( \d[5]_SX0_iter2_1.1 ), 
    .\V[0] ( \pchb_cloud_61_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_61_inst_valid_out_1 ));
  \synthesis.qdi.special.CTREE3.2 \ctreecore_db_RTL_BODY.g1622 ( 
    .\a[0] ( \pchb_cloud_61_inst_go ), 
    .\a[1] ( \core_db_RTL_BODY.n_15_110.e ), 
    .\a[2] ( \c48.e ), 
    .x ( \pchb_cloud_61_inst_en0 ));
  \synthesis.qdi.logic2.LOGIC2_6.2 \core_db_RTL_BODY.g1630 ( 
    .V ( \pchb_cloud_62_inst_valid_out_0 ), 
    .en ( \pchb_cloud_62_inst_en0 ), 
    .\A[0].0 ( \d[1].0 ), 
    .\A[0].1 ( \d[1].1 ), 
    .\A[1].0 ( \d[2].0 ), 
    .\A[1].1 ( \d[2].1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_13.0 ), 
    .\X.1 ( \core_db_RTL_BODY.n_13.1 ));
  \synthesis.qdi.logic2.LOGIC2_6.2 \core_db_RTL_BODY.g1631 ( 
    .V ( \pchb_cloud_62_inst_valid_out_1 ), 
    .en ( \pchb_cloud_62_inst_en0 ), 
    .\A[0].0 ( \d[6].1 ), 
    .\A[0].1 ( \d[6].0 ), 
    .\A[1].0 ( \d[4].0 ), 
    .\A[1].1 ( \d[4].1 ), 
    .\X.0 ( \core_db_RTL_BODY.n_12.0 ), 
    .\X.1 ( \core_db_RTL_BODY.n_12.1 ));
  \synthesis.qdi.special.CTRL42.2 \pchb_cloud_62_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_62_inst_go ), 
    .Ae ( \c62.e ), 
    .\A[0].0 ( \d[1].0 ), 
    .\A[0].1 ( \d[1].1 ), 
    .\A[1].0 ( \d[2].0 ), 
    .\A[1].1 ( \d[2].1 ), 
    .\A[2].0 ( \d[4].0 ), 
    .\A[2].1 ( \d[4].1 ), 
    .\A[3].0 ( \d[6].0 ), 
    .\A[3].1 ( \d[6].1 ), 
    .\V[0] ( \pchb_cloud_62_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_62_inst_valid_out_1 ));
  \synthesis.qdi.special.CTREE3.2 \ctreecore_db_RTL_BODY.g1630 ( 
    .\a[0] ( \pchb_cloud_62_inst_go ), 
    .\a[1] ( \core_db_RTL_BODY.n_12_111.e ), 
    .\a[2] ( \c56.e ), 
    .x ( \pchb_cloud_62_inst_en0 ));
  \synthesis.qdi.special.BUF.4 \pchb_cfbuf_63_FX_inst_core_db_RTL_BODY.n_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_0.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_0.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_0_63.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_0_FX0.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_0_FX0.1 ), 
    .\R.e ( \pchb_cfbuf_63_FX_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cfbuf_63_FX_inst_core_db_RTL_BODY.n_0_buf_companion0 ( 
    .x ( \pchb_cfbuf_63_FX_inst_en0 ), 
    .\a[0] ( \c54.e ), 
    .\a[1] ( \c52.e ));
  \synthesis.qdi.special.BUF.6 \pchb_cfbuf_64_FX_inst_core_db_RTL_BODY.n_16_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_16_SX0_iter2_0.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_16_SX0_iter2_0.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_16_SX0_iter2_0.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_16_FX0.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_16_FX0.1 ), 
    .\R.e ( \pchb_cfbuf_64_FX_inst_en0 ));
  \synthesis.qdi.special.CTREE4.2 \pchb_cfbuf_64_FX_inst_core_db_RTL_BODY.n_16_buf_companion0 ( 
    .x ( \pchb_cfbuf_64_FX_inst_en0 ), 
    .\a[0] ( \core_db_RTL_BODY.n_16_FX0_112.e ), 
    .\a[1] ( \c18.e ), 
    .\a[2] ( \c58.e ), 
    .\a[3] ( \c57.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_65_SX_inst_d[0]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[0].0 ), 
    .\L.1 ( \d[0].1 ), 
    .\L.e ( \d[0]_65.e ), 
    .\R.0 ( \d[0]_SX0_iter2.0 ), 
    .\R.1 ( \d[0]_SX0_iter2.1 ), 
    .\R.e ( \d[0]_SX0_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_66_SX_inst_d[0]_SX0_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[0]_SX0_iter2.0 ), 
    .\L.1 ( \d[0]_SX0_iter2.1 ), 
    .\L.e ( \d[0]_SX0_iter2.e ), 
    .\R.0 ( \d[0]_SX1_iter2.0 ), 
    .\R.1 ( \d[0]_SX1_iter2.1 ), 
    .\R.e ( \d[0]_SX1_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_67_SX_inst_d[0]_SX1_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[0]_SX1_iter2.0 ), 
    .\L.1 ( \d[0]_SX1_iter2.1 ), 
    .\L.e ( \d[0]_SX1_iter2.e ), 
    .\R.0 ( \d[0]_SX2_iter2.0 ), 
    .\R.1 ( \d[0]_SX2_iter2.1 ), 
    .\R.e ( \c54.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_68_SX_inst_d[0]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[0].0 ), 
    .\L.1 ( \d[0].1 ), 
    .\L.e ( \d[0]_68.e ), 
    .\R.0 ( \d[0]_SX0_iter2_0.0 ), 
    .\R.1 ( \d[0]_SX0_iter2_0.1 ), 
    .\R.e ( \d[0]_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_69_SX_inst_d[0]_SX0_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[0]_SX0_iter2_0.0 ), 
    .\L.1 ( \d[0]_SX0_iter2_0.1 ), 
    .\L.e ( \d[0]_SX0_iter2_0.e ), 
    .\R.0 ( \d[0]_SX1_iter2_0.0 ), 
    .\R.1 ( \d[0]_SX1_iter2_0.1 ), 
    .\R.e ( \c58.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_70_SX_inst_d[1]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[1].0 ), 
    .\L.1 ( \d[1].1 ), 
    .\L.e ( \d[1]_70.e ), 
    .\R.0 ( \d[1]_SX0_iter2.0 ), 
    .\R.1 ( \d[1]_SX0_iter2.1 ), 
    .\R.e ( \d[1]_SX0_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_71_SX_inst_d[1]_SX0_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[1]_SX0_iter2.0 ), 
    .\L.1 ( \d[1]_SX0_iter2.1 ), 
    .\L.e ( \d[1]_SX0_iter2.e ), 
    .\R.0 ( \d[1]_SX1_iter2.0 ), 
    .\R.1 ( \d[1]_SX1_iter2.1 ), 
    .\R.e ( \c39.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_72_SX_inst_d[1]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[1].0 ), 
    .\L.1 ( \d[1].1 ), 
    .\L.e ( \d[1]_72.e ), 
    .\R.0 ( \d[1]_SX0_iter2_0.0 ), 
    .\R.1 ( \d[1]_SX0_iter2_0.1 ), 
    .\R.e ( \d[1]_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_73_SX_inst_d[1]_SX0_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[1]_SX0_iter2_0.0 ), 
    .\L.1 ( \d[1]_SX0_iter2_0.1 ), 
    .\L.e ( \d[1]_SX0_iter2_0.e ), 
    .\R.0 ( \d[1]_SX1_iter2_0.0 ), 
    .\R.1 ( \d[1]_SX1_iter2_0.1 ), 
    .\R.e ( \d[1]_SX1_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_74_SX_inst_d[1]_SX1_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[1]_SX1_iter2_0.0 ), 
    .\L.1 ( \d[1]_SX1_iter2_0.1 ), 
    .\L.e ( \d[1]_SX1_iter2_0.e ), 
    .\R.0 ( \d[1]_SX2_iter2.0 ), 
    .\R.1 ( \d[1]_SX2_iter2.1 ), 
    .\R.e ( \c54.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_75_SX_inst_d[2]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[2].0 ), 
    .\L.1 ( \d[2].1 ), 
    .\L.e ( \d[2]_75.e ), 
    .\R.0 ( \d[2]_SX0_iter2.0 ), 
    .\R.1 ( \d[2]_SX0_iter2.1 ), 
    .\R.e ( \d[2]_SX0_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_76_SX_inst_d[2]_SX0_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[2]_SX0_iter2.0 ), 
    .\L.1 ( \d[2]_SX0_iter2.1 ), 
    .\L.e ( \d[2]_SX0_iter2.e ), 
    .\R.0 ( \d[2]_SX1_iter2.0 ), 
    .\R.1 ( \d[2]_SX1_iter2.1 ), 
    .\R.e ( \d[2]_SX1_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_77_SX_inst_d[2]_SX1_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[2]_SX1_iter2.0 ), 
    .\L.1 ( \d[2]_SX1_iter2.1 ), 
    .\L.e ( \d[2]_SX1_iter2.e ), 
    .\R.0 ( \d[2]_SX2_iter2.0 ), 
    .\R.1 ( \d[2]_SX2_iter2.1 ), 
    .\R.e ( \c52.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_78_SX_inst_d[2]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[2].0 ), 
    .\L.1 ( \d[2].1 ), 
    .\L.e ( \d[2]_78.e ), 
    .\R.0 ( \d[2]_SX0_iter2_0.0 ), 
    .\R.1 ( \d[2]_SX0_iter2_0.1 ), 
    .\R.e ( \c56.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_79_SX_inst_d[2]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[2].0 ), 
    .\L.1 ( \d[2].1 ), 
    .\L.e ( \d[2]_79.e ), 
    .\R.0 ( \d[2]_SX0_iter2_1.0 ), 
    .\R.1 ( \d[2]_SX0_iter2_1.1 ), 
    .\R.e ( \d[2]_SX0_iter2_1.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_80_SX_inst_d[2]_SX0_iter2_1_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[2]_SX0_iter2_1.0 ), 
    .\L.1 ( \d[2]_SX0_iter2_1.1 ), 
    .\L.e ( \d[2]_SX0_iter2_1.e ), 
    .\R.0 ( \d[2]_SX1_iter2_0.0 ), 
    .\R.1 ( \d[2]_SX1_iter2_0.1 ), 
    .\R.e ( \c58.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_81_SX_inst_core_db_RTL_BODY.n_19_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_19.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_19.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_19_81.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_19_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_19_SX0_iter2.1 ), 
    .\R.e ( \c18.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_82_SX_inst_core_db_RTL_BODY.n_20_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_20.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_20.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_20_82.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_20_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_20_SX0_iter2.1 ), 
    .\R.e ( \c18.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_83_SX_inst_core_db_RTL_BODY.n_19_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_19.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_19.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_19_83.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_19_SX0_iter2_0.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_19_SX0_iter2_0.1 ), 
    .\R.e ( \c39.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_84_SX_inst_core_db_RTL_BODY.n_20_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_20.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_20.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_20_84.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_20_SX0_iter2_0.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_20_SX0_iter2_0.1 ), 
    .\R.e ( \c39.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_85_SX_inst_d[3]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[3].0 ), 
    .\L.1 ( \d[3].1 ), 
    .\L.e ( \d[3]_85.e ), 
    .\R.0 ( \d[3]_SX0_iter2.0 ), 
    .\R.1 ( \d[3]_SX0_iter2.1 ), 
    .\R.e ( \c39.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_86_SX_inst_d[3]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[3].0 ), 
    .\L.1 ( \d[3].1 ), 
    .\L.e ( \d[3]_86.e ), 
    .\R.0 ( \d[3]_SX0_iter2_0.0 ), 
    .\R.1 ( \d[3]_SX0_iter2_0.1 ), 
    .\R.e ( \d[3]_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_87_SX_inst_d[3]_SX0_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[3]_SX0_iter2_0.0 ), 
    .\L.1 ( \d[3]_SX0_iter2_0.1 ), 
    .\L.e ( \d[3]_SX0_iter2_0.e ), 
    .\R.0 ( \d[3]_SX1_iter2.0 ), 
    .\R.1 ( \d[3]_SX1_iter2.1 ), 
    .\R.e ( \d[3]_SX1_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_88_SX_inst_d[3]_SX1_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[3]_SX1_iter2.0 ), 
    .\L.1 ( \d[3]_SX1_iter2.1 ), 
    .\L.e ( \d[3]_SX1_iter2.e ), 
    .\R.0 ( \d[3]_SX2_iter2.0 ), 
    .\R.1 ( \d[3]_SX2_iter2.1 ), 
    .\R.e ( \c52.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_89_SX_inst_core_db_RTL_BODY.n_14_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_14.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_14.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_14_89.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_14_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_14_SX0_iter2.1 ), 
    .\R.e ( \c48.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_90_SX_inst_core_db_RTL_BODY.n_16_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_16.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_16.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_16_90.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_16_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_16_SX0_iter2.1 ), 
    .\R.e ( \c48.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_91_SX_inst_core_db_RTL_BODY.n_16_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_16.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_16.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_16_91.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_16_SX0_iter2_0.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_16_SX0_iter2_0.1 ), 
    .\R.e ( \core_db_RTL_BODY.n_16_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_92_SX_inst_core_db_RTL_BODY.n_30_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_30.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_30.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_30.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_30_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_30_SX0_iter2.1 ), 
    .\R.e ( \c52.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_93_SX_inst_core_db_RTL_BODY.n_31_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_31.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_31.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_31.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_31_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_31_SX0_iter2.1 ), 
    .\R.e ( \c52.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_94_SX_inst_core_db_RTL_BODY.n_28_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_28.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_28.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_28.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_28_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_28_SX0_iter2.1 ), 
    .\R.e ( \c54.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_95_SX_inst_core_db_RTL_BODY.n_29_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_29.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_29.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_29.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_29_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_29_SX0_iter2.1 ), 
    .\R.e ( \c54.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_96_SX_inst_core_db_RTL_BODY.n_27_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_27.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_27.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_27_96.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_27_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_27_SX0_iter2.1 ), 
    .\R.e ( \c50.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_97_SX_inst_core_db_RTL_BODY.n_32_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_32.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_32.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_32.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_32_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_32_SX0_iter2.1 ), 
    .\R.e ( \c50.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_98_SX_inst_d[4]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[4].0 ), 
    .\L.1 ( \d[4].1 ), 
    .\L.e ( \d[4]_98.e ), 
    .\R.0 ( \d[4]_SX0_iter2.0 ), 
    .\R.1 ( \d[4]_SX0_iter2.1 ), 
    .\R.e ( \d[4]_SX0_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_99_SX_inst_d[4]_SX0_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[4]_SX0_iter2.0 ), 
    .\L.1 ( \d[4]_SX0_iter2.1 ), 
    .\L.e ( \d[4]_SX0_iter2.e ), 
    .\R.0 ( \d[4]_SX1_iter2.0 ), 
    .\R.1 ( \d[4]_SX1_iter2.1 ), 
    .\R.e ( \d[4]_SX1_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_100_SX_inst_d[4]_SX1_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[4]_SX1_iter2.0 ), 
    .\L.1 ( \d[4]_SX1_iter2.1 ), 
    .\L.e ( \d[4]_SX1_iter2.e ), 
    .\R.0 ( \d[4]_SX2_iter2.0 ), 
    .\R.1 ( \d[4]_SX2_iter2.1 ), 
    .\R.e ( \c38.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_101_SX_inst_d[4]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[4].0 ), 
    .\L.1 ( \d[4].1 ), 
    .\L.e ( \d[4]_101.e ), 
    .\R.0 ( \d[4]_SX0_iter2_0.0 ), 
    .\R.1 ( \d[4]_SX0_iter2_0.1 ), 
    .\R.e ( \d[4]_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_102_SX_inst_d[4]_SX0_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[4]_SX0_iter2_0.0 ), 
    .\L.1 ( \d[4]_SX0_iter2_0.1 ), 
    .\L.e ( \d[4]_SX0_iter2_0.e ), 
    .\R.0 ( \d[4]_SX1_iter2_0.0 ), 
    .\R.1 ( \d[4]_SX1_iter2_0.1 ), 
    .\R.e ( \d[4]_SX1_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_103_SX_inst_d[4]_SX1_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[4]_SX1_iter2_0.0 ), 
    .\L.1 ( \d[4]_SX1_iter2_0.1 ), 
    .\L.e ( \d[4]_SX1_iter2_0.e ), 
    .\R.0 ( \d[4]_SX2_iter2_0.0 ), 
    .\R.1 ( \d[4]_SX2_iter2_0.1 ), 
    .\R.e ( \c50.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_104_SX_inst_core_db_RTL_BODY.n_21_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_21.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_21.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_21.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_21_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_21_SX0_iter2.1 ), 
    .\R.e ( \c11.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_105_SX_inst_core_db_RTL_BODY.n_22_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_22.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_22.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_22_105.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_22_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_22_SX0_iter2.1 ), 
    .\R.e ( \c57.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_106_SX_inst_core_db_RTL_BODY.n_24_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_24.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_24.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_24_106.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_24_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_24_SX0_iter2.1 ), 
    .\R.e ( \c57.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_107_SX_inst_core_db_RTL_BODY.n_22_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_22.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_22.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_22_107.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_22_SX0_iter2_0.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_22_SX0_iter2_0.1 ), 
    .\R.e ( \c58.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_108_SX_inst_core_db_RTL_BODY.n_24_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_24.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_24.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_24_108.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_24_SX0_iter2_0.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_24_SX0_iter2_0.1 ), 
    .\R.e ( \c58.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_109_SX_inst_core_db_RTL_BODY.n_25_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_25.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_25.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_25.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_25_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_25_SX0_iter2.1 ), 
    .\R.e ( \c58.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_110_SX_inst_core_db_RTL_BODY.n_15_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_15.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_15.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_15_110.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_15_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_15_SX0_iter2.1 ), 
    .\R.e ( \c60.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_111_SX_inst_core_db_RTL_BODY.n_12_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_12.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_12.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_12_111.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_12_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_12_SX0_iter2.1 ), 
    .\R.e ( \c61.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_112_SX_inst_core_db_RTL_BODY.n_16_FX0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \core_db_RTL_BODY.n_16_FX0.0 ), 
    .\L.1 ( \core_db_RTL_BODY.n_16_FX0.1 ), 
    .\L.e ( \core_db_RTL_BODY.n_16_FX0_112.e ), 
    .\R.0 ( \core_db_RTL_BODY.n_16_FX0_SX0_iter2.0 ), 
    .\R.1 ( \core_db_RTL_BODY.n_16_FX0_SX0_iter2.1 ), 
    .\R.e ( \c38.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_113_SX_inst_d[5]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[5].0 ), 
    .\L.1 ( \d[5].1 ), 
    .\L.e ( \d[5]_113.e ), 
    .\R.0 ( \d[5]_SX0_iter2.0 ), 
    .\R.1 ( \d[5]_SX0_iter2.1 ), 
    .\R.e ( \d[5]_SX0_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_114_SX_inst_d[5]_SX0_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[5]_SX0_iter2.0 ), 
    .\L.1 ( \d[5]_SX0_iter2.1 ), 
    .\L.e ( \d[5]_SX0_iter2.e ), 
    .\R.0 ( \d[5]_SX1_iter2.0 ), 
    .\R.1 ( \d[5]_SX1_iter2.1 ), 
    .\R.e ( \c39.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_115_SX_inst_d[5]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[5].0 ), 
    .\L.1 ( \d[5].1 ), 
    .\L.e ( \d[5]_115.e ), 
    .\R.0 ( \d[5]_SX0_iter2_0.0 ), 
    .\R.1 ( \d[5]_SX0_iter2_0.1 ), 
    .\R.e ( \d[5]_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_116_SX_inst_d[5]_SX0_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[5]_SX0_iter2_0.0 ), 
    .\L.1 ( \d[5]_SX0_iter2_0.1 ), 
    .\L.e ( \d[5]_SX0_iter2_0.e ), 
    .\R.0 ( \d[5]_SX1_iter2_0.0 ), 
    .\R.1 ( \d[5]_SX1_iter2_0.1 ), 
    .\R.e ( \d[5]_SX1_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_117_SX_inst_d[5]_SX1_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[5]_SX1_iter2_0.0 ), 
    .\L.1 ( \d[5]_SX1_iter2_0.1 ), 
    .\L.e ( \d[5]_SX1_iter2_0.e ), 
    .\R.0 ( \d[5]_SX2_iter2.0 ), 
    .\R.1 ( \d[5]_SX2_iter2.1 ), 
    .\R.e ( \c50.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_118_SX_inst_d[5]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[5].0 ), 
    .\L.1 ( \d[5].1 ), 
    .\L.e ( \d[5]_118.e ), 
    .\R.0 ( \d[5]_SX0_iter2_1.0 ), 
    .\R.1 ( \d[5]_SX0_iter2_1.1 ), 
    .\R.e ( \c61.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_119_SX_inst_d[6]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[6].0 ), 
    .\L.1 ( \d[6].1 ), 
    .\L.e ( \d[6]_119.e ), 
    .\R.0 ( \d[6]_SX0_iter2.0 ), 
    .\R.1 ( \d[6]_SX0_iter2.1 ), 
    .\R.e ( \d[6]_SX0_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_120_SX_inst_d[6]_SX0_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[6]_SX0_iter2.0 ), 
    .\L.1 ( \d[6]_SX0_iter2.1 ), 
    .\L.e ( \d[6]_SX0_iter2.e ), 
    .\R.0 ( \d[6]_SX1_iter2.0 ), 
    .\R.1 ( \d[6]_SX1_iter2.1 ), 
    .\R.e ( \d[6]_SX1_iter2.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_121_SX_inst_d[6]_SX1_iter2_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[6]_SX1_iter2.0 ), 
    .\L.1 ( \d[6]_SX1_iter2.1 ), 
    .\L.e ( \d[6]_SX1_iter2.e ), 
    .\R.0 ( \d[6]_SX2_iter2.0 ), 
    .\R.1 ( \d[6]_SX2_iter2.1 ), 
    .\R.e ( \c11.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_122_SX_inst_d[6]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[6].0 ), 
    .\L.1 ( \d[6].1 ), 
    .\L.e ( \d[6]_122.e ), 
    .\R.0 ( \d[6]_SX0_iter2_0.0 ), 
    .\R.1 ( \d[6]_SX0_iter2_0.1 ), 
    .\R.e ( \d[6]_SX0_iter2_0.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_123_SX_inst_d[6]_SX0_iter2_0_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[6]_SX0_iter2_0.0 ), 
    .\L.1 ( \d[6]_SX0_iter2_0.1 ), 
    .\L.e ( \d[6]_SX0_iter2_0.e ), 
    .\R.0 ( \d[6]_SX1_iter2_0.0 ), 
    .\R.1 ( \d[6]_SX1_iter2_0.1 ), 
    .\R.e ( \c18.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_124_SX_inst_d[6]_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \d[6].0 ), 
    .\L.1 ( \d[6].1 ), 
    .\L.e ( \d[6]_124.e ), 
    .\R.0 ( \d[6]_SX0_iter2_1.0 ), 
    .\R.1 ( \d[6]_SX0_iter2_1.1 ), 
    .\R.e ( \c56.e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_datain11b_d[0][10] ( 
    .x ( \datain11b_d[0][10] ), 
    .a ( \datain11b_e[10] ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_datain11b_d[0][8] ( 
    .x ( \datain11b_d[0][8] ), 
    .a ( \datain11b_e[8] ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_datain11b_d[0][9] ( 
    .x ( \datain11b_d[0][9] ), 
    .a ( \datain11b_e[9] ));

endmodule
