

// Generated by cosim_wrapper.pl to be used for cosim

module core_dg_cosim_wrapper(interface dg_8b, interface data_out_11b, input _RESET);

 core_dg core_dg_expanded (data_out_11b.d[0][0] , data_out_11b.d[0][10] , data_out_11b.d[0][1] , data_out_11b.d[0][2] , data_out_11b.d[0][3] , data_out_11b.d[0][4] 
 , data_out_11b.d[0][5] , data_out_11b.d[0][6] , data_out_11b.d[0][7] , data_out_11b.d[0][8] , data_out_11b.d[0][9] , data_out_11b.d[1][0] 
 , data_out_11b.d[1][10] , data_out_11b.d[1][1] , data_out_11b.d[1][2] , data_out_11b.d[1][3] , data_out_11b.d[1][4] , data_out_11b.d[1][5] 
 , data_out_11b.d[1][6] , data_out_11b.d[1][7] , data_out_11b.d[1][8] , data_out_11b.d[1][9] , dg_8b.e[0] , dg_8b.e[10] 
 , dg_8b.e[1] , dg_8b.e[2] , dg_8b.e[3] , dg_8b.e[4] , dg_8b.e[5] , dg_8b.e[6] 
 , dg_8b.e[7] , dg_8b.e[8] , dg_8b.e[9] , data_out_11b.e[0] , data_out_11b.e[10] , data_out_11b.e[1] 
 , data_out_11b.e[2] , data_out_11b.e[3] , data_out_11b.e[4] , data_out_11b.e[5] , data_out_11b.e[6] , data_out_11b.e[7] 
 , data_out_11b.e[8] , data_out_11b.e[9] , dg_8b.d[0][0] , dg_8b.d[0][10] , dg_8b.d[0][1] , dg_8b.d[0][2] 
 , dg_8b.d[0][3] , dg_8b.d[0][4] , dg_8b.d[0][5] , dg_8b.d[0][6] , dg_8b.d[0][7] , dg_8b.d[0][8] 
 , dg_8b.d[0][9] , dg_8b.d[1][0] , dg_8b.d[1][10] , dg_8b.d[1][1] , dg_8b.d[1][2] , dg_8b.d[1][3] 
 , dg_8b.d[1][4] , dg_8b.d[1][5] , dg_8b.d[1][6] , dg_8b.d[1][7] , dg_8b.d[1][8] , dg_8b.d[1][9] 
 , _RESET );

endmodule

// Generated by E-GRAPH (EGS) v0.01

module core_dg (\data_out_11b_d[0][0] , \data_out_11b_d[0][10] , \data_out_11b_d[0][1] , \data_out_11b_d[0][2] , 
  \data_out_11b_d[0][3] , \data_out_11b_d[0][4] , \data_out_11b_d[0][5] , \data_out_11b_d[0][6] , \data_out_11b_d[0][7] , 
  \data_out_11b_d[0][8] , \data_out_11b_d[0][9] , \data_out_11b_d[1][0] , \data_out_11b_d[1][10] , \data_out_11b_d[1][1] , 
  \data_out_11b_d[1][2] , \data_out_11b_d[1][3] , \data_out_11b_d[1][4] , \data_out_11b_d[1][5] , \data_out_11b_d[1][6] , 
  \data_out_11b_d[1][7] , \data_out_11b_d[1][8] , \data_out_11b_d[1][9] , \dg_8b_e[0] , \dg_8b_e[10] , \dg_8b_e[1] , 
  \dg_8b_e[2] , \dg_8b_e[3] , \dg_8b_e[4] , \dg_8b_e[5] , \dg_8b_e[6] , \dg_8b_e[7] , \dg_8b_e[8] , \dg_8b_e[9] , 
  \data_out_11b_e[0] , \data_out_11b_e[10] , \data_out_11b_e[1] , \data_out_11b_e[2] , \data_out_11b_e[3] , \data_out_11b_e[4] , 
  \data_out_11b_e[5] , \data_out_11b_e[6] , \data_out_11b_e[7] , \data_out_11b_e[8] , \data_out_11b_e[9] , \dg_8b_d[0][0] , 
  \dg_8b_d[0][10] , \dg_8b_d[0][1] , \dg_8b_d[0][2] , \dg_8b_d[0][3] , \dg_8b_d[0][4] , \dg_8b_d[0][5] , \dg_8b_d[0][6] , 
  \dg_8b_d[0][7] , \dg_8b_d[0][8] , \dg_8b_d[0][9] , \dg_8b_d[1][0] , \dg_8b_d[1][10] , \dg_8b_d[1][1] , \dg_8b_d[1][2] , 
  \dg_8b_d[1][3] , \dg_8b_d[1][4] , \dg_8b_d[1][5] , \dg_8b_d[1][6] , \dg_8b_d[1][7] , \dg_8b_d[1][8] , \dg_8b_d[1][9] , _RESET );
  input  \data_out_11b_e[0] , \data_out_11b_e[10] , \data_out_11b_e[1] , \data_out_11b_e[2] , \data_out_11b_e[3] ;
  input  \data_out_11b_e[4] , \data_out_11b_e[5] , \data_out_11b_e[6] , \data_out_11b_e[7] , \data_out_11b_e[8] ;
  input  \data_out_11b_e[9] , \dg_8b_d[0][0] , \dg_8b_d[0][10] , \dg_8b_d[0][1] , \dg_8b_d[0][2] , \dg_8b_d[0][3] ;
  input  \dg_8b_d[0][4] , \dg_8b_d[0][5] , \dg_8b_d[0][6] , \dg_8b_d[0][7] , \dg_8b_d[0][8] , \dg_8b_d[0][9] , \dg_8b_d[1][0] ;
  input  \dg_8b_d[1][10] , \dg_8b_d[1][1] , \dg_8b_d[1][2] , \dg_8b_d[1][3] , \dg_8b_d[1][4] , \dg_8b_d[1][5] , \dg_8b_d[1][6] ;
  input  \dg_8b_d[1][7] , \dg_8b_d[1][8] , \dg_8b_d[1][9] , _RESET ;

  output \data_out_11b_d[0][0] , \data_out_11b_d[0][10] , \data_out_11b_d[0][1] , \data_out_11b_d[0][2] , \data_out_11b_d[0][3] ;
  output \data_out_11b_d[0][4] , \data_out_11b_d[0][5] , \data_out_11b_d[0][6] , \data_out_11b_d[0][7] , \data_out_11b_d[0][8] ;
  output \data_out_11b_d[0][9] , \data_out_11b_d[1][0] , \data_out_11b_d[1][10] , \data_out_11b_d[1][1] , \data_out_11b_d[1][2] ;
  output \data_out_11b_d[1][3] , \data_out_11b_d[1][4] , \data_out_11b_d[1][5] , \data_out_11b_d[1][6] , \data_out_11b_d[1][7] ;
  output \data_out_11b_d[1][8] , \data_out_11b_d[1][9] , \dg_8b_e[0] , \dg_8b_e[10] , \dg_8b_e[1] , \dg_8b_e[2] , \dg_8b_e[3] ;
  output \dg_8b_e[4] , \dg_8b_e[5] , \dg_8b_e[6] , \dg_8b_e[7] , \dg_8b_e[8] , \dg_8b_e[9] ;

  wire   \d[4].0 , \d[4].1 , \d[4]_13.e , \d[5].0 , \d[5].1 , \d[5]_15.e , \d[6].0 , \d[6].1 , \d[6]_16.e , \d[7].0 , \d[7].1 ;
  wire   \d[7]_10.e , \data_out_11b_d[0][0] , \data_out_11b_d[0][10] , \data_out_11b_d[0][1] , \data_out_11b_d[0][2] ;
  wire   \data_out_11b_d[0][3] , \data_out_11b_d[0][4] , \data_out_11b_d[0][5] , \data_out_11b_d[0][6] , \data_out_11b_d[0][7] ;
  wire   \data_out_11b_d[0][8] , \data_out_11b_d[0][9] , \data_out_11b_d[1][0] , \data_out_11b_d[1][10] , \data_out_11b_d[1][1] ;
  wire   \data_out_11b_d[1][2] , \data_out_11b_d[1][3] , \data_out_11b_d[1][4] , \data_out_11b_d[1][5] , \data_out_11b_d[1][6] ;
  wire   \data_out_11b_d[1][7] , \data_out_11b_d[1][8] , \data_out_11b_d[1][9] , \dg_8b_e[0] , \dg_8b_e[10] , \dg_8b_e[1] ;
  wire   \dg_8b_e[2] , \dg_8b_e[3] , \dg_8b_e[4] , \dg_8b_e[5] , \dg_8b_e[6] , \dg_8b_e[7] , \dg_8b_e[8] , \dg_8b_e[9] ;
  wire   \n_30.0 , \n_30.1 , \n_30.e , \n_32.0 , \n_32.1 , \n_32.e , \n_33.0 , \n_33.1 , \n_33.e , \pchb_cloud_22_inst_go ;
  wire   \pchb_cloud_22_inst_valid_out_0 , \pchb_cloud_22_inst_valid_out_1 , \pchb_cloud_22_inst_valid_out_2 ;

  trireg \c22.e , \pchb_cloud_22_inst_en0 , \pchb_cloud_4_inst_en0 , \pchb_cloud_5_inst_en0 , \pchb_cloud_6_inst_en0 ;
  trireg \pchb_cloud_7_inst_en0 ;



  \synthesis.qdi.special.BB.2 \pchb_cloud_3_inst_dg_8b_RECEIVE.recv.bits[10].recv ( 
    .\L.0 ( \dg_8b_d[0][10] ), 
    .\L.1 ( \dg_8b_d[1][10] ), 
    .\L.e ( \dg_8b_e[10] ), 
    ._RESET ( _RESET ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_4_inst_dg_8b_RECEIVE.recv.bits[4].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \dg_8b_d[0][4] ), 
    .\L.1 ( \dg_8b_d[1][4] ), 
    .\L.e ( \dg_8b_e[4] ), 
    .\R.0 ( \d[4].0 ), 
    .\R.1 ( \d[4].1 ), 
    .\R.e ( \pchb_cloud_4_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cloud_4_inst_dg_8b_RECEIVE.recv.bits[4].recv_companion0 ( 
    .x ( \pchb_cloud_4_inst_en0 ), 
    .\a[0] ( \d[4]_13.e ), 
    .\a[1] ( \c22.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_5_inst_dg_8b_RECEIVE.recv.bits[5].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \dg_8b_d[0][5] ), 
    .\L.1 ( \dg_8b_d[1][5] ), 
    .\L.e ( \dg_8b_e[5] ), 
    .\R.0 ( \d[5].0 ), 
    .\R.1 ( \d[5].1 ), 
    .\R.e ( \pchb_cloud_5_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cloud_5_inst_dg_8b_RECEIVE.recv.bits[5].recv_companion0 ( 
    .x ( \pchb_cloud_5_inst_en0 ), 
    .\a[0] ( \d[5]_15.e ), 
    .\a[1] ( \c22.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_6_inst_dg_8b_RECEIVE.recv.bits[6].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \dg_8b_d[0][6] ), 
    .\L.1 ( \dg_8b_d[1][6] ), 
    .\L.e ( \dg_8b_e[6] ), 
    .\R.0 ( \d[6].0 ), 
    .\R.1 ( \d[6].1 ), 
    .\R.e ( \pchb_cloud_6_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cloud_6_inst_dg_8b_RECEIVE.recv.bits[6].recv_companion0 ( 
    .x ( \pchb_cloud_6_inst_en0 ), 
    .\a[0] ( \d[6]_16.e ), 
    .\a[1] ( \c22.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_7_inst_dg_8b_RECEIVE.recv.bits[7].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \dg_8b_d[0][7] ), 
    .\L.1 ( \dg_8b_d[1][7] ), 
    .\L.e ( \dg_8b_e[7] ), 
    .\R.0 ( \d[7].0 ), 
    .\R.1 ( \d[7].1 ), 
    .\R.e ( \pchb_cloud_7_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cloud_7_inst_dg_8b_RECEIVE.recv.bits[7].recv_companion0 ( 
    .x ( \pchb_cloud_7_inst_en0 ), 
    .\a[0] ( \d[7]_10.e ), 
    .\a[1] ( \c22.e ));
  \synthesis.qdi.special.BB.2 \pchb_cloud_8_inst_dg_8b_RECEIVE.recv.bits[8].recv ( 
    .\L.0 ( \dg_8b_d[0][8] ), 
    .\L.1 ( \dg_8b_d[1][8] ), 
    .\L.e ( \dg_8b_e[8] ), 
    ._RESET ( _RESET ));
  \synthesis.qdi.special.BB.2 \pchb_cloud_9_inst_dg_8b_RECEIVE.recv.bits[9].recv ( 
    .\L.0 ( \dg_8b_d[0][9] ), 
    .\L.1 ( \dg_8b_d[1][9] ), 
    .\L.e ( \dg_8b_e[9] ), 
    ._RESET ( _RESET ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_10_inst_data_out_11b_SEND.send.bits[10].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \data_out_11b_e[10] ), 
    .\L.0 ( \d[7].0 ), 
    .\L.1 ( \d[7].1 ), 
    .\L.e ( \d[7]_10.e ), 
    .\R.0 ( \data_out_11b_d[0][10] ), 
    .\R.1 ( \data_out_11b_d[1][10] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_11_inst_data_out_11b_SEND.send.bits[4].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \data_out_11b_e[4] ), 
    .\L.0 ( \n_33.0 ), 
    .\L.1 ( \n_33.1 ), 
    .\L.e ( \n_33.e ), 
    .\R.0 ( \data_out_11b_d[0][4] ), 
    .\R.1 ( \data_out_11b_d[1][4] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_12_inst_data_out_11b_SEND.send.bits[5].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \data_out_11b_e[5] ), 
    .\L.0 ( \n_32.0 ), 
    .\L.1 ( \n_32.1 ), 
    .\L.e ( \n_32.e ), 
    .\R.0 ( \data_out_11b_d[0][5] ), 
    .\R.1 ( \data_out_11b_d[1][5] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_13_inst_data_out_11b_SEND.send.bits[6].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \data_out_11b_e[6] ), 
    .\L.0 ( \d[4].0 ), 
    .\L.1 ( \d[4].1 ), 
    .\L.e ( \d[4]_13.e ), 
    .\R.0 ( \data_out_11b_d[0][6] ), 
    .\R.1 ( \data_out_11b_d[1][6] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_14_inst_data_out_11b_SEND.send.bits[7].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \data_out_11b_e[7] ), 
    .\L.0 ( \n_30.0 ), 
    .\L.1 ( \n_30.1 ), 
    .\L.e ( \n_30.e ), 
    .\R.0 ( \data_out_11b_d[0][7] ), 
    .\R.1 ( \data_out_11b_d[1][7] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_15_inst_data_out_11b_SEND.send.bits[8].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \data_out_11b_e[8] ), 
    .\L.0 ( \d[5].0 ), 
    .\L.1 ( \d[5].1 ), 
    .\L.e ( \d[5]_15.e ), 
    .\R.0 ( \data_out_11b_d[0][8] ), 
    .\R.1 ( \data_out_11b_d[1][8] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_16_inst_data_out_11b_SEND.send.bits[9].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \data_out_11b_e[9] ), 
    .\L.0 ( \d[6].0 ), 
    .\L.1 ( \d[6].1 ), 
    .\L.e ( \d[6]_16.e ), 
    .\R.0 ( \data_out_11b_d[0][9] ), 
    .\R.1 ( \data_out_11b_d[1][9] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_17_inst_CFMOD_dg_8b_RECEIVE.recv.bits[0].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \dg_8b_d[0][0] ), 
    .\R.0 ( \data_out_11b_d[0][0] ), 
    .\L.1 ( \dg_8b_d[1][0] ), 
    .\R.1 ( \data_out_11b_d[1][0] ), 
    .\L.e ( \dg_8b_e[0] ), 
    .\R.e ( \data_out_11b_e[0] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_18_inst_CFMOD_dg_8b_RECEIVE.recv.bits[1].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \dg_8b_d[0][1] ), 
    .\R.0 ( \data_out_11b_d[0][1] ), 
    .\L.1 ( \dg_8b_d[1][1] ), 
    .\R.1 ( \data_out_11b_d[1][1] ), 
    .\L.e ( \dg_8b_e[1] ), 
    .\R.e ( \data_out_11b_e[1] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_19_inst_CFMOD_dg_8b_RECEIVE.recv.bits[2].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \dg_8b_d[0][2] ), 
    .\R.0 ( \data_out_11b_d[0][2] ), 
    .\L.1 ( \dg_8b_d[1][2] ), 
    .\R.1 ( \data_out_11b_d[1][2] ), 
    .\L.e ( \dg_8b_e[2] ), 
    .\R.e ( \data_out_11b_e[2] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_20_inst_CFMOD_dg_8b_RECEIVE.recv.bits[3].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \dg_8b_d[0][3] ), 
    .\R.0 ( \data_out_11b_d[0][3] ), 
    .\L.1 ( \dg_8b_d[1][3] ), 
    .\R.1 ( \data_out_11b_d[1][3] ), 
    .\L.e ( \dg_8b_e[3] ), 
    .\R.e ( \data_out_11b_e[3] ));
  \synthesis.qdi.logic3.LOGIC3_69.2 \core_dg_RTL_BODY.g73 ( 
    .V ( \pchb_cloud_22_inst_valid_out_1 ), 
    .en ( \pchb_cloud_22_inst_en0 ), 
    .\A[0].0 ( \d[5].1 ), 
    .\A[0].1 ( \d[5].0 ), 
    .\A[1].0 ( \d[6].0 ), 
    .\A[1].1 ( \d[6].1 ), 
    .\A[2].0 ( \d[7].0 ), 
    .\A[2].1 ( \d[7].1 ), 
    .\X.0 ( \n_30.0 ), 
    .\X.1 ( \n_30.1 ));
  \synthesis.qdi.logic3.LOGIC3_69.2 \core_dg_RTL_BODY.g74 ( 
    .V ( \pchb_cloud_22_inst_valid_out_2 ), 
    .en ( \pchb_cloud_22_inst_en0 ), 
    .\A[0].0 ( \d[4].1 ), 
    .\A[0].1 ( \d[4].0 ), 
    .\A[1].0 ( \d[6].0 ), 
    .\A[1].1 ( \d[6].1 ), 
    .\A[2].0 ( \d[7].0 ), 
    .\A[2].1 ( \d[7].1 ), 
    .\X.0 ( \n_32.0 ), 
    .\X.1 ( \n_32.1 ));
  \synthesis.qdi.logic3.LOGIC3_69.2 \core_dg_RTL_BODY.g75 ( 
    .V ( \pchb_cloud_22_inst_valid_out_0 ), 
    .en ( \pchb_cloud_22_inst_en0 ), 
    .\A[0].0 ( \d[4].1 ), 
    .\A[0].1 ( \d[4].0 ), 
    .\A[1].0 ( \d[5].0 ), 
    .\A[1].1 ( \d[5].1 ), 
    .\A[2].0 ( \d[7].0 ), 
    .\A[2].1 ( \d[7].1 ), 
    .\X.0 ( \n_33.0 ), 
    .\X.1 ( \n_33.1 ));
  \synthesis.qdi.special.CTRL43.2 \pchb_cloud_22_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_22_inst_go ), 
    .Ae ( \c22.e ), 
    .\A[0].0 ( \d[4].0 ), 
    .\A[0].1 ( \d[4].1 ), 
    .\A[1].0 ( \d[5].0 ), 
    .\A[1].1 ( \d[5].1 ), 
    .\A[2].0 ( \d[6].0 ), 
    .\A[2].1 ( \d[6].1 ), 
    .\A[3].0 ( \d[7].0 ), 
    .\A[3].1 ( \d[7].1 ), 
    .\V[0] ( \pchb_cloud_22_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_22_inst_valid_out_1 ), 
    .\V[2] ( \pchb_cloud_22_inst_valid_out_2 ));
  \synthesis.qdi.special.CTREE4.2 \ctreecore_dg_RTL_BODY.g75 ( 
    .\a[0] ( \pchb_cloud_22_inst_go ), 
    .\a[1] ( \n_30.e ), 
    .\a[2] ( \n_32.e ), 
    .\a[3] ( \n_33.e ), 
    .x ( \pchb_cloud_22_inst_en0 ));

endmodule
