

// Generated by cosim_wrapper.pl to be used for cosim

module core_db_cosim_wrapper(interface data_in_11b_e, interface , interface db_8b, interface data_in_11b, interface db_8b_e, input _RESET);

 core_db core_db_expanded (data_in_11b.d[0].d[0][0] , data_in_11b.d[0].d[1][0] , data_in_11b.d[0].d[0][10] , data_in_11b.d[0].d[1][10] , data_in_11b.d[0].d[0][1] , data_in_11b.d[0].d[1][1] 
 , data_in_11b.d[0].d[0][2] , data_in_11b.d[0].d[1][2] , data_in_11b.d[0].d[0][3] , data_in_11b.d[0].d[1][3] , data_in_11b.d[0].d[0][4] , data_in_11b.d[0].d[1][4] 
 , data_in_11b.d[0].d[0][5] , data_in_11b.d[0].d[1][5] , data_in_11b.d[0].d[0][6] , data_in_11b.d[0].d[1][6] , data_in_11b.d[0].d[0][7] , data_in_11b.d[0].d[1][7] 
 , data_in_11b.d[0].d[0][8] , data_in_11b.d[0].d[1][8] , data_in_11b.d[0].d[0][9] , data_in_11b.d[0].d[1][9] , data_in_11b.d[1].d[0][0] , data_in_11b.d[1].d[1][0] 
 , data_in_11b.d[1].d[0][10] , data_in_11b.d[1].d[1][10] , data_in_11b.d[1].d[0][1] , data_in_11b.d[1].d[1][1] , data_in_11b.d[1].d[0][2] , data_in_11b.d[1].d[1][2] 
 , data_in_11b.d[1].d[0][3] , data_in_11b.d[1].d[1][3] , data_in_11b.d[1].d[0][4] , data_in_11b.d[1].d[1][4] , data_in_11b.d[1].d[0][5] , data_in_11b.d[1].d[1][5] 
 , data_in_11b.d[1].d[0][6] , data_in_11b.d[1].d[1][6] , data_in_11b.d[1].d[0][7] , data_in_11b.d[1].d[1][7] , data_in_11b.d[1].d[0][8] , data_in_11b.d[1].d[1][8] 
 , data_in_11b.d[1].d[0][9] , data_in_11b.d[1].d[1][9] , data_in_11b_e.e[0] , data_in_11b_e.e[10] , data_in_11b_e.e[1] , data_in_11b_e.e[2] 
 , data_in_11b_e.e[3] , data_in_11b_e.e[4] , data_in_11b_e.e[5] , data_in_11b_e.e[6] , data_in_11b_e.e[7] , data_in_11b_e.e[8] 
 , data_in_11b_e.e[9] , db_8b.d[0].e[0] , db_8b.d[1].e[0] , db_8b.d[2].e[0] , db_8b.d[3].e[0] , db_8b.d[4].e[0] 
 , db_8b.d[5].e[0] , db_8b.d[6].e[0] , db_8b.d[7].e[0] , db_8b.d[0].e[1] , db_8b.d[1].e[1] , db_8b.d[2].e[1] 
 , db_8b.d[3].e[1] , db_8b.d[4].e[1] , db_8b.d[5].e[1] , db_8b.d[6].e[1] , db_8b.d[7].e[1] , db_8b_e.d[0][0] 
 , db_8b_e.d[1][0] , db_8b_e.d[0][1] , db_8b_e.d[1][1] , db_8b_e.d[0][2] , db_8b_e.d[1][2] , db_8b_e.d[0][3] 
 , db_8b_e.d[1][3] , db_8b_e.d[0][4] , db_8b_e.d[1][4] , db_8b_e.d[0][5] , db_8b_e.d[1][5] , db_8b_e.d[0][6] 
 , db_8b_e.d[1][6] , db_8b_e.d[0][7] , db_8b_e.d[1][7] , data_in_11b.d[0].e[0] , data_in_11b.d[10].e[0] , data_in_11b.d[1].e[0] 
 , data_in_11b.d[2].e[0] , data_in_11b.d[3].e[0] , data_in_11b.d[4].e[0] , data_in_11b.d[5].e[0] , data_in_11b.d[6].e[0] , data_in_11b.d[7].e[0] 
 , data_in_11b.d[8].e[0] , data_in_11b.d[9].e[0] , data_in_11b.d[0].e[1] , data_in_11b.d[10].e[1] , data_in_11b.d[1].e[1] , data_in_11b.d[2].e[1] 
 , data_in_11b.d[3].e[1] , data_in_11b.d[4].e[1] , data_in_11b.d[5].e[1] , data_in_11b.d[6].e[1] , data_in_11b.d[7].e[1] , data_in_11b.d[8].e[1] 
 , data_in_11b.d[9].e[1] , data_in_11b_e.d[0][0] , data_in_11b_e.d[1][0] , data_in_11b_e.d[0][10] , data_in_11b_e.d[1][10] , data_in_11b_e.d[0][1] 
 , data_in_11b_e.d[1][1] , data_in_11b_e.d[0][2] , data_in_11b_e.d[1][2] , data_in_11b_e.d[0][3] , data_in_11b_e.d[1][3] , data_in_11b_e.d[0][4] 
 , data_in_11b_e.d[1][4] , data_in_11b_e.d[0][5] , data_in_11b_e.d[1][5] , data_in_11b_e.d[0][6] , data_in_11b_e.d[1][6] , data_in_11b_e.d[0][7] 
 , data_in_11b_e.d[1][7] , data_in_11b_e.d[0][8] , data_in_11b_e.d[1][8] , data_in_11b_e.d[0][9] , data_in_11b_e.d[1][9] , db_8b.d[0].d[0][0] 
 , db_8b.d[0].d[1][0] , db_8b.d[0].d[0][1] , db_8b.d[0].d[1][1] , db_8b.d[0].d[0][2] , db_8b.d[0].d[1][2] , db_8b.d[0].d[0][3] 
 , db_8b.d[0].d[1][3] , db_8b.d[0].d[0][4] , db_8b.d[0].d[1][4] , db_8b.d[0].d[0][5] , db_8b.d[0].d[1][5] , db_8b.d[0].d[0][6] 
 , db_8b.d[0].d[1][6] , db_8b.d[0].d[0][7] , db_8b.d[0].d[1][7] , db_8b.d[1].d[0][0] , db_8b.d[1].d[1][0] , db_8b.d[1].d[0][1] 
 , db_8b.d[1].d[1][1] , db_8b.d[1].d[0][2] , db_8b.d[1].d[1][2] , db_8b.d[1].d[0][3] , db_8b.d[1].d[1][3] , db_8b.d[1].d[0][4] 
 , db_8b.d[1].d[1][4] , db_8b.d[1].d[0][5] , db_8b.d[1].d[1][5] , db_8b.d[1].d[0][6] , db_8b.d[1].d[1][6] , db_8b.d[1].d[0][7] 
 , db_8b.d[1].d[1][7] , db_8b_e.e[0] , db_8b_e.e[1] , db_8b_e.e[2] , db_8b_e.e[3] , db_8b_e.e[4] 
 , db_8b_e.e[5] , db_8b_e.e[6] , db_8b_e.e[7] , _RESET );

endmodule

// Generated by E-GRAPH (EGS) v0.01

module core_db (\data_in_11b_d[0][0].0 , \data_in_11b_d[0][0].1 , \data_in_11b_d[0][10].0 , \data_in_11b_d[0][10].1 , 
  \data_in_11b_d[0][1].0 , \data_in_11b_d[0][1].1 , \data_in_11b_d[0][2].0 , \data_in_11b_d[0][2].1 , \data_in_11b_d[0][3].0 , 
  \data_in_11b_d[0][3].1 , \data_in_11b_d[0][4].0 , \data_in_11b_d[0][4].1 , \data_in_11b_d[0][5].0 , \data_in_11b_d[0][5].1 , 
  \data_in_11b_d[0][6].0 , \data_in_11b_d[0][6].1 , \data_in_11b_d[0][7].0 , \data_in_11b_d[0][7].1 , \data_in_11b_d[0][8].0 , 
  \data_in_11b_d[0][8].1 , \data_in_11b_d[0][9].0 , \data_in_11b_d[0][9].1 , \data_in_11b_d[1][0].0 , \data_in_11b_d[1][0].1 , 
  \data_in_11b_d[1][10].0 , \data_in_11b_d[1][10].1 , \data_in_11b_d[1][1].0 , \data_in_11b_d[1][1].1 , \data_in_11b_d[1][2].0 , 
  \data_in_11b_d[1][2].1 , \data_in_11b_d[1][3].0 , \data_in_11b_d[1][3].1 , \data_in_11b_d[1][4].0 , \data_in_11b_d[1][4].1 , 
  \data_in_11b_d[1][5].0 , \data_in_11b_d[1][5].1 , \data_in_11b_d[1][6].0 , \data_in_11b_d[1][6].1 , \data_in_11b_d[1][7].0 , 
  \data_in_11b_d[1][7].1 , \data_in_11b_d[1][8].0 , \data_in_11b_d[1][8].1 , \data_in_11b_d[1][9].0 , \data_in_11b_d[1][9].1 , 
  \data_in_11b_e[0].e , \data_in_11b_e[10].e , \data_in_11b_e[1].e , \data_in_11b_e[2].e , \data_in_11b_e[3].e , 
  \data_in_11b_e[4].e , \data_in_11b_e[5].e , \data_in_11b_e[6].e , \data_in_11b_e[7].e , \data_in_11b_e[8].e , 
  \data_in_11b_e[9].e , \db_8b_d[0][0].e , \db_8b_d[0][1].e , \db_8b_d[0][2].e , \db_8b_d[0][3].e , \db_8b_d[0][4].e , 
  \db_8b_d[0][5].e , \db_8b_d[0][6].e , \db_8b_d[0][7].e , \db_8b_d[1][0].e , \db_8b_d[1][1].e , \db_8b_d[1][2].e , 
  \db_8b_d[1][3].e , \db_8b_d[1][4].e , \db_8b_d[1][5].e , \db_8b_d[1][6].e , \db_8b_d[1][7].e , \db_8b_e[0].0 , \db_8b_e[0].1 , 
  \db_8b_e[1].0 , \db_8b_e[1].1 , \db_8b_e[2].0 , \db_8b_e[2].1 , \db_8b_e[3].0 , \db_8b_e[3].1 , \db_8b_e[4].0 , \db_8b_e[4].1 , 
  \db_8b_e[5].0 , \db_8b_e[5].1 , \db_8b_e[6].0 , \db_8b_e[6].1 , \db_8b_e[7].0 , \db_8b_e[7].1 , \data_in_11b_d[0][0].e , 
  \data_in_11b_d[0][10].e , \data_in_11b_d[0][1].e , \data_in_11b_d[0][2].e , \data_in_11b_d[0][3].e , \data_in_11b_d[0][4].e , 
  \data_in_11b_d[0][5].e , \data_in_11b_d[0][6].e , \data_in_11b_d[0][7].e , \data_in_11b_d[0][8].e , \data_in_11b_d[0][9].e , 
  \data_in_11b_d[1][0].e , \data_in_11b_d[1][10].e , \data_in_11b_d[1][1].e , \data_in_11b_d[1][2].e , \data_in_11b_d[1][3].e , 
  \data_in_11b_d[1][4].e , \data_in_11b_d[1][5].e , \data_in_11b_d[1][6].e , \data_in_11b_d[1][7].e , \data_in_11b_d[1][8].e , 
  \data_in_11b_d[1][9].e , \data_in_11b_e[0].0 , \data_in_11b_e[0].1 , \data_in_11b_e[10].0 , \data_in_11b_e[10].1 , 
  \data_in_11b_e[1].0 , \data_in_11b_e[1].1 , \data_in_11b_e[2].0 , \data_in_11b_e[2].1 , \data_in_11b_e[3].0 , 
  \data_in_11b_e[3].1 , \data_in_11b_e[4].0 , \data_in_11b_e[4].1 , \data_in_11b_e[5].0 , \data_in_11b_e[5].1 , 
  \data_in_11b_e[6].0 , \data_in_11b_e[6].1 , \data_in_11b_e[7].0 , \data_in_11b_e[7].1 , \data_in_11b_e[8].0 , 
  \data_in_11b_e[8].1 , \data_in_11b_e[9].0 , \data_in_11b_e[9].1 , \db_8b_d[0][0].0 , \db_8b_d[0][0].1 , \db_8b_d[0][1].0 , 
  \db_8b_d[0][1].1 , \db_8b_d[0][2].0 , \db_8b_d[0][2].1 , \db_8b_d[0][3].0 , \db_8b_d[0][3].1 , \db_8b_d[0][4].0 , 
  \db_8b_d[0][4].1 , \db_8b_d[0][5].0 , \db_8b_d[0][5].1 , \db_8b_d[0][6].0 , \db_8b_d[0][6].1 , \db_8b_d[0][7].0 , 
  \db_8b_d[0][7].1 , \db_8b_d[1][0].0 , \db_8b_d[1][0].1 , \db_8b_d[1][1].0 , \db_8b_d[1][1].1 , \db_8b_d[1][2].0 , 
  \db_8b_d[1][2].1 , \db_8b_d[1][3].0 , \db_8b_d[1][3].1 , \db_8b_d[1][4].0 , \db_8b_d[1][4].1 , \db_8b_d[1][5].0 , 
  \db_8b_d[1][5].1 , \db_8b_d[1][6].0 , \db_8b_d[1][6].1 , \db_8b_d[1][7].0 , \db_8b_d[1][7].1 , \db_8b_e[0].e , \db_8b_e[1].e , 
  \db_8b_e[2].e , \db_8b_e[3].e , \db_8b_e[4].e , \db_8b_e[5].e , \db_8b_e[6].e , \db_8b_e[7].e , _RESET );
  input  \data_in_11b_d[0][0].e , \data_in_11b_d[0][10].e , \data_in_11b_d[0][1].e , \data_in_11b_d[0][2].e ;
  input  \data_in_11b_d[0][3].e , \data_in_11b_d[0][4].e , \data_in_11b_d[0][5].e , \data_in_11b_d[0][6].e ;
  input  \data_in_11b_d[0][7].e , \data_in_11b_d[0][8].e , \data_in_11b_d[0][9].e , \data_in_11b_d[1][0].e ;
  input  \data_in_11b_d[1][10].e , \data_in_11b_d[1][1].e , \data_in_11b_d[1][2].e , \data_in_11b_d[1][3].e ;
  input  \data_in_11b_d[1][4].e , \data_in_11b_d[1][5].e , \data_in_11b_d[1][6].e , \data_in_11b_d[1][7].e ;
  input  \data_in_11b_d[1][8].e , \data_in_11b_d[1][9].e , \data_in_11b_e[0].0 , \data_in_11b_e[0].1 , \data_in_11b_e[10].0 ;
  input  \data_in_11b_e[10].1 , \data_in_11b_e[1].0 , \data_in_11b_e[1].1 , \data_in_11b_e[2].0 , \data_in_11b_e[2].1 ;
  input  \data_in_11b_e[3].0 , \data_in_11b_e[3].1 , \data_in_11b_e[4].0 , \data_in_11b_e[4].1 , \data_in_11b_e[5].0 ;
  input  \data_in_11b_e[5].1 , \data_in_11b_e[6].0 , \data_in_11b_e[6].1 , \data_in_11b_e[7].0 , \data_in_11b_e[7].1 ;
  input  \data_in_11b_e[8].0 , \data_in_11b_e[8].1 , \data_in_11b_e[9].0 , \data_in_11b_e[9].1 , \db_8b_d[0][0].0 ;
  input  \db_8b_d[0][0].1 , \db_8b_d[0][1].0 , \db_8b_d[0][1].1 , \db_8b_d[0][2].0 , \db_8b_d[0][2].1 , \db_8b_d[0][3].0 ;
  input  \db_8b_d[0][3].1 , \db_8b_d[0][4].0 , \db_8b_d[0][4].1 , \db_8b_d[0][5].0 , \db_8b_d[0][5].1 , \db_8b_d[0][6].0 ;
  input  \db_8b_d[0][6].1 , \db_8b_d[0][7].0 , \db_8b_d[0][7].1 , \db_8b_d[1][0].0 , \db_8b_d[1][0].1 , \db_8b_d[1][1].0 ;
  input  \db_8b_d[1][1].1 , \db_8b_d[1][2].0 , \db_8b_d[1][2].1 , \db_8b_d[1][3].0 , \db_8b_d[1][3].1 , \db_8b_d[1][4].0 ;
  input  \db_8b_d[1][4].1 , \db_8b_d[1][5].0 , \db_8b_d[1][5].1 , \db_8b_d[1][6].0 , \db_8b_d[1][6].1 , \db_8b_d[1][7].0 ;
  input  \db_8b_d[1][7].1 , \db_8b_e[0].e , \db_8b_e[1].e , \db_8b_e[2].e , \db_8b_e[3].e , \db_8b_e[4].e , \db_8b_e[5].e ;
  input  \db_8b_e[6].e , \db_8b_e[7].e , _RESET ;

  output \data_in_11b_d[0][0].0 , \data_in_11b_d[0][0].1 , \data_in_11b_d[0][10].0 , \data_in_11b_d[0][10].1 ;
  output \data_in_11b_d[0][1].0 , \data_in_11b_d[0][1].1 , \data_in_11b_d[0][2].0 , \data_in_11b_d[0][2].1 ;
  output \data_in_11b_d[0][3].0 , \data_in_11b_d[0][3].1 , \data_in_11b_d[0][4].0 , \data_in_11b_d[0][4].1 ;
  output \data_in_11b_d[0][5].0 , \data_in_11b_d[0][5].1 , \data_in_11b_d[0][6].0 , \data_in_11b_d[0][6].1 ;
  output \data_in_11b_d[0][7].0 , \data_in_11b_d[0][7].1 , \data_in_11b_d[0][8].0 , \data_in_11b_d[0][8].1 ;
  output \data_in_11b_d[0][9].0 , \data_in_11b_d[0][9].1 , \data_in_11b_d[1][0].0 , \data_in_11b_d[1][0].1 ;
  output \data_in_11b_d[1][10].0 , \data_in_11b_d[1][10].1 , \data_in_11b_d[1][1].0 , \data_in_11b_d[1][1].1 ;
  output \data_in_11b_d[1][2].0 , \data_in_11b_d[1][2].1 , \data_in_11b_d[1][3].0 , \data_in_11b_d[1][3].1 ;
  output \data_in_11b_d[1][4].0 , \data_in_11b_d[1][4].1 , \data_in_11b_d[1][5].0 , \data_in_11b_d[1][5].1 ;
  output \data_in_11b_d[1][6].0 , \data_in_11b_d[1][6].1 , \data_in_11b_d[1][7].0 , \data_in_11b_d[1][7].1 ;
  output \data_in_11b_d[1][8].0 , \data_in_11b_d[1][8].1 , \data_in_11b_d[1][9].0 , \data_in_11b_d[1][9].1 ;
  output \data_in_11b_e[0].e , \data_in_11b_e[10].e , \data_in_11b_e[1].e , \data_in_11b_e[2].e , \data_in_11b_e[3].e ;
  output \data_in_11b_e[4].e , \data_in_11b_e[5].e , \data_in_11b_e[6].e , \data_in_11b_e[7].e , \data_in_11b_e[8].e ;
  output \data_in_11b_e[9].e , \db_8b_d[0][0].e , \db_8b_d[0][1].e , \db_8b_d[0][2].e , \db_8b_d[0][3].e , \db_8b_d[0][4].e ;
  output \db_8b_d[0][5].e , \db_8b_d[0][6].e , \db_8b_d[0][7].e , \db_8b_d[1][0].e , \db_8b_d[1][1].e , \db_8b_d[1][2].e ;
  output \db_8b_d[1][3].e , \db_8b_d[1][4].e , \db_8b_d[1][5].e , \db_8b_d[1][6].e , \db_8b_d[1][7].e , \db_8b_e[0].0 ;
  output \db_8b_e[0].1 , \db_8b_e[1].0 , \db_8b_e[1].1 , \db_8b_e[2].0 , \db_8b_e[2].1 , \db_8b_e[3].0 , \db_8b_e[3].1 ;
  output \db_8b_e[4].0 , \db_8b_e[4].1 , \db_8b_e[5].0 , \db_8b_e[5].1 , \db_8b_e[6].0 , \db_8b_e[6].1 , \db_8b_e[7].0 ;
  output \db_8b_e[7].1 ;

  wire   \data_in_11b_e[0].e , \data_in_11b_e[10].e , \data_in_11b_e[1].e , \data_in_11b_e[2].e , \data_in_11b_e[3].e ;
  wire   \data_in_11b_e[4].e , \data_in_11b_e[5].e , \data_in_11b_e[6].e , \data_in_11b_e[7].e , \data_in_11b_e[8].e ;
  wire   \data_in_11b_e[9].e , \db_8b_d[0][0].e , \db_8b_d[0][1].e , \db_8b_d[0][2].e , \db_8b_d[0][3].e , \db_8b_d[0][4].e ;
  wire   \db_8b_d[0][5].e , \db_8b_d[0][6].e , \db_8b_d[0][7].e , \db_8b_d[1][0].e , \db_8b_d[1][1].e , \db_8b_d[1][2].e ;
  wire   \db_8b_d[1][3].e , \db_8b_d[1][4].e , \db_8b_d[1][5].e , \db_8b_d[1][6].e , \db_8b_d[1][7].e ;



  assign \data_in_11b_d[0][0].0 = 1'b0 ;
  assign \data_in_11b_d[0][10].0 = 1'b0 ;
  assign \data_in_11b_d[0][1].0 = 1'b0 ;
  assign \data_in_11b_d[0][2].0 = 1'b0 ;
  assign \data_in_11b_d[0][3].0 = 1'b0 ;
  assign \data_in_11b_d[0][4].0 = 1'b0 ;
  assign \data_in_11b_d[0][5].0 = 1'b0 ;
  assign \data_in_11b_d[0][6].0 = 1'b0 ;
  assign \data_in_11b_d[0][7].0 = 1'b0 ;
  assign \data_in_11b_d[0][8].0 = 1'b0 ;
  assign \data_in_11b_d[0][9].0 = 1'b0 ;
  assign \data_in_11b_d[1][0].0 = 1'b0 ;
  assign \data_in_11b_d[1][10].0 = 1'b0 ;
  assign \data_in_11b_d[1][1].0 = 1'b0 ;
  assign \data_in_11b_d[1][2].0 = 1'b0 ;
  assign \data_in_11b_d[1][3].0 = 1'b0 ;
  assign \data_in_11b_d[1][4].0 = 1'b0 ;
  assign \data_in_11b_d[1][5].0 = 1'b0 ;
  assign \data_in_11b_d[1][6].0 = 1'b0 ;
  assign \data_in_11b_d[1][7].0 = 1'b0 ;
  assign \data_in_11b_d[1][8].0 = 1'b0 ;
  assign \data_in_11b_d[1][9].0 = 1'b0 ;
  assign \db_8b_e[0].0 = 1'b0 ;
  assign \db_8b_e[1].0 = 1'b0 ;
  assign \db_8b_e[2].0 = 1'b0 ;
  assign \db_8b_e[3].0 = 1'b0 ;
  assign \db_8b_e[4].0 = 1'b0 ;
  assign \db_8b_e[5].0 = 1'b0 ;
  assign \db_8b_e[6].0 = 1'b0 ;
  assign \db_8b_e[7].0 = 1'b0 ;

  \synthesis.qdi.special.BB.2 \data_in_11b_e[0]_bb_inst_data_in_11b_e[0]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \data_in_11b_e[0].0 ), 
    .\L.1 ( \data_in_11b_e[0].1 ), 
    .\L.e ( \data_in_11b_e[0].e ));
  \synthesis.qdi.special.BB.2 \data_in_11b_e[10]_bb_inst_data_in_11b_e[10]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \data_in_11b_e[10].0 ), 
    .\L.1 ( \data_in_11b_e[10].1 ), 
    .\L.e ( \data_in_11b_e[10].e ));
  \synthesis.qdi.special.BB.2 \data_in_11b_e[1]_bb_inst_data_in_11b_e[1]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \data_in_11b_e[1].0 ), 
    .\L.1 ( \data_in_11b_e[1].1 ), 
    .\L.e ( \data_in_11b_e[1].e ));
  \synthesis.qdi.special.BB.2 \data_in_11b_e[2]_bb_inst_data_in_11b_e[2]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \data_in_11b_e[2].0 ), 
    .\L.1 ( \data_in_11b_e[2].1 ), 
    .\L.e ( \data_in_11b_e[2].e ));
  \synthesis.qdi.special.BB.2 \data_in_11b_e[3]_bb_inst_data_in_11b_e[3]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \data_in_11b_e[3].0 ), 
    .\L.1 ( \data_in_11b_e[3].1 ), 
    .\L.e ( \data_in_11b_e[3].e ));
  \synthesis.qdi.special.BB.2 \data_in_11b_e[4]_bb_inst_data_in_11b_e[4]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \data_in_11b_e[4].0 ), 
    .\L.1 ( \data_in_11b_e[4].1 ), 
    .\L.e ( \data_in_11b_e[4].e ));
  \synthesis.qdi.special.BB.2 \data_in_11b_e[5]_bb_inst_data_in_11b_e[5]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \data_in_11b_e[5].0 ), 
    .\L.1 ( \data_in_11b_e[5].1 ), 
    .\L.e ( \data_in_11b_e[5].e ));
  \synthesis.qdi.special.BB.2 \data_in_11b_e[6]_bb_inst_data_in_11b_e[6]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \data_in_11b_e[6].0 ), 
    .\L.1 ( \data_in_11b_e[6].1 ), 
    .\L.e ( \data_in_11b_e[6].e ));
  \synthesis.qdi.special.BB.2 \data_in_11b_e[7]_bb_inst_data_in_11b_e[7]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \data_in_11b_e[7].0 ), 
    .\L.1 ( \data_in_11b_e[7].1 ), 
    .\L.e ( \data_in_11b_e[7].e ));
  \synthesis.qdi.special.BB.2 \data_in_11b_e[8]_bb_inst_data_in_11b_e[8]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \data_in_11b_e[8].0 ), 
    .\L.1 ( \data_in_11b_e[8].1 ), 
    .\L.e ( \data_in_11b_e[8].e ));
  \synthesis.qdi.special.BB.2 \data_in_11b_e[9]_bb_inst_data_in_11b_e[9]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \data_in_11b_e[9].0 ), 
    .\L.1 ( \data_in_11b_e[9].1 ), 
    .\L.e ( \data_in_11b_e[9].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[0][0]_bb_inst_db_8b_d[0][0]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[0][0].0 ), 
    .\L.1 ( \db_8b_d[0][0].1 ), 
    .\L.e ( \db_8b_d[0][0].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[0][1]_bb_inst_db_8b_d[0][1]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[0][1].0 ), 
    .\L.1 ( \db_8b_d[0][1].1 ), 
    .\L.e ( \db_8b_d[0][1].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[0][2]_bb_inst_db_8b_d[0][2]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[0][2].0 ), 
    .\L.1 ( \db_8b_d[0][2].1 ), 
    .\L.e ( \db_8b_d[0][2].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[0][3]_bb_inst_db_8b_d[0][3]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[0][3].0 ), 
    .\L.1 ( \db_8b_d[0][3].1 ), 
    .\L.e ( \db_8b_d[0][3].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[0][4]_bb_inst_db_8b_d[0][4]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[0][4].0 ), 
    .\L.1 ( \db_8b_d[0][4].1 ), 
    .\L.e ( \db_8b_d[0][4].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[0][5]_bb_inst_db_8b_d[0][5]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[0][5].0 ), 
    .\L.1 ( \db_8b_d[0][5].1 ), 
    .\L.e ( \db_8b_d[0][5].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[0][6]_bb_inst_db_8b_d[0][6]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[0][6].0 ), 
    .\L.1 ( \db_8b_d[0][6].1 ), 
    .\L.e ( \db_8b_d[0][6].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[0][7]_bb_inst_db_8b_d[0][7]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[0][7].0 ), 
    .\L.1 ( \db_8b_d[0][7].1 ), 
    .\L.e ( \db_8b_d[0][7].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[1][0]_bb_inst_db_8b_d[1][0]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[1][0].0 ), 
    .\L.1 ( \db_8b_d[1][0].1 ), 
    .\L.e ( \db_8b_d[1][0].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[1][1]_bb_inst_db_8b_d[1][1]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[1][1].0 ), 
    .\L.1 ( \db_8b_d[1][1].1 ), 
    .\L.e ( \db_8b_d[1][1].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[1][2]_bb_inst_db_8b_d[1][2]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[1][2].0 ), 
    .\L.1 ( \db_8b_d[1][2].1 ), 
    .\L.e ( \db_8b_d[1][2].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[1][3]_bb_inst_db_8b_d[1][3]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[1][3].0 ), 
    .\L.1 ( \db_8b_d[1][3].1 ), 
    .\L.e ( \db_8b_d[1][3].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[1][4]_bb_inst_db_8b_d[1][4]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[1][4].0 ), 
    .\L.1 ( \db_8b_d[1][4].1 ), 
    .\L.e ( \db_8b_d[1][4].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[1][5]_bb_inst_db_8b_d[1][5]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[1][5].0 ), 
    .\L.1 ( \db_8b_d[1][5].1 ), 
    .\L.e ( \db_8b_d[1][5].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[1][6]_bb_inst_db_8b_d[1][6]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[1][6].0 ), 
    .\L.1 ( \db_8b_d[1][6].1 ), 
    .\L.e ( \db_8b_d[1][6].e ));
  \synthesis.qdi.special.BB.2 \db_8b_d[1][7]_bb_inst_db_8b_d[1][7]_bb ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \db_8b_d[1][7].0 ), 
    .\L.1 ( \db_8b_d[1][7].1 ), 
    .\L.e ( \db_8b_d[1][7].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[0][0].1 ( 
    .x ( \data_in_11b_d[0][0].1 ), 
    .a ( \data_in_11b_d[0][0].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[0][10].1 ( 
    .x ( \data_in_11b_d[0][10].1 ), 
    .a ( \data_in_11b_d[0][10].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[0][1].1 ( 
    .x ( \data_in_11b_d[0][1].1 ), 
    .a ( \data_in_11b_d[0][1].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[0][2].1 ( 
    .x ( \data_in_11b_d[0][2].1 ), 
    .a ( \data_in_11b_d[0][2].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[0][3].1 ( 
    .x ( \data_in_11b_d[0][3].1 ), 
    .a ( \data_in_11b_d[0][3].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[0][4].1 ( 
    .x ( \data_in_11b_d[0][4].1 ), 
    .a ( \data_in_11b_d[0][4].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[0][5].1 ( 
    .x ( \data_in_11b_d[0][5].1 ), 
    .a ( \data_in_11b_d[0][5].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[0][6].1 ( 
    .x ( \data_in_11b_d[0][6].1 ), 
    .a ( \data_in_11b_d[0][6].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[0][7].1 ( 
    .x ( \data_in_11b_d[0][7].1 ), 
    .a ( \data_in_11b_d[0][7].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[0][8].1 ( 
    .x ( \data_in_11b_d[0][8].1 ), 
    .a ( \data_in_11b_d[0][8].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[0][9].1 ( 
    .x ( \data_in_11b_d[0][9].1 ), 
    .a ( \data_in_11b_d[0][9].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[1][0].1 ( 
    .x ( \data_in_11b_d[1][0].1 ), 
    .a ( \data_in_11b_d[1][0].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[1][10].1 ( 
    .x ( \data_in_11b_d[1][10].1 ), 
    .a ( \data_in_11b_d[1][10].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[1][1].1 ( 
    .x ( \data_in_11b_d[1][1].1 ), 
    .a ( \data_in_11b_d[1][1].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[1][2].1 ( 
    .x ( \data_in_11b_d[1][2].1 ), 
    .a ( \data_in_11b_d[1][2].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[1][3].1 ( 
    .x ( \data_in_11b_d[1][3].1 ), 
    .a ( \data_in_11b_d[1][3].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[1][4].1 ( 
    .x ( \data_in_11b_d[1][4].1 ), 
    .a ( \data_in_11b_d[1][4].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[1][5].1 ( 
    .x ( \data_in_11b_d[1][5].1 ), 
    .a ( \data_in_11b_d[1][5].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[1][6].1 ( 
    .x ( \data_in_11b_d[1][6].1 ), 
    .a ( \data_in_11b_d[1][6].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[1][7].1 ( 
    .x ( \data_in_11b_d[1][7].1 ), 
    .a ( \data_in_11b_d[1][7].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[1][8].1 ( 
    .x ( \data_in_11b_d[1][8].1 ), 
    .a ( \data_in_11b_d[1][8].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_data_in_11b_d[1][9].1 ( 
    .x ( \data_in_11b_d[1][9].1 ), 
    .a ( \data_in_11b_d[1][9].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_db_8b_e[0].1 ( 
    .x ( \db_8b_e[0].1 ), 
    .a ( \db_8b_e[0].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_db_8b_e[1].1 ( 
    .x ( \db_8b_e[1].1 ), 
    .a ( \db_8b_e[1].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_db_8b_e[2].1 ( 
    .x ( \db_8b_e[2].1 ), 
    .a ( \db_8b_e[2].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_db_8b_e[3].1 ( 
    .x ( \db_8b_e[3].1 ), 
    .a ( \db_8b_e[3].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_db_8b_e[4].1 ( 
    .x ( \db_8b_e[4].1 ), 
    .a ( \db_8b_e[4].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_db_8b_e[5].1 ( 
    .x ( \db_8b_e[5].1 ), 
    .a ( \db_8b_e[5].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_db_8b_e[6].1 ( 
    .x ( \db_8b_e[6].1 ), 
    .a ( \db_8b_e[6].e ));
  \synthesis.qdi.special.INVINV.8 \rm_assign_db_8b_e[7].1 ( 
    .x ( \db_8b_e[7].1 ), 
    .a ( \db_8b_e[7].e ));

endmodule
